Repository cortexproject/cortex, pull requests merged in 2018-09, with the labels that each got.

#951 Use HTTP server for request from query frontend.
  Gopkg.lock
  cmd/querier/main.go
  vendor/github.com/weaveworks/common/server/server.go
Labels: size/small

#986 Remove vendored proto from Makefile.
  Makefile
Labels: size/small

#987 Raise default series-per-query limit to 100K, and samples-per-query limit to 1M.
  pkg/util/validation/limits.go
Labels: size/small

#997 Ingester: Defer converting from LabelPairs to Metric until flush
  pkg/chunk/chunk_test.go
  pkg/chunk/fixtures.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/fnv.go
  pkg/ingester/flush.go
  pkg/ingester/index.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/mapper.go
  pkg/ingester/mapper_test.go
  pkg/ingester/series.go
  pkg/ingester/transfer.go
  pkg/ingester/user_state.go
Labels: type/performance

#999 Accumulate Fingerprints by append() in ingester index lookup
  pkg/ingester/index.go
Labels: component/ingester, type/performance

#1042 Lock round access to query results
  pkg/chunk/chunk_store.go
Labels: component/querier, type/bug
