Repository cortexproject/cortex, pull requests merged in 2020-11, with the labels that each got.

#3438 Add EverQuote to ADOPTERS.md
  ADOPTERS.md
Labels: size/XS

#3431 Ensure grpc keepalive on all clients
  CHANGELOG.md
  pkg/chunk/grpc/grpc_client.go
  pkg/util/grpcclient/grpcclient.go
Labels: size/S

#3434 Fixed TestSchedulerEnqueueWithFrontendDisconnect flakyness
  pkg/querier/frontend2/scheduler.go
  pkg/querier/frontend2/scheduler_test.go
Labels: size/M

#3428 Fixed faillint for ./integration tests
  Makefile
Labels: size/XS

#3440 Fix race in TestFrontend_LogsSlowQueriesFormValues.
  pkg/querier/frontend/frontend_test.go
Labels: size/S

#3433 Moved query-scheduler to pkg/scheduler
  Makefile
  pkg/api/api.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/frontend2/frontend.pb.go
  pkg/querier/frontend2/frontend.proto
  pkg/querier/frontend2/frontend2.go
  pkg/querier/frontend2/frontend2_test.go
  pkg/querier/frontend2/frontend_scheduler_worker.go
  pkg/querier/frontend2/querier_scheduler_worker.go
  pkg/scheduler/queues.go
  pkg/scheduler/queues_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/scheduler/schedulerpb/scheduler.pb.go
  pkg/scheduler/schedulerpb/scheduler.proto
  pkg/util/grpcutil/carrier.go
Labels: size/L

#3426 Upgrade Prometheus and Thanos
  CHANGELOG.md
  Makefile
  go.mod
  go.sum
  pkg/chunk/table_manager.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor.go
  pkg/ingester/wal.go
  pkg/querier/blocks_scanner.go
  pkg/storegateway/bucket_stores.go
  pkg/util/errors.go
  tools/blocksconvert/builder/series.go
  tools/blocksconvert/builder/series_iterator.go
  tools/blocksconvert/builder/symbols_iterator.go
  tools/blocksconvert/scanner/files.go
  vendor/github.com/prometheus/prometheus/storage/fanout.go
  vendor/github.com/prometheus/prometheus/storage/merge.go
  vendor/github.com/prometheus/prometheus/storage/remote/queue_manager.go
  vendor/github.com/prometheus/prometheus/tsdb/CHANGELOG.md
  vendor/github.com/prometheus/prometheus/tsdb/block.go
  vendor/github.com/prometheus/prometheus/tsdb/chunkenc/chunk.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/compact.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/errors/errors.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/index/index.go
  vendor/github.com/prometheus/prometheus/tsdb/querier.go
  vendor/github.com/prometheus/prometheus/tsdb/repair.go
  vendor/github.com/prometheus/prometheus/tsdb/tombstones/tombstones.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/checkpoint.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go
  vendor/github.com/prometheus/prometheus/util/testutil/directory.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/streamed_block_writer.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go
  vendor/github.com/thanos-io/thanos/pkg/errutil/multierror.go.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/helpers.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/runutil/runutil.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/multitsdb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/testutil/series.go
  vendor/modules.txt
Labels: size/L

#3429 Add integration test on query-scheduler
  integration/asserts.go
  integration/backward_compatibility_test.go
  integration/e2ecortex/services.go
  integration/querier_sharding_test.go
  integration/query_frontend_test.go
  pkg/querier/frontend2/querier_scheduler_worker.go
Labels: size/L

#3445 Fix query-scheduler after pkg refactoring
  pkg/cortex/cortex.go
  pkg/scheduler/scheduler.go
Labels: size/XS

#3436 fix: register querier routes explicitly with handler for instrumentation
  pkg/api/handlers.go
Labels: size/M

#3447 fix: register querier routes explicitly with handler for instrumentation
  pkg/api/handlers.go
Labels: size/M

#3347 Query the entire ingester range for series.
  integration/e2ecortex/client.go
  integration/getting_started_single_process_config_test.go
  integration/querier_test.go
  pkg/distributor/distributor.go
  pkg/ingester/client/cortex.pb.go
  pkg/ingester/client/cortex.proto
  pkg/ingester/ingester_v2.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier_test.go
Labels: size/L

#3422 Fail ingestion when a flush is going on
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3449 query-scheduler: forward error directly to frontend
  docs/configuration/config-file-reference.md
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L

#3454 Fixed query-frontend backward compatibility
  integration/backward_compatibility_test.go
  pkg/cortex/cortex.go
  pkg/frontend/v1/frontendv1pb/frontend.pb.go
  pkg/frontend/v1/frontendv1pb/frontend.proto
Labels: size/M

#3439 chore: ensure internalQuerier utilizes identical authMiddleware to API
  pkg/api/api.go
  pkg/cortex/modules.go
Labels: size/S

#3452 Added -querier.max-query-lookback and fixed -querier.max-query-into-future
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/chunk_store.go
  pkg/cortex/cortex.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/util/spanlogger/spanlogger.go
  pkg/util/validation/limits.go
Labels: size/L

#3455 Querier workers refactor, step 1
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/frontend/frontend_test.go
  pkg/frontend/v1/frontend_test.go
  pkg/querier/worker/config.go
  pkg/querier/worker/querier_scheduler_worker.go
  pkg/querier/worker/worker.go
  pkg/querier/worker/worker_frontend_manager.go
  pkg/querier/worker/worker_frontend_manager_test.go
  pkg/querier/worker/worker_test.go
  tools/doc-generator/main.go
Labels: size/M

#3460 Split ReadRing.GetAll() into two functions
  pkg/compactor/compactor_test.go
  pkg/distributor/distributor.go
  pkg/distributor/query.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/client/ring_service_discovery.go
  pkg/ring/client/ring_service_discovery_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ruler/ruler.go
  pkg/storegateway/gateway.go
Labels: size/L

#3457 Querier worker refactor step2
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  integration/e2ecortex/services.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/frontend/frontend_test.go
  pkg/frontend/v1/frontend_test.go
  pkg/querier/worker/config.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/frontend_processor_test.go
  pkg/querier/worker/processor_manager.go
  pkg/querier/worker/querier_scheduler_worker.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
  pkg/querier/worker/worker_frontend_manager.go
  pkg/querier/worker/worker_frontend_manager_test.go
  pkg/querier/worker/worker_test.go
  tools/doc-generator/main.go
Labels: size/XXL

#3464 Disable DNS resolution for testing.
  pkg/querier/worker/worker.go
  pkg/querier/worker/worker_test.go
  pkg/util/test/poll.go
Labels: size/M

#3405 Add documentation for '/debug/*' endpoints
  docs/api/_index.md
Labels: size/S

#3458 Enforced -querier.max-query-lookback in the query-frontend for range queries
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/querier/querier.go
  pkg/querier/queryrange/limits.go
  pkg/querier/queryrange/limits_test.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/queryable_test.go
  pkg/querier/queryrange/querysharding_test.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/roundtrip_test.go
  pkg/querier/queryrange/split_by_interval_test.go
  pkg/querier/queryrange/util.go
  pkg/storage/tsdb/memcache_client_config.go
  pkg/util/time.go
  pkg/util/validation/limits.go
Labels: size/XL

#3466 Use Info level for messages about adding and removing connection to scheduler and frontend.
  pkg/frontend/v2/frontend_scheduler_worker.go
  pkg/querier/worker/worker.go
Labels: size/XS

#3461 Query store for series lookups
  CHANGELOG.md
  docs/api/_index.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/limitations.md
  integration/querier_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/querier.go
Labels: size/M

#3473 Cut release 1.5.0
  CHANGELOG.md
  VERSION
  docs/production/storage-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/S

#3468 Frontend refactor
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/queue_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
  pkg/scheduler/queues.go
  pkg/scheduler/queues_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/XXL

#3474 Fixing README guide links
  README.md
Labels: size/XS

#3476 Expose WAL segment size setting
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester_v2.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
Labels: size/S

#3475 Mention that blocks storage is ready for production use in guides
  docs/guides/running-chunks-storage-in-production.md
Labels: size/XS

#3479 Merge release-1.5 back to master
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  VERSION
  docs/guides/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#3481 Add backwards compatability test for v1.5.0
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#3472 add support for slicing of chunk in encodings
  pkg/chunk/chunk.go
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_test.go
  pkg/chunk/encoding/bigchunk.go
  pkg/chunk/encoding/chunk.go
  pkg/chunk/encoding/chunk_test.go
  pkg/chunk/encoding/doubledelta.go
  pkg/chunk/encoding/varbit.go
Labels: size/L

#3471 Document query scheduler
  CHANGELOG.md
  docs/architecture.md
  docs/configuration/config-file-reference.md
  docs/operations/scalable-query-frontend.md
  pkg/querier/worker/worker.go
Labels: size/L

#3483 Improve compactor blocks cleaner when running with a large number of tenants
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/frontend/frontend_test.go
  pkg/ingester/ingester_v2.go
  pkg/util/concurrency/buffer.go
  pkg/util/concurrency/runner.go
Labels: size/L

#3477 Added option to ignore regexp-matching users by scheduler.
  CHANGELOG.md
  tools/blocksconvert/scanner/scanner.go
  tools/blocksconvert/scheduler/scheduler.go
  tools/blocksconvert/scheduler/scheduler_test.go
Labels: size/M

#3480 Support custom log.Logger instances in spanlogger
  pkg/util/spanlogger/spanlogger.go
  pkg/util/spanlogger/spanlogger_test.go
Labels: size/M

#3484 Wait for a stable ring at compactor startup
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/compactor.template
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_ring.go
  pkg/compactor/compactor_test.go
  pkg/ring/util.go
  pkg/ring/util_test.go
Labels: size/L

#3364 Add cross tenant query federation proposal
  docs/proposals/cross-tenant-query-federation.md
Labels: size/L

#3495 Update auth documentation
  docs/guides/authentication-and-authorisation.md
Labels: size/S

#3494 Don't report io.EOF as error from FrontendLoop.
  pkg/scheduler/scheduler.go
Labels: size/XS

#3485 Fix makefile for SELinux enabled machines
  Makefile
Labels: size/S

#3470 blocksconvert: read chunks concurrently when finishing block
  CHANGELOG.md
  tools/blocksconvert/builder/tsdb.go
Labels: size/M

#3498 Add index-header lazy loading support to store-gateway
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
  go.mod
  go.sum
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  tools/blocksconvert/builder/tsdb.go
  vendor/github.com/lann/builder/.travis.yml
  vendor/github.com/lann/builder/LICENSE
  vendor/github.com/lann/builder/registry.go
  vendor/github.com/thanos-io/thanos/pkg/block/block.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/block/index.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/header.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/reader_pool.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/deletionmark.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/markers.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/streamed_block_writer.go
  vendor/github.com/thanos-io/thanos/pkg/compact/planner.go
  vendor/github.com/thanos-io/thanos/pkg/compact/retention.go
  vendor/github.com/thanos-io/thanos/pkg/component/component.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/XL

#3459 [security] Add details about vendor announce list
  SECURITY.md
Labels: size/M

#3508 Query frontend with scheduler fixes
  development/tsdb-blocks-storage-s3/docker-compose.yml
  development/tsdb-blocks-storage-s3/goland/TSDB Query-frontend (using scheduler).run.xml
  development/tsdb-blocks-storage-s3/goland/TSDB Query-scheduler.run.xml
  pkg/frontend/v2/frontend_scheduler_worker.go
Labels: size/M

#3505 Safely check pointer in aws client before using them.
  pkg/chunk/aws/s3_storage_client.go
Labels: size/XS

#3501 Reuse components slice when parsing chunk time range value.
  pkg/chunk/chunk_store.go
  pkg/chunk/schema_test.go
  pkg/chunk/schema_util.go
  pkg/chunk/schema_util_test.go
Labels: size/M

#3443 Remove dummy credentials from AWS config
  pkg/chunk/aws/s3_storage_client.go
Labels: size/XS

#3504 Fix blocks operation doc broken link
  docs/getting-started/getting-started-blocks.md
Labels: size/XS

#3414 Add topology aware read
  CHANGELOG.md
  docs/guides/zone-replication.md
  integration/e2e/service.go
  integration/e2ecortex/client.go
  integration/zone_aware_test.go
  pkg/distributor/distributor_test.go
  pkg/ring/replication_set.go
  pkg/ring/replication_set_test.go
  pkg/ring/replication_set_tracker.go
  pkg/ring/replication_set_tracker_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/XXL

#3506 Fixed false counters resets for aggregated metrics
  CHANGELOG.md
  pkg/alertmanager/alertmanager_metrics.go
  pkg/ingester/metrics.go
  pkg/ruler/manager.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_fetcher_metrics.go
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/XL

#3510 Added missing requires_docker tag to zone_aware_test.go
  integration/zone_aware_test.go
Labels: size/XS

#3512 Refactor consistency check so it can be reused
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/L

#3511 Support removal of registry from UserRegistries
  pkg/ruler/manager_metrics.go
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/XL

#3517 Use formatMatcher only once.
  pkg/chunk/chunk_store.go
Labels: size/S

#3516 Improve delete index query signature.
  pkg/chunk/purger/delete_requests_store.go
Labels: size/M

#3519 Update flag names in CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#3216 Alertmanager: Remove outdated comment
  pkg/alertmanager/multitenant.go
Labels: size/M

#3524 Update weaveworks/common.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  vendor/github.com/weaveworks/common/middleware/http_tracing.go
  vendor/github.com/weaveworks/common/middleware/instrument.go
  vendor/github.com/weaveworks/common/server/server.go
  vendor/modules.txt
Labels: size/S

#3305 Allow ingesters to stay in the ring during restart
  CHANGELOG.md
  docs/api/_index.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/lifecycle_test.go
  pkg/ring/lifecycler.go
  pkg/ring/replication_strategy.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/L

#3525 Refactored do not unregister ingester on shutdown option
  docs/api/_index.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ingester/ingester.go
  pkg/ingester/lifecycle_test.go
  pkg/ring/lifecycler.go
  pkg/ring/replication_strategy.go
  pkg/ring/replication_strategy_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ring/util_test.go
Labels: size/L

#3526 Added tests on BlocksScanner quick shutdown
  pkg/querier/blocks_scanner_test.go
Labels: size/M

#3528 Added support to cache meta.json attributes
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/caching_bucket.go
Labels: size/S

#3531 Fixed meta.json sync concurrency config option
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
Labels: size/XS

#3521 Add chunk.EncodeTo to allow to pass your own buffer.
  pkg/chunk/chunk.go
Labels: size/S

#3532 Fixed TestWaitRingStabilityShouldReturnOnceMinStabilityHasBeenReached flakyness
  pkg/ring/util_test.go
Labels: size/XS

#3527 Scan tenants upfront in the querier.BlocksScanner in order to improve its cacheability
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/storage/tsdb/users_scanner.go
  pkg/storage/tsdb/users_scanner_test.go
Labels: size/M

#3534 Validate block range periods config in the compactor
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/cortex.go
Labels: size/M

#3538 Upgrade Thanos
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor.go
  pkg/querier/blocks_scanner.go
  pkg/storage/tsdb/index_cache.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/block/index.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/block/writer.go
  vendor/github.com/thanos-io/thanos/pkg/component/component.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/S

#3491 Close TSDB and delete local data when TSDB is idle for a long time.
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
  pkg/storage/tsdb/config.go
Labels: size/XL

#3520 Query Label Names and Values from blocks store
  CHANGELOG.md
  Makefile
  docs/api/_index.md
  integration/querier_test.go
  pkg/distributor/distributor.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/querier.go
  pkg/querier/store_gateway_client_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/gateway.go
  pkg/storegateway/storegatewaypb/gateway.pb.go
  pkg/storegateway/storegatewaypb/gateway.proto
Labels: size/XXL

#3540 Add option to use v2 signatures for S3 blocks store
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/backend/s3/bucket_client.go
  pkg/storage/backend/s3/config.go
  pkg/storage/tsdb/config.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/modules.txt
Labels: size/M

#3536 API: HTTP GZIP API compression
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/alertmanager_test.go
  integration/configs.go
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/api/api.go
Labels: size/L

#3486 Add tenant resolver
  Makefile
  pkg/alertmanager/api.go
  pkg/alertmanager/multitenant.go
  pkg/api/middlewares.go
  pkg/chunk/purger/request_handler.go
  pkg/chunk/storage/caching_index_client.go
  pkg/configs/api/api.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v2/frontend.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/user_state.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/chunk_store_queryable.go
  pkg/querier/chunks_handler.go
  pkg/querier/distributor_queryable.go
  pkg/querier/querier.go
  pkg/querier/queryrange/limits.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/util.go
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/tenant/resolver.go
  pkg/tenant/resolver_test.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
  pkg/util/log.go
Labels: size/XL

#3537 Exported process metrics to monitor the number of memory map areas allocated
  CHANGELOG.md
  pkg/cortex/cortex.go
  pkg/util/process/collector.go
  pkg/util/process/collector_test.go
Labels: size/L

#3523 Expose gRPC client configuration in ruler
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/ruler/ruler.go
Labels: size/M
