Repository cortexproject/cortex, pull requests merged in 2020-03, with the labels that each got.

#2195 Fixed doc
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/storage/tsdb/config.go
Labels: size/S

#2197 Add comment and check for chunkSeries implementation of SeriesWithChunks
  pkg/querier/chunk_store_queryable.go
  pkg/querier/chunk_store_queryable_test.go
Labels: size/XS

#2199 Add documentation on configuring caching.
  docs/guides/caching.md
  docs/guides/running.md
Labels: size/L

#2200 Documented how to add a new maintainer
  docs/governance/how-to-add-a-maintainer.md
  tools/website/web-pre.sh
Labels: size/M

#2201 Documented how to run the website locally
  CONTRIBUTING.md
  README.md
  docs/_index.md
  docs/contributing/how-to-run-website-locally.md
  tools/website/web-pre.sh
Labels: size/M

#2198 Add Peter as maintainer
  MAINTAINERS
Labels: size/XS

#2103 delete series api and purger to purge data requested for deletion
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config.yaml
  pkg/chunk/aws/dynamodb_storage_client_test.go
  pkg/chunk/delete_requests_store.go
  pkg/chunk/purger/delete_plan.pb.go
  pkg/chunk/purger/delete_plan.proto
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/purger/request_handler.go
  pkg/chunk/storage/chunk_client_test.go
  pkg/chunk/storage/factory.go
  pkg/chunk/testutils/testutils.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  tools/doc-generator/main.go
Labels: size/XXL

#2166 Convert Cortex components to services
  CHANGELOG.md
  cmd/cortex/main.go
  integration/backward_compatibility_test.go
  integration/e2e/service.go
  integration/e2ecortex/services.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/table_manager.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_http.go
  pkg/compactor/compactor_test.go
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/module_service_wrapper.go
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/cortex/server_service_test.go
  pkg/cortex/status.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
  pkg/ingester/client/pool.go
  pkg/ingester/client/pool_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/wal_test.go
  pkg/querier/block.go
  pkg/querier/block_store.go
  pkg/querier/block_store_test.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/replication_strategy_test.go
  pkg/ring/ring.go
  pkg/ruler/api_test.go
  pkg/ruler/lifecycle_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/runtimeconfig/manager.go
  pkg/util/runtimeconfig/manager_test.go
  pkg/util/services/basic_service.go
  pkg/util/services/manager.go
  pkg/util/services/services.go
  pkg/util/services/services_test.go
Labels: size/XXL

#2181 Configs API: Allow POST configs in YAML format.
  CHANGELOG.md
  pkg/configs/api/api.go
  pkg/configs/api/api_test.go
  pkg/configs/api/helpers_test.go
  pkg/configs/api/testdata/config.json
  pkg/configs/api/testdata/config.yml
  pkg/configs/configs.go
  pkg/configs/configs_test.go
Labels: size/L

#2196 Support `lastEvaluation` and `evaluationTime` in `/api/v1/rules` endpoints and make order of groups stable.
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/rules/rules.pb.go
  pkg/ruler/rules/rules.proto
Labels: size/XL

#2187 Change config flags, add flags to disable Alertmanager notifications methods: email & webhoook
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alerts/configdb/store.go
  pkg/configs/api/api.go
  pkg/configs/api/api_test.go
  pkg/configs/api/helpers_test.go
  pkg/configs/client/client.go
  pkg/configs/client/configs_test.go
  pkg/configs/config.go
  pkg/configs/db/db.go
  pkg/configs/db/memory/memory.go
  pkg/configs/db/postgres/postgres.go
  pkg/configs/db/timed.go
  pkg/configs/db/traced.go
  pkg/configs/userconfig/config.go
  pkg/configs/userconfig/config_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ruler/rules/store.go
  pkg/ruler/rules/store_test.go
  tools/doc-generator/main.go
Labels: size/XL

#2203 Introduce query-tee tool
  .gitignore
  CHANGELOG.md
  cmd/query-tee/Dockerfile
  cmd/query-tee/instrumentation.go
  cmd/query-tee/main.go
  cmd/query-tee/proxy.go
  cmd/query-tee/proxy_backend.go
  cmd/query-tee/proxy_backend_test.go
  cmd/query-tee/proxy_endpoint.go
  cmd/query-tee/proxy_endpoint_test.go
  cmd/query-tee/proxy_metrics.go
  cmd/query-tee/proxy_test.go
  docs/operations/query-tee.md
Labels: size/XL

#2211 Updated 'How to add a maintainer' doc
  docs/governance/how-to-add-a-maintainer.md
Labels: size/XS

#2212 Added / support to query-tee for health checking
  cmd/query-tee/proxy.go
Labels: size/XS

#2213 add metrics for number of failures in creation and deletion of tables
  pkg/chunk/aws/dynamodb_table_client_test.go
  pkg/chunk/aws/metrics_autoscaling_test.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/table_manager.go
  pkg/chunk/table_manager_test.go
  pkg/chunk/testutils/testutils.go
  pkg/cortex/modules.go
Labels: size/L

#2216 fix broken tests in wal
  pkg/ingester/wal_test.go
Labels: size/XS

#2215 Fixed HTTP status code on failed query because missing block
  integration/e2ecortex/storage.go
  integration/querier_test.go
  pkg/querier/block.go
  pkg/storage/tsdb/backend/s3/bucket_client.go
Labels: size/L

#2224 Upgrade Golang version used in integration tests
  .circleci/config.yml
  docs/contributing/how-to-upgrade-golang-version.md
  go.mod
Labels: size/XS

#2219 Move call of stopIncomingRequests before lifecycler shutdown.
  pkg/ingester/ingester.go
  pkg/ring/flush.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ruler/lifecycle.go
Labels: size/M

#2227 exclude generated protos from PR size bot
  .gitattributes
Labels: size/XS

#2228 Exit with status code 1 if Cortex fails to start or any service fails
  cmd/cortex/main.go
  pkg/cortex/cortex.go
Labels: size/S

#2222 Move WAL replays (chunks / tsdb) into ingester's Starting state.
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
Labels: size/M

#2192 RCF: Add index page to Cortex, linking to various interesting endpoints.
  pkg/cortex/index.go
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/cortex/server_service_test.go
Labels: size/M

#2230 Fix build-image version used in CI
  .circleci/config.yml
Labels: size/XS

#2231 services: add failure case to Stopping function
  pkg/alertmanager/multitenant.go
  pkg/chunk/purger/purger.go
  pkg/chunk/table_manager.go
  pkg/compactor/compactor.go
  pkg/cortex/module_service_wrapper.go
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/distributor/distributor.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/querier/block.go
  pkg/querier/block_store.go
  pkg/ring/lifecycler.go
  pkg/ruler/ruler.go
  pkg/util/runtimeconfig/manager.go
  pkg/util/services/basic_service.go
  pkg/util/services/basic_service_test.go
  pkg/util/services/services_test.go
Labels: size/M

#2229 Exclude vendor/ from PR size
  .gitattributes
Labels: size/XS

#2232 Extract RetryMiddlewareMetrics from NewRetryMiddleware.
  pkg/querier/queryrange/retry.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/M

#2233 Move memberlist KV init state into memberlist package, and make it public.
  pkg/cortex/cortex.go
  pkg/cortex/memberlist_kv.go
  pkg/cortex/modules.go
  pkg/ring/kv/memberlist/kv_state.go
Labels: size/L

#2207 Update the default configs for spread flush and bigchunks
  CHANGELOG.md
  docs/configuration/single-process-config.yaml
  pkg/chunk/cache/cache_test.go
  pkg/chunk/encoding/factory.go
Labels: size/XS

#2234 Fixed typo in -experimental.tsdb.retention-period doc
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/storage/tsdb/config.go
Labels: size/XS

#2221 Remove support schema flags, only use config file.
  CHANGELOG.md
  docs/configuration/schema-config-reference.md
  docs/guides/aws-specific.md
  docs/guides/running.md
  integration/backward_compatibility_test.go
  integration/configs.go
  integration/e2e/util.go
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/ruler-dep.yaml
  k8s/schema-config.yaml
  k8s/table-manager-dep.yaml
  pkg/chunk/schema_config.go
  pkg/cortex/modules.go
Labels: size/L

#2236 Release Cortex 0.7.0-rc.0
  CHANGELOG.md
  RELEASE.md
  VERSION
  docs/guides/cortex-with-cassandra.md
Labels: size/L

#2238 Fixed cortex_distributor_ingester_query_failures_total metric if an error occurr in the stream.Recv()
  pkg/distributor/query.go
Labels: size/XS

#2240 Do not track cortex_distributor_ingester_query_failures_total if context was canceled
  pkg/distributor/query.go
Labels: size/S

#2239 Convert module name to a string. It simplifies the code a bit.
  pkg/cortex/modules.go
  pkg/cortex/status.go
Labels: size/L

#2226 Refactor Rules Protos
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/rules.pb.go
  pkg/ruler/rules/rules.proto
Labels: size/XXL

#2243 Upgraded weaveworks/common
  cmd/cortex/main.go
  cmd/test-exporter/main.go
  go.mod
  go.sum
  vendor/github.com/weaveworks/common/instrument/instrument.go
  vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go
  vendor/github.com/weaveworks/common/middleware/grpc_logging.go
  vendor/github.com/weaveworks/common/server/fake_server.pb.go
  vendor/github.com/weaveworks/common/server/fake_server.proto
  vendor/github.com/weaveworks/common/tracing/tracing.go
  vendor/modules.txt
Labels: size/S

#2242 Ingester gRPC servers should return context error if any
  pkg/distributor/query.go
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/cortex_util.go
  pkg/ingester/client/cortex_util_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/transfer.go
  pkg/ingester/transfer_test.go
  pkg/util/grpc/util.go
  vendor/github.com/weaveworks/common/grpc/cancel.go
  vendor/google.golang.org/grpc/test/bufconn/bufconn.go
  vendor/modules.txt
Labels: size/L

#2246 Converted frontend worker to a service.
  CHANGELOG.md
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/frontend/frontend_test.go
  pkg/querier/frontend/worker.go
Labels: size/M

#2248 Make NewServerService generic again
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/cortex/server_service_test.go
Labels: size/M

#2245 Experimental TSDB: Add support for local filesystem backend
  CHANGELOG.md
  docs/architecture.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  pkg/storage/tsdb/backend/filesystem/bucket_client.go
  pkg/storage/tsdb/backend/filesystem/config.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/config.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go
  vendor/modules.txt
Labels: size/M

#2251 Lifecycler errors don't make process exit immediately, but let other modules shutdown properly
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/distributor/distributor.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ring/lifecycler.go
  pkg/util/services/failure_watch_test.go
  pkg/util/services/failure_watcher.go
Labels: size/L

#2260 404 handling and DeleteObject implementations (GCS & S3)
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/gcp/gcs_object_client.go
Labels: size/M

#2257 Doc/getting started blocks storage
  docs/_index.md
  docs/configuration/single-process-config-blocks.yaml
  docs/getting-started/_index.md
  docs/getting-started/getting-started-blocks.md
  docs/getting-started/getting-started-chunks.md
  docs/guides/cortex-with-cassandra.md
  integration/configs.go
  integration/getting_started_single_process_config_test.go
Labels: size/L

#2249 add support for bigtable as index store for integration tests
  .circleci/config.yml
  integration/chunks_storage_backends_test.go
  integration/configs.go
  integration/e2e/db/db.go
Labels: size/L

#2256 e2e: Fixed WaitSumMetrics to fail on non existing metric
  .circleci/config.yml
  integration/README.md
  integration/alertmanager_test.go
  integration/api_config_test.go
  integration/backward_compatibility_test.go
  integration/chunks_storage_backends_test.go
  integration/configs.go
  integration/e2e/scenario_test.go
  integration/e2e/service.go
  integration/e2e/service_test.go
  integration/getting_started_single_process_config_test.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/integration_memberlist_single_binary_test.go
  integration/metrics_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/util.go
  pkg/alertmanager/multitenant.go
  pkg/chunk/table_manager.go
Labels: size/S

#2263 Deduplicate streamed samples from ingesters using blocks storage
  pkg/distributor/query.go
  pkg/distributor/query_test.go
  pkg/querier/duplicates_test.go
Labels: size/L

#2250 Make module service wrapper reusable from other projects
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/module_service_wrapper.go
  pkg/flusher/flusher.go
  pkg/util/errors.go
  pkg/util/module_service.go
Labels: size/L

#2252 Support 1w, 1y for retention and table period take 2
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/config-file-reference.template
  docs/configuration/schema-config-reference.md
  docs/configuration/single-process-config.md
  docs/configuration/single-process-config.yaml
  integration/configs.go
  pkg/chunk/schema_config.go
  pkg/chunk/schema_config_test.go
  pkg/chunk/table_manager.go
  pkg/cortex/cortex.go
  tools/doc-generator/parser.go
Labels: size/L

#2265 Update breaking change around mixed time units
  CHANGELOG.md
Labels: size/XS

#2264 Reference CLI flags <prefix> in generated doc
  docs/configuration/config-file-reference.md
  tools/doc-generator/main.go
  tools/doc-generator/parser.go
  tools/doc-generator/writer.go
Labels: size/L

#2272 Introduce faillint in the CI workflow
  .circleci/config.yml
  Makefile
  build-image/Dockerfile
Labels: size/S

#2270 added FIFO cache metrics for current number of entries and memory usage
  CHANGELOG.md
  pkg/chunk/cache/fifo_cache.go
  pkg/chunk/cache/fifo_cache_test.go
Labels: size/L

#2271 Add documentation how to use other TSDB backends beside S3
  docs/configuration/single-process-config-blocks.yaml
  docs/getting-started/getting-started-blocks.md
Labels: size/S

#2214 query time filtering of chunks for pending delete requests
  docs/configuration/single-process-config.yaml
  pkg/chunk/purger/delete_requests_store.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/purger/request_handler.go
  pkg/chunk/purger/tombstones.go
  pkg/chunk/purger/tombstones_test.go
  pkg/chunk/storage/factory.go
  pkg/chunk/testutils/testutils.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/chunks_handler.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/series/series_set.go
  pkg/querier/series/series_set_test.go
  pkg/util/time.go
Labels: size/XXL

#2274 Prepare release 0.7.0
  CHANGELOG.md
  VERSION
  docs/guides/cortex-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/L

#2277 Updated RELEASE instructions
  RELEASE.md
Labels: size/XS

#2268 Allow more connection reuse for DynamoDB and S3 calls
  CHANGELOG.md
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/s3_storage_client.go
Labels: size/S

#2282 Attach memcached span logs to the correct span
  pkg/chunk/cache/memcached.go
Labels: size/XS

#2285 Fix the import for test for bucket_client
  pkg/storage/tsdb/bucket_client_test.go
Labels: size/XS

#2275 support for cassandra in integration tests
  .circleci/config.yml
  integration/backward_compatibility_test.go
  integration/chunks_storage_backends_test.go
  integration/e2e/db/db.go
  integration/e2e/service.go
  integration/e2ecortex/service.go
  integration/e2ecortex/services.go
Labels: size/L

#2209 Removes all the occurences of omitempty
  CHANGELOG.md
  pkg/chunk/cache/background.go
  pkg/chunk/cache/cache.go
  pkg/chunk/cache/fifo_cache.go
  pkg/chunk/cache/memcached.go
  pkg/chunk/cache/memcached_client.go
  pkg/chunk/cache/redis_cache.go
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/chunk_store.go
  pkg/chunk/schema_config.go
  pkg/chunk/storage/factory.go
  pkg/compactor/compactor_ring.go
  pkg/cortex/cortex.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_ring.go
  pkg/distributor/ha_tracker.go
  pkg/flusher/flusher.go
  pkg/ingester/client/pool.go
  pkg/ingester/ingester.go
  pkg/ingester/wal.go
  pkg/ring/kv/client.go
  pkg/ring/lifecycler.go
  pkg/ring/ring.go
  pkg/ruler/api.go
  pkg/ruler/legacy_rulefmt/rulefmt.go
  pkg/ruler/ruler_ring.go
Labels: size/L

#2293 Introduced a basic logger to the integration tests framework
  .circleci/config.yml
  integration/e2e/logger.go
  integration/e2e/scenario.go
  integration/e2e/service.go
Labels: size/M

#2290 Added memcached support to the blocks storage index cache
  .circleci/config.yml
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  docs/operations/dns-service-discovery.md
  docs/operations/query-auditor.md
  docs/operations/query-tee.md
  integration/e2e/cache/cache.go
  integration/e2e/service.go
  integration/querier_test.go
  pkg/cortex/cortex_test.go
  pkg/querier/block_store.go
  pkg/querier/block_store_metrics.go
  pkg/querier/bucket_store_metrics_test.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/bucket_client_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/index_cache_metrics.go
  pkg/storage/tsdb/index_cache_metrics_test.go
  pkg/storage/tsdb/index_cache_test.go
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
  pkg/util/strings.go
Labels: size/XXL

#2295 Set the Registerer for the WAL
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/wal.go
Labels: size/XS

#2296 Updated latest stable version tag to 0.7.0
  k8s/configs-db-dep.yaml
  k8s/configs-dep.yaml
Labels: size/XS

#2281 Allow usage of host lookups for memcache discovery
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  docs/operations/dns-service-discovery.md
  docs/operations/query-auditor.md
  docs/operations/query-tee.md
  integration/query_frontend_test.go
  pkg/chunk/cache/cache.go
  pkg/chunk/cache/memcached_client.go
Labels: size/M

#2301 Fix link to doc
  docs/configuration/arguments.md
Labels: size/XS

#2300 Added integration test for Cortex 0.7.0 backward compatibility
  .circleci/config.yml
  RELEASE.md
  integration/backward_compatibility_test.go
Labels: size/S

#2306 Add Prometheus to local dev env setup
  development/tsdb-blocks-storage-s3-single-binary/.dockerignore
  development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml
  development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml
  development/tsdb-blocks-storage-s3/.dockerignore
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
Labels: size/M

#2303 Make each DNS provider register a diff metric
  integration/querier_test.go
  integration/query_frontend_test.go
  pkg/chunk/cache/cache.go
  pkg/chunk/cache/memcached_client.go
Labels: size/L

#2298 Add ability for test-exporter to only query a specified duration in the past
  pkg/testexporter/correctness/runner.go
  pkg/testexporter/correctness/runner_test.go
Labels: size/M

#2305 Documented design patterns and code conventions
  CONTRIBUTING.md
  docs/contributing/_index.md
  docs/contributing/design-patterns-and-conventions.md
  docs/contributing/how-to-run-website-locally.md
  docs/contributing/how-to-upgrade-golang-version.md
  tools/website/web-pre.sh
Labels: size/L

#2269 Ruler API and ObjectStore Backend
  CHANGELOG.md
  Makefile
  docs/configuration/config-file-reference.md
  integration/alertmanager_test.go
  integration/api_ruler_test.go
  integration/backward_compatibility_test.go
  integration/chunks_storage_backends_test.go
  integration/configs.go
  integration/e2ecortex/client.go
  integration/e2ecortex/services.go
  integration/getting_started_single_process_config_test.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/metrics_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  pkg/chunk/aws/fixtures.go
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/gcp/fixtures.go
  pkg/chunk/gcp/gcs_object_client.go
  pkg/chunk/storage/factory.go
  pkg/cortex/modules.go
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/store.go
  pkg/ruler/storage.go
  pkg/ruler/store_mock_test.go
Labels: size/XL

#2308 Improve metrics integration tests
  Makefile
  integration/alertmanager_test.go
  integration/api_ruler_test.go
  integration/asserts.go
  integration/chunks_storage_backends_test.go
  integration/e2ecortex/services.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/metrics_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
Labels: size/L

#2310 Switched pkg/alertmanager metrics to promauto
  integration/asserts.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#2309 Fix multiple registrations with multi schema
  pkg/chunk/cache/cache_test.go
  pkg/chunk/cache/memcached_client.go
  pkg/chunk/cache/mock.go
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/chunk_store_utils.go
  pkg/chunk/composite_store.go
  pkg/chunk/series_store.go
  pkg/chunk/storage/factory.go
  pkg/chunk/testutils/testutils.go
Labels: size/S

#2312 Removed metricsRegisterer from querier config
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/S

#2299 Switch pkg/ingester to promauto.With(reg)
  integration/asserts.go
  integration/configs.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  pkg/ingester/flush.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
  pkg/ingester/series.go
  pkg/ingester/transfer.go
  pkg/ingester/transfer_test.go
  pkg/ingester/user_state.go
  pkg/ingester/wal.go
Labels: size/L

#2323 Documented how to run integration tests
  docs/contributing/_index.md
  docs/contributing/how-integration-tests-work.md
  integration/README.md
Labels: size/M

#2311 Proposal: Implement Prometheus Metadata API
  docs/proposals/receiving_metadata.md
Labels: size/M

#2241 Prefix chunks cache flags.
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/guides/caching.md
  docs/guides/running.md
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/ruler-dep.yaml
  pkg/chunk/cache/background.go
  pkg/chunk/cache/memcached_client.go
  pkg/chunk/chunk_store.go
Labels: size/L

#2314 Gettings started with gossip ring.
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/getting-started/getting-started-blocks.md
  docs/getting-started/getting-started-with-gossip-ring.md
  integration/e2e/service.go
  integration/getting_started_with_gossiped_ring_test.go
Labels: size/L

#2324 Removed gRPC server to communicate between querier and BucketStore
  pkg/querier/block.go
  pkg/querier/block_store.go
  pkg/querier/blocks_bucket_store_inmemory_server.go
Labels: size/L

#2326 Store gateway service scaffolding
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ring/ring.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_http.go
  pkg/storegateway/gateway_ring.go
  pkg/storegateway/gateway_ring_test.go
Labels: size/L

#2329 Fix TestBackwardCompatibilityWithChunksStorage: Start first ingester with old image.
  integration/backward_compatibility_test.go
Labels: size/XS

#2330 /ready now returns 200, not 204
  CHANGELOG.md
  integration/backward_compatibility_test.go
  integration/e2e/db/db.go
  integration/e2e/service.go
  integration/e2ecortex/services.go
  pkg/cortex/cortex.go
Labels: size/M

#2321 Spread checkpoint writing
  pkg/ingester/wal.go
  pkg/ingester/wal_test.go
Labels: size/S

#2333 astmapper shard metrics only instantiated once
  pkg/querier/astmapper/shard_summer.go
  pkg/querier/queryrange/querysharding.go
Labels: size/M

#2332 enforce sharding defaults in period configs
  pkg/chunk/fixtures.go
  pkg/chunk/schema_config.go
  pkg/chunk/schema_config_test.go
Labels: size/L

#2334 Make `moduleName` -> `ModuleName`
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/module_service_wrapper.go
  pkg/cortex/modules.go
Labels: size/L

#2273 Saner and consistent YAML fields in config
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config.yaml
  integration/configs.go
  pkg/alertmanager/multitenant.go
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/metrics_autoscaling.go
  pkg/chunk/gcp/bigtable_index_client.go
  pkg/chunk/storage/factory.go
  pkg/configs/client/client.go
  pkg/ingester/ingester.go
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/worker.go
  pkg/querier/querier.go
  pkg/ring/kv/consul/client.go
  pkg/ruler/ruler.go
  pkg/util/backoff.go
Labels: size/L

#2343 Add missing CHANGELOG entries
  CHANGELOG.md
Labels: size/XS

#2339 Remove deprecated flags from months ago
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/configuration/single-process-config.md
  docs/configuration/single-process-config.yaml
  docs/guides/cortex-with-cassandra.md
  k8s/ingester-dep.yaml
  pkg/chunk/aws/metrics_autoscaling.go
  pkg/chunk/chunk_store.go
  pkg/distributor/distributor.go
  pkg/ring/lifecycler.go
Labels: size/S

#2317 Enabling availability zone awareness in metric R/W with ingesters.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/guides/running.md
  docs/guides/zone-replication.md
  pkg/ring/http.go
  pkg/ring/lifecycler.go
  pkg/ring/model.go
  pkg/ring/ring.go
  pkg/ring/ring.pb.go
  pkg/ring/ring.proto
  pkg/ring/ring_test.go
Labels: size/L

#2346 Increment discarded samples for invalid metric names
  CHANGELOG.md
  pkg/util/validation/validate.go
Labels: size/XS

#2341 Add metric for deprecated flags set.
  pkg/chunk/schema_config.go
  pkg/util/flagext/deprecated.go
Labels: size/S

#2354 Fix: Changelog entry for #2346
  CHANGELOG.md
Labels: size/XS

#2307 Renamed table-manager metrics to remove cortex_dynamo prefix
  CHANGELOG.md
  pkg/chunk/table_manager.go
Labels: size/S

#2342 TSDB soft errors: check original error
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/S

#2328 Remove AWS based autoscaler code
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/aws/aws_autoscaling.go
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/dynamodb_table_client.go
  pkg/chunk/aws/dynamodb_table_client_test.go
  pkg/chunk/aws/metrics_autoscaling_test.go
  pkg/cortex/modules.go
  vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/api.go
  vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/applicationautoscalingiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/doc.go
  vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/errors.go
  vendor/github.com/aws/aws-sdk-go/service/applicationautoscaling/service.go
  vendor/modules.txt
Labels: size/XL

#2358 doc update for zone awareness
  docs/guides/zone-replication.md
Labels: size/S

#2315 Proposal: blocks storage sharding
  docs/proposals/_index.md
  docs/proposals/blocks-storage-sharding.md
Labels: size/M

#2357 Fix pushes when ingesters don't have a zone.
  integration/backward_compatibility_test.go
  pkg/ring/ring.go
Labels: size/XS

#2344 Saner defaults for configs
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/guides/running.md
  integration/ingester_hand_over_test.go
  pkg/chunk/cache/memcached.go
  pkg/chunk/cache/memcached_client.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/pool.go
  pkg/ingester/ingester.go
  pkg/querier/querier.go
  pkg/ring/kv/consul/client.go
Labels: size/S

#2360 Document the v1.x guarantees
  docs/configuration/schema-config-reference.md
  docs/configuration/single-process-config.md
  docs/configuration/v1-guarantees.md
Labels: size/M

#2359 Rename rest of the dynamodb flags
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  integration/configs.go
  pkg/chunk/table_manager.go
Labels: size/L

#2361 Print a warning when using an experimental feature
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/cache/fifo_cache.go
  pkg/chunk/cache/memcached_client.go
  pkg/chunk/cache/redis_cache.go
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/purger/purger.go
  pkg/cortex/modules.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/wal.go
  pkg/querier/block.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/lifecycler.go
  pkg/util/experimental.go
Labels: size/M

#2218 Reorganise the production docs
  README.md
  docs/_index.md
  docs/architecture.md
  docs/getting-started/_index.md
  docs/guides/capacity-planning.md
  docs/guides/ingester-handover.md
  docs/guides/kubernetes.md
  docs/guides/running.md
  docs/guides/tracing.md
  docs/production/_index.md
  docs/production/auth.md
  docs/production/caching.md
  docs/production/ha-pair-handling.md
  docs/production/ingesters-with-wal.md
  docs/production/running.md
  docs/production/storage-aws.md
  docs/production/storage-cassandra.md
Labels: size/L

#2338 Update metrics if transfer fails
  CHANGELOG.md
  pkg/ingester/ingester_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/transfer.go
  pkg/ingester/user_state.go
  pkg/ingester/user_state_test.go
  pkg/ingester/wal_test.go
Labels: size/L

#2365 Add final config file changes
  CHANGELOG.md
Labels: size/L

#2369 Reduce the headings in v1-guarantees from H1 to H2
  docs/configuration/v1-guarantees.md
Labels: size/XS

#2370 TSDB: Metrics for discarded samples (soft errors)
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/series.go
Labels: size/M
