Repository cortexproject/cortex, pull requests merged in 2020-12, with the labels that each got.

#3546 typo
  docs/getting-started/getting-started-blocks.md
Labels: size/XS

#3535 Added metrics to track on-going compaction
  CHANGELOG.md
  pkg/compactor/compactor.go
Labels: size/M

#3547 blocksconvert: Normalize labels from chunks.
  CHANGELOG.md
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/builder/builder_test.go
Labels: size/L

#3553 Define bucket index struct
  go.mod
  go.sum
  pkg/querier/block_meta.go
  pkg/querier/blocks_consistency_checker.go
  pkg/querier/blocks_consistency_checker_test.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/bucketindex/index_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/modules.txt
Labels: size/XXL

#3552 Close old TSDB faster.
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
Labels: size/S

#3551 Module needs to wait for services from all of its dependencies.
  CHANGELOG.md
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/M

#3555 Moved bucket client pkg
  Makefile
  integration/e2ecortex/storage.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/cortex_test.go
  pkg/ingester/ingester_v2.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/bucket/azure/bucket_client.go
  pkg/storage/bucket/azure/config.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/client_test.go
  pkg/storage/bucket/filesystem/bucket_client.go
  pkg/storage/bucket/filesystem/config.go
  pkg/storage/bucket/gcs/bucket_client.go
  pkg/storage/bucket/gcs/config.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/swift/bucket_client.go
  pkg/storage/bucket/swift/config.go
  pkg/storage/bucket/user_bucket_client.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
  pkg/storage/tsdb/users_scanner_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/shared_config.go
Labels: size/L

#3549 Tenant deletion when using blocks storage
  CHANGELOG.md
  docs/api/_index.md
  docs/configuration/v1-guarantees.md
  pkg/api/api.go
  pkg/chunk/purger/blocks_purger_api.go
  pkg/chunk/purger/blocks_purger_api_test.go
  pkg/chunk/purger/purger.go
  pkg/cortex/modules.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storage/tsdb/tenant_deletion_mark_test.go
Labels: size/XL

#3560 Add signature v2 support for S3 chunks client
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/storage.go
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/storage/factory.go
  pkg/cortex/cortex.go
  pkg/ruler/storage.go
  vendor/modules.txt
Labels: size/L

#3566 We are an incubating project now 🤭
  website/content/en/_index.html
Labels: size/XS

#3558 Tenant deletion: compactor changes
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/users_scanner.go
  pkg/storage/tsdb/users_scanner_test.go
Labels: size/L

#3559 Ignore series API lookups to chunks store
  pkg/querier/chunk_store_queryable.go
Labels: size/XS

#3554 Proposal: introduce bucket index for the blocks storage
  docs/proposals/blocks-storage-bucket-index.md
Labels: size/L

#3539 Add basic query stats collection & logging.
  CHANGELOG.md
  Makefile
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/query_frontend_test.go
  pkg/api/handlers.go
  pkg/cortex/modules.go
  pkg/frontend/frontend_test.go
  pkg/frontend/transport/handler.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/frontendv1pb/frontend.pb.go
  pkg/frontend/v1/frontendv1pb/frontend.proto
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_scheduler_worker.go
  pkg/frontend/v2/frontend_test.go
  pkg/frontend/v2/frontendv2pb/frontend.pb.go
  pkg/frontend/v2/frontendv2pb/frontend.proto
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/querier_benchmark_test.go
  pkg/querier/querier_test.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/time_middleware.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
Labels: size/L

#3561 Write block deletion marks in the global location too
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/querier/blocks_scanner_test.go
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/bucketindex/markers.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_test.go
  pkg/storage/tsdb/bucketindex/reader.go
  pkg/storage/tsdb/bucketindex/reader_test.go
  pkg/storage/tsdb/bucketindex/writer.go
  pkg/storage/tsdb/bucketindex/writer_test.go
  pkg/storage/tsdb/testutil/block_mock.go
Labels: size/XXL

#3576 Removed CircleCI support
  .circleci/config.yml
  Makefile
  README.md
  RELEASE.md
  docs/_index.md
  docs/contributing/how-to-update-the-build-image.md
  docs/contributing/how-to-upgrade-golang-version.md
  integration/e2e/images/images.go
  tools/test
Labels: size/L

#3577 chore: cut CHANGELOG for 1.6.0-rc0
  CHANGELOG.md
Labels: size/XS

#3580 chore: update version file and verify changelog
  CHANGELOG.md
  VERSION
Labels: size/XS

#3544 [Querier] Deprecate `-querier.compress-http-responses-deprecated`
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/frontend/config.go
Labels: size/S

#3575 Memberlist status page
  CHANGELOG.md
  pkg/api/api.go
  pkg/cortex/modules.go
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/kv_init_service_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/L

#3578 Add docker-compose setup using gossip.
  development/tsdb-blocks-storage-s3-gossip/.data-ingester-1/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.data-ingester-2/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.data-minio/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.data-minio/cortex-alertmanager/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.data-minio/cortex-ruler/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.data-minio/cortex-tsdb/.gitignore
  development/tsdb-blocks-storage-s3-gossip/.dockerignore
  development/tsdb-blocks-storage-s3-gossip/.gitignore
  development/tsdb-blocks-storage-s3-gossip/compose-down.sh
  development/tsdb-blocks-storage-s3-gossip/compose-up.sh
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3-gossip/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3-gossip/config/prometheus.yaml
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-gossip/docker-compose.yml
Labels: size/XL

#3581 Memberlist: keep a buffer with sent and received messages for troubleshooting
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/kv_init_service_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/util/http.go
  pkg/util/http_test.go
Labels: size/L

#3590 Clarify that ingester WAL config applies only to chunks storage
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
Labels: size/S

#3589 Fix cortex query seconds total
  CHANGELOG.md
  pkg/frontend/transport/handler.go
Labels: size/XS

#3592 Fix Cortex logo in the website
  Makefile
  website/layouts/partials/navbar.html
Labels: size/XS

#3582 [Ruler] Add `cortex_prometheus_last_evaluation_samples` metric
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/ruler_ring.go
Labels: size/M

#3591 Do not log error if tokens file does not exist
  pkg/ring/basic_lifecycler_delegates.go
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ring/lifecycler.go
Labels: size/S

#3583 Compactor: keep bucket index updated
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/blocks-storage/_index.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/compactor.template
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/bucketindex/index_test.go
  pkg/storage/tsdb/bucketindex/markers.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_test.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storage/tsdb/testutil/block_mock.go
  pkg/util/strings.go
Labels: size/XXL

#3594 Finish docker-compose gossip setup
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3-gossip/docker-compose.yml
Labels: size/M

#3599 HA pair guide typo
  docs/guides/ha-pair-handling.md
Labels: size/XS

#3595 Propagate whether query stats is enabled from query-frontend down the request path
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/frontend/transport/handler.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontendv1pb/frontend.pb.go
  pkg/frontend/v1/frontendv1pb/frontend.proto
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_scheduler_worker.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/time_middleware.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/schedulerpb/scheduler.pb.go
  pkg/scheduler/schedulerpb/scheduler.proto
Labels: size/L

#3598 Fix max query lookback type
  CHANGELOG.md
  pkg/querier/querier_test.go
  pkg/util/validation/limits.go
Labels: size/M

#3608 Add AWS to adopters list
  ADOPTERS.md
Labels: size/XS

#3603 Memberlist: fix "forget"
  CHANGELOG.md
  pkg/ring/merge_test.go
  pkg/ring/model.go
Labels: size/S

#3600 Proposal for deletion of tenant data when using blocks storage.
  docs/proposals/tenant-deletion.md
Labels: size/L

#3602 Memberlist: more debugging options
  CHANGELOG.md
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/kv_init_service_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/M

#3619 Cut release 1.6.0-rc.1
  CHANGELOG.md
  VERSION
  pkg/frontend/transport/handler.go
Labels: size/XS

#3618 Exit Consul watch on context canceled
  pkg/ring/kv/consul/client.go
Labels: size/XS

#3614 Add bucket index support to querier
  CHANGELOG.md
  docs/blocks-storage/_index.md
  docs/blocks-storage/bucket-index.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/compactor.template
  docs/blocks-storage/querier.md
  docs/blocks-storage/querier.template
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/proposals/blocks-storage-bucket-index.md
  integration/e2e/metrics.go
  integration/e2ecortex/services.go
  integration/querier_test.go
  pkg/querier/blocks_finder_bucket_index.go
  pkg/querier/blocks_finder_bucket_index_test.go
  pkg/querier/blocks_finder_bucket_scan.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/bucketindex/index_test.go
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/caching_bucket_test.go
  pkg/storage/tsdb/config.go
  website/static/images/blocks-storage/bucket-index-querier-logic.png
Labels: size/XXL

#3623 Check if kv pointer is nil before casting it
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/kv_init_service_test.go
Labels: size/S

#3626 Synchronous call to rulerNotifier.run()
  pkg/ruler/manager.go
  pkg/ruler/notifier.go
Labels: size/XS

#3628 Improve wording of --query-store-after description
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/querier/querier.go
Labels: size/S

#3250 Add multi tenant query federation
  CHANGELOG.md
  Makefile
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/limitations.md
  integration/querier_tenant_federation_test.go
  pkg/api/middlewares.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/frontend/transport/handler.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v2/frontend.go
  pkg/querier/querier.go
  pkg/querier/queryrange/limits.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/util.go
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
  pkg/querier/tenantfederation/tenant_federation.go
  pkg/scheduler/scheduler.go
  pkg/tenant/tenant.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/XXL

#3636 Cut 1.6.0 release
  CHANGELOG.md
  VERSION
  docs/guides/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/S

#3637 chore: add 1.6.0 to backwards compatibility tests
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS
