Repository cortexproject/cortex, pull requests merged in 2020-08, with the labels that each got.

#2958 Fixed local dev environment after blocks storage config changes
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
Labels: size/M

#2965 Added Google Analytics tracking to website
  docs/governance/how-to-add-a-maintainer.md
  website/config.toml
Labels: size/XS

#2962 Always return a result and result type in QueryRange
  CHANGELOG.md
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
Labels: size/S

#2916 docs for performing deletion in cortex chunks storage
  docs/apis.md
  docs/guides/deleting-series.md
Labels: size/L

#2971 make a copy of KVs coming from boltdb which are only valid until the transaction is valid
  CHANGELOG.md
  pkg/chunk/local/boltdb_index_client.go
Labels: size/S

#2968 Update Thanos to latest master
  go.mod
  go.sum
  pkg/ingester/ingester_v2.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/store/limiter.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/modules.txt
Labels: size/XS

#2974 Always query series and labels from TSDB head
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
Labels: size/M

#2955 Avoid indefinite checkpointing
  CHANGELOG.md
  pkg/ingester/wal.go
Labels: size/S

#2960 AM Metric: Add tenant label to valid/invalid configs
  CHANGELOG.md
  integration/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#2522 Basic functional options support to metrics assertion in integration tests
  integration/alertmanager_test.go
  integration/api_ruler_test.go
  integration/e2e/composite_service.go
  integration/e2e/metrics.go
  integration/e2e/metrics_options.go
  integration/e2e/service.go
  integration/getting_started_with_gossiped_ring_test.go
  integration/ingester_hand_over_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
Labels: size/L

#2838 Add RPM and deb packaging for cortex binary
  Makefile
  RELEASE.md
  packaging/deb/control/postinst
  packaging/deb/control/prerm
  packaging/deb/debian-systemd/Dockerfile
  packaging/deb/default/cortex
  packaging/deb/systemd/cortex.service
  packaging/fpm/Dockerfile
  packaging/fpm/package.sh
  packaging/rpm/centos-systemd/Dockerfile
  packaging/rpm/control/post
  packaging/rpm/control/preun
  packaging/rpm/sysconfig/cortex
  packaging/rpm/systemd/cortex.service
  tools/packaging/test-packages
Labels: size/L

#2977 Prepare CHANGELOG for Cortex 1.3.0 release
  CHANGELOG.md
  RELEASE.md
Labels: size/S

#2978 Prepare Cortex 1.3.0-rc.0
  CHANGELOG.md
  Makefile
  RELEASE.md
  VERSION
Labels: size/XS

#2979 Revert "Prepare Cortex 1.3.0-rc.0"
  CHANGELOG.md
  Makefile
  RELEASE.md
  VERSION
Labels: size/XS

#2981 Exclude packaging images from CI
  Makefile
Labels: size/XS

#2980 Prepare Cortex release 1.3.0-rc.0
  CHANGELOG.md
  Makefile
  RELEASE.md
  VERSION
Labels: size/XS

#2982 Generate sha256 for .rpm and .deb packages too
  Makefile
Labels: size/S

#2989 Fix -ruler.alertmanager-url flag
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ring/kv/etcd/etcd.go
  pkg/ring/lifecycler.go
  pkg/ruler/notifier.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
  pkg/storegateway/gateway_ring.go
  pkg/util/flagext/strings.go
  pkg/util/flagext/stringslice.go
Labels: size/L

#2997 Cherry pick PR #2989 into release-1.3
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ring/kv/etcd/etcd.go
  pkg/ring/lifecycler.go
  pkg/ruler/notifier.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
  pkg/storegateway/gateway_ring.go
  pkg/util/flagext/strings.go
  pkg/util/flagext/stringslice.go
Labels: size/L

#2998 Add chunk flush outcome "Dropped", for short series
  pkg/ingester/flush.go
Labels: size/XS

#3001 Cherry pick PR 2998 into release 1.3 branch
  CHANGELOG.md
  pkg/ingester/flush.go
Labels: size/S

#2994 Query-tee: added a small tolerance to floating point sample values comparison
  CHANGELOG.md
  cmd/query-tee/main.go
  cmd/query-tee/main_test.go
  docs/operations/query-tee.md
  tools/querytee/proxy.go
  tools/querytee/response_comparator.go
  tools/querytee/response_comparator_test.go
Labels: size/L

#3002 Cut 1.3.0-rc.1
  CHANGELOG.md
  VERSION
Labels: size/XS

#2990 Fixed query start/end timestamp rounding
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/M

#2996 Removed ingesters blocks transfer support
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/architecture.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/guides/ingester-handover.md
  docs/guides/ingesters-rolling-updates.md
  integration/ingester_hand_over_test.go
  pkg/ingester/client/cortex.pb.go
  pkg/ingester/client/cortex.proto
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/cortex_util.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/metrics.go
  pkg/ingester/transfer.go
  pkg/ingester/transfer_test.go
  pkg/storage/tsdb/config.go
Labels: size/XXL

#3005 Add a log if the initial blocks scan fail in the querier
  pkg/querier/blocks_scanner.go
Labels: size/XS, storage/blocks

#2984 Chore: update logToSpan method comment
  pkg/querier/queryrange/query_range.go
Labels: size/XS

#2988 Support azure storage of azurechina,azuregerman,azureusgov
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/storage/factory.go
  pkg/ruler/storage.go
Labels: size/M

#2956 Documented how to migrate a live cluster from chunks to blocks
  docs/blocks-storage/migrate-from-chunks-to-blocks.md
  docs/proposals/ingesters-migration.md
  tools/migrate-ingester-statefulsets.sh
Labels: component/documentation, size/L

#2946 integration test for deletion of series
  CHANGELOG.md
  integration/asserts.go
  integration/chunks_delete_series_test.go
  integration/e2ecortex/client.go
  integration/e2ecortex/services.go
  pkg/chunk/purger/request_handler.go
  pkg/testexporter/correctness/delete_series.go
Labels: size/L

#2970 Be consistent with span logging, set error=true and use otlog.Error
  .errcheck-exclude
  pkg/chunk/cache/memcached.go
  pkg/chunk/gcp/bigtable_index_client.go
  pkg/chunk/util/parallel_chunk_fetch.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/results_cache.go
  pkg/testexporter/correctness/simple.go
  pkg/util/spanlogger/spanlogger.go
Labels: size/M

#3022 Lower default blocks listing and meta.json not exist TTL to 5m
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/caching_bucket.go
Labels: size/S, storage/blocks

#3026 Expose dynamodb backoff config
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/dynamodb_table_client.go
  pkg/chunk/aws/fixtures.go
Labels: size/M

#3035 Query /series from ingesters regardless the -querier.query-ingesters-within setting
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
Labels: size/M

#3018 add support for doing a passthrough of requests to preferred backend for unregistered routes
  CHANGELOG.md
  docs/operations/query-tee.md
  tools/querytee/proxy.go
  tools/querytee/proxy_endpoint.go
  tools/querytee/proxy_test.go
Labels: size/L

#2976 Optimised /api/v1/series for blocks storage
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3037 Cherry pick PR #3035 into release-1.3
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
Labels: size/M

#3043 Close spanlogger
  pkg/chunk/cache/memcached.go
  pkg/chunk/chunk_store.go
  pkg/chunk/series_store.go
Labels: size/XS

#3027 Update getting-started-chunks.md
  docs/getting-started/getting-started-chunks.md
Labels: size/XS

#3015 Batch series in streaming ingester based on message sizes.
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3042 Cut 1.3.0-rc.2
  CHANGELOG.md
  VERSION
Labels: size/XS

#3019 Refactor Ruler, introduce MultiTenantManager interface
  pkg/cortex/modules.go
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/XL

#2912 Add options to rule group description
  pkg/ruler/rules/rules.pb.go
  pkg/ruler/rules/rules.proto
Labels: size/XS

#3007 change: increase default cassandra RF to 3 and update docs
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/chunks_delete_series_test.go
  integration/chunks_storage_backends_test.go
  pkg/chunk/cassandra/storage_client.go
Labels: size/S

#3052 Make tests build on go1.15
  pkg/chunk/cache/memcached_test.go
  pkg/chunk/schema_test.go
  pkg/util/time_test.go
Labels: size/S

#3044 Fix typo in docs/getting-started/getting-started-chunks.md
  docs/getting-started/getting-started-chunks.md
Labels: size/XS

#3046 Simpler instrumentation for non-batched memcached
  CHANGELOG.md
  pkg/chunk/cache/memcached.go
Labels: size/S

#3030 Bugfix: Enable TLS server certificate validation by default
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  docs/production/tls.md
  integration/ca/ca.go
  integration/certs/genCerts.sh
  integration/e2e/service.go
  integration/query_frontend_test.go
  integration/util.go
  pkg/util/tls/tls.go
  pkg/util/tls/tls_test.go
Labels: size/XL

#3060 Do not return error from Ring.Subring()
  pkg/distributor/distributor.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/M

#3075 Added backward compatibility integration tests for Cortex 1.2.0 and 1.3.0
  integration/backward_compatibility_test.go
Labels: size/XS

#3066 Use intervalFn to support dynamic split interval in query frontend
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/split_by_interval.go
  pkg/querier/queryrange/split_by_interval_test.go
Labels: size/S

#3047 gRPC storage plugin docs
  docs/guides/grpc-storage-plugin.md
Labels: size/M

#3017 Fixes the Alertmanager panicking when no external URL is provided
  CHANGELOG.md
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#3013 Merge timeseries and chunkseries from ingesters
  CHANGELOG.md
  docs/blocks-storage/migrate-from-chunks-to-blocks.md
  integration/querier_streaming_mixed_ingester_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
Labels: size/L

#3056 Add integration label to notification metrics
  CHANGELOG.md
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
Labels: size/L

#3065 Fixes the registration of the Alertmanager alert receiving API metrics
  CHANGELOG.md
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#3058 Fixed memberlist for store-gateway ring
  CHANGELOG.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  integration/e2e/service.go
  integration/getting_started_with_gossiped_ring_test.go
  pkg/cortex/modules.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/lifecycler.go
  pkg/ring/model.go
Labels: size/L, storage/blocks

#3081 Fixed HTTP API documentation
  docs/api/_index.md
Labels: size/M

#3067 Dont skip WAL logging for validation errors
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/wal.go
  pkg/ingester/wal_test.go
Labels: size/M

#2973 Move regex opt to after lookup
  CHANGELOG.md
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
Labels: size/L

#3051 Add a circuit-breaker to memcached dial calls
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/chunk/cache/memcached_client.go
  vendor/github.com/bradfitz/gomemcache/memcache/memcache.go
  vendor/github.com/sony/gobreaker/.travis.yml
  vendor/github.com/sony/gobreaker/LICENSE
  vendor/github.com/sony/gobreaker/README.md
  vendor/github.com/sony/gobreaker/go.mod
  vendor/github.com/sony/gobreaker/go.sum
  vendor/github.com/sony/gobreaker/gobreaker.go
  vendor/modules.txt
Labels: size/M

#3077 Doc fixes for KV stores supported by HA Tracker
  docs/architecture.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/production/ha-pair-handling.md
  pkg/distributor/ha_tracker.go
Labels: component/documentation, size/S

#3070 Add warning that schema configuration is not used in blocks storage mode
  pkg/cortex/cortex.go
Labels: size/XS

#3074 Publish ruler's ring metrics
  CHANGELOG.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  integration/getting_started_with_gossiped_ring_test.go
  pkg/ruler/ruler.go
Labels: size/S

#3087 Fixes `-config.expand-env` requires argument
  CHANGELOG.md
  cmd/cortex/main.go
Labels: size/XS

#3086 Fixed CLI flags for memcached circuit breaker
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/memcached_client.go
Labels: size/S

#2985 Add client ip address to duplicate message
  CHANGELOG.md
  docs/configuration/arguments.md
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/util/extract_forwarded.go
  pkg/util/extract_forwarded_test.go
  pkg/util/log.go
  pkg/util/push/push.go
  pkg/util/push/push_test.go
Labels: size/L

#3095 Fixed memberlist support for the compactor ring
  CHANGELOG.md
  pkg/cortex/modules.go
Labels: size/XS

#3088 Explain how gossiping works, how to tune and monitor it.
  docs/configuration/arguments.md
Labels: size/S

#3099 Do not mention deprecated config option use_gzip_compression in the doc
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/configuration/single-process-config.md
  docs/configuration/single-process-config.yaml
  docs/production/storage-cassandra.md
Labels: size/S

#3069 Store-gateway shuffle sharding
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/cortex/cortex.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/ring.go
  pkg/storage/tsdb/util.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_filters.go
  pkg/storegateway/metadata_filters_test.go
  pkg/storegateway/sharding_strategy.go
  pkg/storegateway/sharding_strategy_test.go
  pkg/util/validation/limits.go
Labels: size/XXL

#3103 feat: return stdout and stderr from all concrete service exec commands
  integration/e2e/service.go
Labels: size/S

#3021 Use custom bucket size for indexEntriesPerChunk
  CHANGELOG.md
  pkg/chunk/series_store.go
Labels: size/XS

#3107 change: rename integration test package from main to integration
  integration/alertmanager_test.go
  integration/api_config_test.go
  integration/asserts.go
  integration/backward_compatibility_test.go
  integration/chunks_delete_series_test.go
  integration/chunks_storage_backends_test.go
  integration/configs.go
  integration/getting_started_single_process_config_test.go
  integration/getting_started_with_gossiped_ring_test.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/integration_memberlist_single_binary_test.go
  integration/kv_test.go
  integration/package.go
  integration/querier_remote_read_test.go
  integration/querier_streaming_mixed_ingester_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/ruler_test.go
  integration/s3_storage_client_test.go
  integration/util.go
Labels: size/M

#3102 Issue #3091 - Add etcd dependency TLS support
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/etcd/etcd.go
Labels: size/M
