Repository cortexproject/cortex, pull requests merged in 2020-06, with the labels that each got.

#2640 Enable metadata caching by blocks scanner.
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
Labels: size/S

#2669 Fix spans under BucketStores.Series span.
  pkg/storegateway/bucket_stores.go
Labels: size/S

#2667 Add debugger to Docker compose
  development/tsdb-blocks-storage-s3/compose-up.sh
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-s3/docker-compose.yml
  development/tsdb-blocks-storage-s3/goland/compactor.run.xml
  development/tsdb-blocks-storage-s3/goland/distributor.run.xml
  development/tsdb-blocks-storage-s3/goland/ingester-1.run.xml
  development/tsdb-blocks-storage-s3/goland/ingester-2.run.xml
  development/tsdb-blocks-storage-s3/goland/querier.run.xml
  development/tsdb-blocks-storage-s3/goland/query-frontend.run.xml
  development/tsdb-blocks-storage-s3/goland/store-gateway-1.run.xml
  development/tsdb-blocks-storage-s3/goland/store-gateway-2.run.xml
Labels: size/M

#2627 Don't prefix Thanos index-cache metrics
  CHANGELOG.md
  integration/e2e/composite_service.go
  integration/e2e/service.go
  integration/querier_test.go
  pkg/querier/blocks_bucket_stores_service.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/storage/tsdb/index_cache_metrics.go
  pkg/storage/tsdb/index_cache_metrics_test.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_fetcher_metrics.go
  pkg/storegateway/metadata_fetcher_metrics_test.go
Labels: size/XXL

#2663 ChangeLog entry for #2646
  CHANGELOG.md
Labels: size/XS

#2546 provisioning of table for delete requests using table manager
  docs/configuration/config-file-reference.md
  pkg/chunk/aws/metrics_autoscaling_test.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/purger/delete_requests_store.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/purger/table_provisioning.go
  pkg/chunk/purger/tombstones_test.go
  pkg/chunk/schema_config.go
  pkg/chunk/table_manager.go
  pkg/chunk/table_manager_test.go
  pkg/chunk/table_provisioning.go
  pkg/chunk/testutils/testutils.go
  pkg/cortex/modules.go
  tools/doc-generator/parser.go
Labels: size/XL

#2666 Allow users to configure the number of TCP connections per host for Cassandra.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cassandra/fixtures.go
  pkg/chunk/cassandra/storage_client.go
Labels: size/M

#2678 Changes in docker-compose (multiservices) setup
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
Labels: size/L

#2673 Support Accept: application/json on common HTTP endpoints
  CHANGELOG.md
  pkg/cortex/status.go
  pkg/distributor/ha_tracker_http.go
  pkg/distributor/http_admin.go
  pkg/ring/http.go
  pkg/util/http.go
  pkg/util/http_test.go
Labels: size/L

#2677 Fix CHANGELOG.md entry with correct metric names.
  CHANGELOG.md
Labels: size/XS

#2674 Dedicated struct and methods for metric counter
  CHANGELOG.md
  pkg/ingester/ingester_test.go
  pkg/ingester/user_state.go
Labels: size/L

#2682 Refactor querier batch iterator to make it general purpose
  pkg/querier/batch/batch.go
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/batch/merge.go
  pkg/querier/batch/merge_test.go
  pkg/querier/batch/non_overlapping.go
  pkg/querier/batch/non_overlapping_test.go
Labels: size/L

#2670 disabling of chunks write dedupe
  pkg/chunk/chunk_store.go
  pkg/chunk/series_store.go
Labels: size/S

#2671 [1145] Replacing fake s3 with minio in s3-dep
  k8s/s3-dep.yaml
Labels: size/S

#2657 Move 'make doc' inside containerised build
  Makefile
Labels: size/S

#2648 Generic KV Client Instrumentation
  CHANGELOG.md
  integration/kv_test.go
  pkg/compactor/compactor.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/querier/blocks_store_queryable.go
  pkg/ring/kv/client.go
  pkg/ring/kv/metrics.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/ring.go
  pkg/ruler/ruler.go
  pkg/storegateway/gateway.go
Labels: size/L

#2685 Add the ability to customize the frontend request span log.
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/S

#2679 Use vendor deps when building.
  Makefile
Labels: size/XS

#2687 Set cassandra default reconnect interval to 1s
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cassandra/storage_client.go
Labels: size/XS

#2690 Fix ingester test when running on machine with non-UTC timezone.
  pkg/ingester/ingester_v2_test.go
Labels: size/XS

#2688 Upgraded Thanos to master
  go.mod
  go.sum
  pkg/compactor/compactor.go
  pkg/compactor/syncer_metrics.go
  pkg/compactor/syncer_metrics_test.go
  vendor/github.com/minio/minio-go/v6/.gitignore
  vendor/github.com/minio/minio-go/v6/.golangci.yml
  vendor/github.com/minio/minio-go/v6/.travis.yml
  vendor/github.com/minio/minio-go/v6/Makefile
  vendor/github.com/minio/minio-go/v6/api-bucket-tagging.go
  vendor/github.com/minio/minio-go/v6/api-datatypes.go
  vendor/github.com/minio/minio-go/v6/api-notification.go
  vendor/github.com/minio/minio-go/v6/api-object-lock.go
  vendor/github.com/minio/minio-go/v6/api-object-tagging.go
  vendor/github.com/minio/minio-go/v6/api-put-bucket.go
  vendor/github.com/minio/minio-go/v6/api-put-object-streaming.go
  vendor/github.com/minio/minio-go/v6/api-s3-datatypes.go
  vendor/github.com/minio/minio-go/v6/api-select.go
  vendor/github.com/minio/minio-go/v6/api.go
  vendor/github.com/minio/minio-go/v6/appveyor.yml
  vendor/github.com/minio/minio-go/v6/bucket-cache.go
  vendor/github.com/minio/minio-go/v6/core.go
  vendor/github.com/minio/minio-go/v6/go.mod
  vendor/github.com/minio/minio-go/v6/go.sum
  vendor/github.com/minio/minio-go/v6/pkg/credentials/file_minio_client.go
  vendor/github.com/minio/minio-go/v6/pkg/credentials/iam_aws.go
  vendor/github.com/minio/minio-go/v6/pkg/encrypt/server-side.go
  vendor/github.com/minio/minio-go/v6/pkg/set/stringset.go
  vendor/github.com/minio/minio-go/v6/pkg/tags/tags.go
  vendor/github.com/minio/minio-go/v6/post-policy.go
  vendor/github.com/minio/minio-go/v6/s3-endpoints.go
  vendor/github.com/minio/minio-go/v6/transport.go
  vendor/github.com/minio/minio-go/v6/utils.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/hintspb/hints.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/hintspb/hints.proto
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.proto
  vendor/modules.txt
Labels: size/XL

#2645 improve query speed when does not enable caching
  pkg/chunk/cache/tiered.go
  pkg/chunk/storage/caching_index_client.go
Labels: size/XS

#2668 do not invalidate chunks cache when series are deleted
  pkg/chunk/storage/factory.go
Labels: size/XS

#2692 Fix test timeout when test.Poll in TestBasicLifecycler_HeartbeatWhile…
  pkg/ring/basic_lifecycler.go
Labels: size/XS

#2691 Print usage on stdout, and only when asked with -help.
  CHANGELOG.md
  cmd/cortex/main.go
  cmd/cortex/main_test.go
Labels: size/M

#2689 Selectively query blocks from each store-gateway
  pkg/querier/blocks_consistency_checker.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
Labels: size/L

#2693 Added jitter to blocks storage period bucket scans
  CHANGELOG.md
  pkg/querier/blocks_scanner.go
  pkg/storegateway/gateway.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/M

#2676 Series limit for TSDB blocks based ingester
  CHANGELOG.md
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/user_state.go
  pkg/util/extract/extract.go
Labels: size/XL

#2684 Various Cassandra client tweaks
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/chunk/aws/dynamodb_storage_client_test.go
  pkg/chunk/aws/dynamodb_table_client.go
  pkg/chunk/aws/fixtures.go
  pkg/chunk/cassandra/fixtures.go
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/cassandra/table_client.go
  pkg/chunk/gcp/fixtures.go
  pkg/chunk/gcp/table_client.go
  pkg/chunk/grpc/table_client.go
  pkg/chunk/local/boltdb_table_client.go
  pkg/chunk/local/fixtures.go
  pkg/chunk/storage/caching_fixtures.go
  pkg/chunk/storage/factory.go
  pkg/chunk/storage/utils_test.go
  pkg/chunk/table_client.go
  pkg/chunk/table_manager.go
  pkg/chunk/table_manager_test.go
  pkg/chunk/testutils/testutils.go
  vendor/github.com/gocql/gocql/AUTHORS
  vendor/github.com/gocql/gocql/README.md
  vendor/github.com/gocql/gocql/cluster.go
  vendor/github.com/gocql/gocql/conn.go
  vendor/github.com/gocql/gocql/connectionpool.go
  vendor/github.com/gocql/gocql/control.go
  vendor/github.com/gocql/gocql/events.go
  vendor/github.com/gocql/gocql/filters.go
  vendor/github.com/gocql/gocql/go.mod
  vendor/github.com/gocql/gocql/go.sum
  vendor/github.com/gocql/gocql/helpers.go
  vendor/github.com/gocql/gocql/host_source.go
  vendor/github.com/gocql/gocql/internal/murmur/murmur_appengine.go
  vendor/github.com/gocql/gocql/internal/murmur/murmur_unsafe.go
  vendor/github.com/gocql/gocql/logger.go
  vendor/github.com/gocql/gocql/marshal.go
  vendor/github.com/gocql/gocql/metadata.go
  vendor/github.com/gocql/gocql/policies.go
  vendor/github.com/gocql/gocql/session.go
  vendor/github.com/gocql/gocql/token.go
  vendor/github.com/gocql/gocql/topology.go
  vendor/github.com/golang/protobuf/jsonpb/decode.go
  vendor/github.com/golang/protobuf/proto/deprecated.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/github.com/prometheus/client_golang/prometheus/push/push.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/modules.txt
Labels: size/XXL

#2696 add dist/ repo to gitignore
  .gitignore
Labels: size/XS

#2575 Add Cassandra table options flag
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/production/storage-cassandra.md
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/cassandra/table_client.go
  pkg/chunk/cassandra/table_client_test.go
Labels: size/L

#2611 support for comparison of response in querytee
  cmd/query-tee/main.go
  cmd/query-tee/proxy_metrics.go
  tools/querytee/instrumentation.go
  tools/querytee/proxy.go
  tools/querytee/proxy_backend.go
  tools/querytee/proxy_backend_test.go
  tools/querytee/proxy_endpoint.go
  tools/querytee/proxy_endpoint_test.go
  tools/querytee/proxy_metrics.go
  tools/querytee/proxy_test.go
  tools/querytee/response_comparator.go
  tools/querytee/response_comparator_test.go
Labels: size/XL

#2697 Fixed incorrect query results introduced in #2604
  CHANGELOG.md
  go.mod
  go.sum
  pkg/querier/block_test.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/duplicates_test.go
  vendor/github.com/prometheus/prometheus/storage/generic.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/modules.txt
Labels: size/L

#2699 Micro-optimization in blockQuerierSeriesSet.At()
  pkg/querier/block.go
Labels: size/S

#2701 check response comparison flag in query tee to compare responses
  tools/querytee/proxy.go
  tools/querytee/proxy_endpoint.go
Labels: size/XS

#2702 Do not wait for the slowest response in the query-tee
  CHANGELOG.md
  docs/operations/query-tee.md
  tools/querytee/proxy.go
  tools/querytee/proxy_endpoint.go
  tools/querytee/proxy_endpoint_test.go
  tools/querytee/proxy_metrics.go
  tools/querytee/proxy_test.go
Labels: size/L

#2706 Default value of -ingester.chunk-encoding is actually Bigchunk starting 0.7.0
  docs/configuration/arguments.md
Labels: size/XS

#2720 Small optimization for FromLabelAdaptersToLabelsWithCopy
  pkg/ingester/client/compat.go
  pkg/ingester/client/compat_test.go
Labels: size/M

#2716 allow registering routes with multiple http methods with query tee
  cmd/query-tee/main.go
  tools/querytee/proxy.go
  tools/querytee/proxy_test.go
Labels: size/S

#2712 Log number of series in API response
  pkg/querier/queryrange/query_range.go
Labels: size/XS

#2711 load delete requests frequently if there are more pending requests for a user
  pkg/chunk/purger/purger.go
Labels: size/M

#2705 Add retry with backoff on memberlist join other members
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/L

#2715 Randomize gossip node name by adding random suffix.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/M

#2700 Fix Redis cache error when a query has no chunks to lookup
  CHANGELOG.md
  pkg/chunk/chunk_store.go
  pkg/chunk/composite_store.go
  pkg/chunk/series_store.go
Labels: size/S

#2721 Added benchmark for RefCache with long labels.
  pkg/storage/tsdb/ref_cache_test.go
Labels: size/M

#2722 more detailed slow query logging
  docs/configuration/config-file-reference.md
  pkg/querier/frontend/frontend.go
Labels: size/M

#2713 Make memberlist KV a service.
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/kv_state.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/ring/kv/memberlist/metrics.go
Labels: size/L

#2724 Memberlist: added rejoin interval
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/M

#2725 Unexperimentalize memberlist
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/operations/blocks-storage.md
  pkg/ring/kv/client.go
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/M

#2708 Separate HTTP Instrumentation for Querier
  CHANGELOG.md
  integration/asserts.go
  pkg/api/api.go
  pkg/cortex/modules.go
Labels: size/M

#2480 Update golang to 1.14.4 and other build deps
  .circleci/config.yml
  Makefile
  build-image/Dockerfile
  go.mod
  go.sum
  pkg/alertmanager/multitenant.go
  tools/query-audit/main.go
  vendor/go.etcd.io/bbolt/README.md
  vendor/go.etcd.io/bbolt/freelist.go
  vendor/go.etcd.io/bbolt/node.go
  vendor/go.etcd.io/bbolt/page.go
  vendor/go.etcd.io/bbolt/tx.go
  vendor/go.etcd.io/bbolt/unsafe.go
  vendor/golang.org/x/sys/cpu/byteorder.go
  vendor/golang.org/x/sys/windows/memory_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/M

#2729 Uniform error field name in logs
  pkg/configs/db/postgres/postgres.go
  pkg/cortex/cortex.go
  pkg/distributor/ha_tracker.go
  pkg/querier/frontend/frontend.go
Labels: size/S

#2739 Fix website
  website/config.toml
  website/content/en/_index.html
Labels: size/XS

#2595 test exporter changes for testing delete series
  cmd/test-exporter/main.go
  pkg/testexporter/correctness/case.go
  pkg/testexporter/correctness/delete_series.go
  pkg/testexporter/correctness/runner.go
  pkg/testexporter/correctness/runner_test.go
  pkg/testexporter/correctness/simple.go
Labels: size/XL

#2730 more metrics in purger for monitoring delete requests processing progress
  CHANGELOG.md
  pkg/chunk/purger/delete_requests_store.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
Labels: size/L

#2745 Give example of default label keys for HA pair
  docs/production/ha-pair-handling.md
Labels: size/XS

#2750 Mention that -distributor.shard-by-all-labels is used by querier too.
  docs/configuration/arguments.md
Labels: size/XS

#2751 Cleanup partial blocks with deletion mark expired
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/L

#2728 change flag DisableChunksDeduplication to DisableIndexDeduplication for disabling just index deduplication
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/series_store.go
  pkg/chunk/storage_client.go
Labels: size/L

#2695 Refetch series for missing blocks
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/config-file-reference.md
  pkg/querier/blocks_consistency_checker.go
  pkg/querier/blocks_consistency_checker_test.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/querier/querier.go
Labels: size/XL

#2741 Propgate GOPROXY value to build-image/Dockerfile
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
Labels: size/XS

#2736 Add memcached server address to Set() error
  pkg/chunk/cache/memcached_client.go
Labels: size/S

#2753 Run integration tests with Go 1.14
  .circleci/config.yml
  CHANGELOG.md
Labels: size/XS

#2738 Clarified actual limits in the series limit error
  pkg/ingester/limiter.go
Labels: size/XS

#2754 Fixed S3 config in the k8s/ manifests
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/ruler-dep.yaml
  k8s/s3-dep.yaml
  k8s/s3-svc.yaml
  k8s/schema-config.yaml
Labels: size/S

#2760 make delete request cancellation duration configurable and rename data-purger to purger
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/api/api.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/purger/request_handler.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
Labels: size/L

#2761 Added query-tee to the list of released binaries
  Makefile
Labels: size/XS

#2749 Set go version to 1.14, to enable vendor builds by default.
  go.mod
  tools/test
  vendor/modules.txt
Labels: size/S

#2656 Remove -store.fullsize-chunks option
  CHANGELOG.md
  pkg/chunk/encoding/chunk_test.go
  pkg/chunk/encoding/factory.go
  pkg/chunk/encoding/varbit.go
Labels: size/S

#2726 Remove old temporary checkpoints
  CHANGELOG.md
  pkg/ingester/wal.go
  pkg/ingester/wal_test.go
Labels: size/M

#2767 Add missing docs for TLS config in Ingester Client
  docs/production/tls.md
Labels: size/S

#2762 fix race in processing of headers in sharded queries
  CHANGELOG.md
  pkg/querier/queryrange/queryable.go
  pkg/querier/queryrange/querysharding.go
Labels: size/S

#2717 Added proposal for ingester+querier migration from chunks to blocks and back.
  docs/proposals/ingesters-migration.md
Labels: size/M

#2764 fix: set correct number of keys in background cache metrics
  CHANGELOG.md
  pkg/chunk/cache/background.go
Labels: size/XS

#2773 Add CHANGELOG.md entry for PR 2571
  CHANGELOG.md
Labels: size/XS

#2769 Prepare Release 1.2
  CHANGELOG.md
  VERSION
  docs/production/storage-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#2435 Remove additional step, the issue is closed?
  .circleci/config.yml
Labels: size/XS

#2783 new flag: ruler.outage-tolerance
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/ruler.go
Labels: size/M

#2777 Rename purger target flag
  CHANGELOG.md
  pkg/chunk/purger/purger_test.go
  pkg/cortex/modules.go
Labels: size/M

#2747 Support querying multiple stores by Querier
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/config-file-reference.template
  docs/configuration/v1-guarantees.md
  pkg/chunk/chunk_store.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/util/flagext/time.go
  pkg/util/flagext/time_test.go
  tools/doc-generator/parser.go
Labels: size/XL

#2775 Update release instructions
  RELEASE.md
Labels: size/S

#2771 refactor processing of writes in boltdb index client
  pkg/chunk/local/boltdb_index_client.go
  pkg/chunk/local/boltdb_index_client_test.go
Labels: size/L

#2779 Initialize RuntimeConfig module only if config is specified
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
Labels: size/S

#2789 Don't use shipper context, but pass shipper service context instead.
  pkg/ingester/ingester_v2.go
Labels: size/S

#2791 Fix up CHANGELOG for release 1.2 and after
  CHANGELOG.md
Labels: size/M

#2784 make label name validation optional
  pkg/distributor/distributor.go
Labels: size/S

#2796 Fixes an issue in the index chunks/series intersect code.
  CHANGELOG.md
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/series_store.go
Labels: size/S

#2786 Instrument the Ruler Notifier
  CHANGELOG.md
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/S

#2797 Switched store-gateway query concurrency limit from per-tenant to shared
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  go.mod
  go.sum
  pkg/ingester/ingester_v2.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/M

#2792 Fix ruler.outage-tolerance changelog entry and orders correctly
  CHANGELOG.md
Labels: size/XS

#2799 Little query tee enhancements
  CHANGELOG.md
  tools/querytee/proxy.go
  tools/querytee/proxy_metrics.go
Labels: size/S

#2798 Upgrade Prometheus to current master
  go.mod
  go.sum
  pkg/api/api.go
  pkg/configs/legacy_promql/test.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/querier.go
  pkg/ruler/compat.go
  vendor/github.com/prometheus/prometheus/pkg/labels/matcher.go
  vendor/github.com/prometheus/prometheus/pkg/labels/regexp.go
  vendor/github.com/prometheus/prometheus/storage/fanout.go
  vendor/github.com/prometheus/prometheus/storage/generic.go
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/codec.go
  vendor/github.com/prometheus/prometheus/storage/remote/queue_manager.go
  vendor/github.com/prometheus/prometheus/storage/remote/read.go
  vendor/github.com/prometheus/prometheus/storage/remote/storage.go
  vendor/github.com/prometheus/prometheus/storage/remote/write.go
  vendor/github.com/prometheus/prometheus/storage/series.go
  vendor/github.com/prometheus/prometheus/tsdb/block.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/index/index.go
  vendor/github.com/prometheus/prometheus/tsdb/querier.go
  vendor/github.com/prometheus/prometheus/web/api/v1/api.go
  vendor/modules.txt
Labels: size/S

#2766 Do not split requests around ingester boundaries
  CHANGELOG.md
  pkg/querier/queryrange/querysharding.go
  pkg/querier/queryrange/querysharding_test.go
Labels: size/L

#2780 Added flag to flush chunks to long-term storage even when using WAL.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/wal.go
  pkg/ring/lifecycler.go
Labels: size/S

#2800 fix cache generation keys prefix
  CHANGELOG.md
  pkg/chunk/cache/cache_gen.go
  pkg/chunk/cache/cache_gen_test.go
Labels: size/M

#2802 Update seriesFlushReason when flushing, not enqueing.
  CHANGELOG.md
  pkg/ingester/flush.go
  pkg/ingester/metrics.go
Labels: size/S

#2752 Dynamically generate available options for -target commandline arg
  CHANGELOG.md
  cmd/cortex/main.go
  cmd/cortex/main_test.go
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/L

#2806 track oldest delete request age since their cancellation period is over
  CHANGELOG.md
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/testexporter/correctness/runner_test.go
Labels: size/M

#2814 Added support for path prefix to query-tee.
  CHANGELOG.md
  cmd/query-tee/main.go
  cmd/query-tee/main_test.go
Labels: size/M

#2801 add support for delete chunks in index stores
  CHANGELOG.md
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/chunk_store.go
  pkg/chunk/gcp/bigtable_object_client.go
  pkg/chunk/grpc/grpc_client_test.go
  pkg/chunk/grpc/storage_client.go
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/objectclient/client.go
  pkg/chunk/storage/metrics.go
  pkg/chunk/storage_client.go
Labels: size/M

#2815 Add support for forwarding X-Scope-OrgId.
  CHANGELOG.md
  tools/querytee/proxy_backend.go
Labels: size/XS

#2803 Compact idle blocks.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
Labels: size/L

#2794 Added support for flushing blocks
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/ingester/flush.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
Labels: size/L
