Repository cortexproject/cortex, pull requests merged in 2020-02, with the labels that each got.

#1839 Migrate integration tests to Go testing framework
  .circleci/config.yml
  integration-tests/common.sh
  integration-tests/start-components.sh
  integration-tests/stop-components.sh
  integration-tests/test-flush.sh
  integration-tests/test-handover.sh
  integration/README.md
  integration/backward_compatibility_test.go
  integration/chunks-storage-schema-dynamodb.yaml
  integration/configs.go
  integration/framework/client.go
  integration/framework/scenario.go
  integration/framework/service.go
  integration/framework/util.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/util.go
  tools/test
Labels: keepalive

#2188 Added services package.
  pkg/util/services/README.md
  pkg/util/services/basic_service.go
  pkg/util/services/basic_service_test.go
  pkg/util/services/example_test.go
  pkg/util/services/manager.go
  pkg/util/services/manager_test.go
  pkg/util/services/service.go
  pkg/util/services/services.go
  pkg/util/services/services_test.go
Labels: size/XXL

#2190 Pass logger with userID to per-user TSDB components.
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/ingester/ingester_v2.go
  pkg/querier/block_store.go
Labels: size/S

#2194 Fix flaky test for AwaitRunning.
  pkg/util/services/basic_service_test.go
Labels: size/M

#2189 Shared in-memory index cache for queriers with blocks storage
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  integration/configs.go
  integration/querier_test.go
  pkg/querier/block_store.go
  pkg/querier/block_store_metrics.go
  pkg/querier/bucket_store_metrics_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/index_cache.go
Labels: size/L
