Repository cortexproject/cortex, pull requests merged in 2020-09, with the labels that each got.

#3054 Support checking cache behavior based on query request
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/queryrange.pb.go
  pkg/querier/queryrange/queryrange.proto
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/L

#3073 Start an Alertmanager when it is requested if we have a fallback config
  CHANGELOG.md
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#3119 makes rule group validation an interface
  pkg/ruler/api.go
  pkg/ruler/manager.go
  pkg/ruler/ruler.go
Labels: size/M

#3112 change: separate distributor into api and service module
  CHANGELOG.md
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
Labels: size/M

#3092 Blocksconvert suite of tools for converting existing chunks data to blocks
  Makefile
  cmd/blocksconvert/Dockerfile
  cmd/blocksconvert/main.go
  pkg/chunk/gcp/bigtable_index_client.go
  tools/blocksconvert/allowed_users.go
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/builder/fetcher.go
  tools/blocksconvert/builder/heartbeat.go
  tools/blocksconvert/builder/symbols.go
  tools/blocksconvert/builder/tsdb.go
  tools/blocksconvert/builder/tsdb_test.go
  tools/blocksconvert/plan_file.go
  tools/blocksconvert/plan_file_test.go
  tools/blocksconvert/scanner/bigtable_index_reader.go
  tools/blocksconvert/scanner/bigtable_index_reader_test.go
  tools/blocksconvert/scanner/files.go
  tools/blocksconvert/scanner/index_entry.go
  tools/blocksconvert/scanner/index_reader.go
  tools/blocksconvert/scanner/scanner.go
  tools/blocksconvert/scanner/scanner_processor.go
  tools/blocksconvert/scanner/scanner_processor_test.go
  tools/blocksconvert/scanner/scanner_test.go
  tools/blocksconvert/scheduler.pb.go
  tools/blocksconvert/scheduler.proto
  tools/blocksconvert/scheduler/plan_status.go
  tools/blocksconvert/scheduler/scheduler.go
  tools/blocksconvert/scheduler/scheduler_test.go
  tools/blocksconvert/shared_config.go
Labels: size/XXL

#3120 Allow the Ruler to delete a whole namespace
  CHANGELOG.md
  docs/api/_index.md
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/api/api.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/rules/compat.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/store.go
  pkg/ruler/store_mock_test.go
Labels: size/L

#2926 retry processing of failed delete requests
  CHANGELOG.md
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/objectclient/client.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/testutils/testutils.go
Labels: size/L

#3129 feat: allow for temp dir to be specified using an env variable in E2E…
  docs/contributing/how-integration-tests-work.md
  integration/e2e/scenario.go
  integration/e2e/util.go
Labels: size/M

#3126 Index page should honor configured HTTP path prefix.
  CHANGELOG.md
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
  pkg/cortex/modules.go
Labels: size/M

#3131 Support fgprof debug endpoint
  go.mod
  go.sum
  pkg/api/api.go
  vendor/github.com/felixge/fgprof/LICENSE.txt
  vendor/github.com/felixge/fgprof/README.md
  vendor/github.com/felixge/fgprof/fgprof.go
  vendor/github.com/felixge/fgprof/format.go
  vendor/github.com/felixge/fgprof/go.mod
  vendor/github.com/felixge/fgprof/go.sum
  vendor/github.com/felixge/fgprof/handler.go
  vendor/github.com/felixge/fgprof/pprof.go
  vendor/github.com/google/pprof/AUTHORS
  vendor/github.com/google/pprof/CONTRIBUTORS
  vendor/github.com/google/pprof/LICENSE
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/filter.go
  vendor/github.com/google/pprof/profile/index.go
  vendor/github.com/google/pprof/profile/legacy_java_profile.go
  vendor/github.com/google/pprof/profile/legacy_profile.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/google/pprof/profile/proto.go
  vendor/github.com/google/pprof/profile/prune.go
  vendor/modules.txt
Labels: size/XS

#3144 Removed promql.lookback-delta option.
  CHANGELOG.md
  pkg/querier/querier.go
Labels: size/S

#3145 Remove obsolete `results_cache.max_freshness` from YAML config.
  CHANGELOG.md
  docs/configuration/prometheus-frontend.md
  docs/configuration/prometheus-frontend.yml
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/M

#3141 split ingester module into ingester and ingesterService
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
Labels: size/S

#3098 Make ruler evaluation delay configuration per user.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/validation/limits.go
Labels: size/M

#3149 export distributor properties to make ingester extendable
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/S

#3165 Fix failing integration tests
  pkg/cortex/modules.go
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/ring/kv/memberlist/tcp_transport.go
Labels: size/L

#3122 blocksconvert: Set compaction sources correctly
  tools/blocksconvert/builder/tsdb.go
  tools/blocksconvert/builder/tsdb_test.go
Labels: size/M

#3105 Honor configured Cassandra consistency when creating the keyspace
  CHANGELOG.md
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/cassandra/storage_client_test.go
Labels: size/L

#3157 Added default template funcs to templates validation
  CHANGELOG.md
  pkg/configs/api/api.go
  pkg/configs/api/api_test.go
Labels: size/S

#3164 add store method for getting fetcher for a chunk
  pkg/chunk/chunk_store.go
  pkg/chunk/composite_store.go
  pkg/chunk/composite_store_test.go
  pkg/chunk/schema_config.go
  pkg/chunk/schema_config_test.go
Labels: size/L

#3133 Index page should only show links that are valid for running Cortex
  CHANGELOG.md
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
Labels: size/L

#3170 Fix @ in the S3 URL without username and password
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/weaveworks/common/aws/config.go
  vendor/github.com/weaveworks/common/httpgrpc/README.md
  vendor/github.com/weaveworks/common/server/server.go
  vendor/modules.txt
Labels: size/XS

#3160 Doc fixes related to block storage
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/production/running.md
  k8s/query-frontend-svc.yaml
Labels: size/XS

#3158 Improve the error message in readiness check when unhealthy ingesters are in the ring.
  pkg/ring/lifecycler.go
Labels: size/XS

#3175 Fixed double tracing spans
  pkg/cortex/cortex.go
  pkg/cortex/tracing.go
Labels: size/M

#3167 Fix the querier returning 500 status code on query range limit errors
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/querier_test.go
  pkg/api/queryable.go
  pkg/api/queryable_test.go
  pkg/querier/querier.go
  pkg/util/validation/limits.go
Labels: size/M

#3125 AwaitHealthy now returns more descriptive error message
  pkg/util/services/manager.go
  pkg/util/services/manager_test.go
Labels: size/S

#3155 Make it possible for user to discover which modules are included in "All" target.
  CHANGELOG.md
  cmd/cortex/main.go
  cmd/cortex/main_test.go
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/M

#3180 Move Cassandra and Blocks storage to GA
  CHANGELOG.md
  docs/api/_index.md
  docs/architecture.md
  docs/blocks-storage/_index.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/production-tips.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/querier.template
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/getting-started/getting-started-blocks.md
  docs/roadmap.md
  integration/backward_compatibility_test.go
  integration/configs.go
  integration/e2ecortex/services.go
  integration/getting_started_single_process_config_test.go
  integration/getting_started_with_gossiped_ring_test.go
  integration/querier_streaming_mixed_ingester_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  pkg/api/api.go
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/storage/factory.go
  pkg/ingester/ingester_v2.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/querier.go
  pkg/storage/backend/azure/config.go
  pkg/storage/backend/filesystem/config.go
  pkg/storage/backend/gcs/config.go
  pkg/storage/backend/s3/config.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/index_cache.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
  pkg/util/validation/limits.go
  tools/doc-generator/main.go
Labels: size/XXL

#3176 feat(e2e): set network name in e2e tests using env variable
  docs/contributing/how-integration-tests-work.md
  integration/configs.go
Labels: size/S

#3140 Issue3139 flushing
  CHANGELOG.md
  pkg/cortex/modules.go
  pkg/flusher/flusher.go
  pkg/ingester/flush_test.go
  pkg/ingester/ingester.go
Labels: size/L

#3127 Improvements to blocksconvert
  tools/blocksconvert/allowed_users.go
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/scanner/scanner.go
  tools/blocksconvert/scanner/scanner_processor.go
  tools/blocksconvert/scanner/scanner_processor_test.go
  tools/blocksconvert/scheduler/scheduler.go
  tools/blocksconvert/scheduler/scheduler_test.go
Labels: size/L

#3080 Fail the config validation if an empty node is set at root level
  CHANGELOG.md
  cmd/cortex/main.go
  cmd/cortex/main_test.go
  pkg/chunk/encoding/factory.go
  pkg/cortex/cortex.go
Labels: size/M

#3137 Follow symlinks and ignore target directories.
  CHANGELOG.md
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
Labels: size/M

#3183 Fixed doc about Gossip/memberlist support no more experimental
  docs/getting-started/getting-started-with-gossip-ring.md
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/XS

#3115 Removed deprecated untyped record from chunks WAL
  CHANGELOG.md
  pkg/ingester/wal.go
  pkg/ingester/wal.pb.go
  pkg/ingester/wal.proto
  pkg/ingester/wal_test.go
Labels: size/L

#3182 Release the lock when loading of cache gen number fails.
  CHANGELOG.md
  pkg/chunk/purger/tombstones.go
  pkg/chunk/purger/tombstones_test.go
Labels: size/M

#3177 Re-use memory for chunks in ingester QueryStream
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: size/M

#3162 Document blocksconvert tools.
  docs/blocks-storage/convert-stored-chunks-to-blocks.md
  docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
Labels: size/M

#3184 Micro fixes to CHANGELOG and API doc
  CHANGELOG.md
  docs/api/_index.md
  integration/e2ecortex/client.go
  integration/ruler_test.go
Labels: size/S

#3179 Update golang to 1.14.9 in build-image
  .circleci/config.yml
  build-image/Dockerfile
Labels: size/S

#2992 Update storage-aws.md
  docs/production/storage-aws.md
Labels: size/XS

#3186 Cutting CHANGELOG before next release
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#3187 Cut release 1.4.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#3189 Turn memcached circuit-breaker on by default
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/memcached_client.go
Labels: size/XS

#3190 Turn memcached circuit-breaker on by default (#3189)
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/memcached_client.go
Labels: size/XS

#3153 Configurable active user series
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/ingester/active_series.go
  pkg/ingester/active_series_test.go
  pkg/ingester/client/compat.go
  pkg/ingester/flush_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/metrics.go
  pkg/ingester/user_state.go
  pkg/ingester/user_state_test.go
  pkg/storage/tsdb/ref_cache_test.go
Labels: size/XL

#3193 Pool hash to reduce allocations on Push.
  pkg/ingester/active_series.go
Labels: size/S

#3195 fix: cleanup tempoary ruler files on startup and shutdown
  CHANGELOG.md
  integration/ruler_test.go
  pkg/ruler/manager.go
  pkg/ruler/mapper.go
Labels: size/M

#3192 Dont rely on hashes for collecting chunks together
  CHANGELOG.md
  integration/querier_test.go
  pkg/distributor/query.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/compat_test.go
  pkg/querier/chunk_store_queryable.go
Labels: size/L

#3178 Cancel abandoned operations in ReplicationSet.Do()
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/query.go
  pkg/ring/replication_set.go
Labels: size/M

#3196 Fixed changelog entry for PR 3178
  CHANGELOG.md
Labels: size/XS

#3113 Shuffle-sharding of queriers in the query-frontend
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/querier_sharding_test.go
  pkg/cortex/modules.go
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend.pb.go
  pkg/querier/frontend/frontend.proto
  pkg/querier/frontend/frontend_querier_queues.go
  pkg/querier/frontend/frontend_querier_queues_test.go
  pkg/querier/frontend/frontend_queues.go
  pkg/querier/frontend/frontend_queues_test.go
  pkg/querier/frontend/frontend_test.go
  pkg/querier/frontend/queue_test.go
  pkg/querier/frontend/worker.go
  pkg/querier/frontend/worker_frontend_manager.go
  pkg/querier/frontend/worker_frontend_manager_test.go
  pkg/querier/frontend/worker_test.go
  pkg/util/validation/limits.go
Labels: size/XXL

#3090 Added shuffle sharding support to generate a subring
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/e2e/metrics.go
  integration/e2e/service.go
  integration/ingester_sharding_test.go
  pkg/cortex/cortex.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/model.go
  pkg/ring/model_test.go
  pkg/ring/replication_strategy.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ring/util.go
  pkg/storage/tsdb/util.go
  pkg/storegateway/sharding_strategy.go
  pkg/storegateway/sharding_strategy_test.go
  pkg/util/validation/limits.go
Labels: size/XL

#3173 Blocksconvert: store series and symbols on the disk to avoid using large heap
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/builder/heap.go
  tools/blocksconvert/builder/series.go
  tools/blocksconvert/builder/series_iterator.go
  tools/blocksconvert/builder/series_test.go
  tools/blocksconvert/builder/symbols.go
  tools/blocksconvert/builder/symbols_iterator.go
  tools/blocksconvert/builder/tsdb.go
  tools/blocksconvert/builder/tsdb_test.go
Labels: size/XXL

#3201 Fix store-gateway sharding ring CLI flags prefix
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/querier.template
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  integration/e2ecortex/services.go
  integration/querier_test.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#3202 Fix store-gateway sharding ring CLI flags prefix (#3201)
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/querier.template
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  integration/e2ecortex/services.go
  integration/querier_test.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#3197 Check for postgres rows errors
  CHANGELOG.md
  pkg/configs/db/postgres/postgres.go
Labels: size/S

#3198 Mark TLS Configuration in gRPC, HTTP and etcd clients as experimental.
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
Labels: size/XS

#3203 Fixed DNS-based service discovery doc
  docs/configuration/arguments.md
Labels: size/XS

#3199 Add design documents about shuffle-sharding on read path and zone awareness
  docs/proposals/shuffle-sharding-and-zone-awareness.md
  docs/proposals/shuffle-sharding-on-the-read-path.md
Labels: size/L

#3205 Drop alertmanager message about blank config to debug
  CHANGELOG.md
  pkg/alertmanager/multitenant.go
Labels: size/XS

#3204 Cherry picked PR 3198
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
Labels: size/XS

#3185 Alertmanager Config API: Do not allow empty configurations
  CHANGELOG.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
Labels: size/L

#3211 Backported PR 3192
  CHANGELOG.md
  integration/querier_test.go
  pkg/distributor/query.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/compat_test.go
  pkg/querier/chunk_store_queryable.go
Labels: size/L

#3210 Ruler Experimental API: Fix rule group validation
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/manager.go
Labels: size/L

#3207 feat: add metric and fix querier int test flake
  CHANGELOG.md
  integration/querier_sharding_test.go
  pkg/querier/frontend/frontend.go
Labels: size/S

#3209 Blocksconvert: download plan file locally
  CHANGELOG.md
  docs/blocks-storage/convert-stored-chunks-to-blocks.md
  docs/configuration/v1-guarantees.md
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/plan_file.go
  tools/blocksconvert/scanner/scanner.go
Labels: size/L

#3213 Mark blocksconvert tools as experimental.
  docs/configuration/v1-guarantees.md
Labels: size/XS

#3200 Added flag to explicitly enable zone-awareness replication and added store-gateway support
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  docs/guides/zone-replication.md
  pkg/distributor/distributor_test.go
  pkg/ring/lifecycler.go
  pkg/ring/replication_strategy.go
  pkg/ring/replication_strategy_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/storegateway/gateway_ring.go
  pkg/storegateway/replication_strategy.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/XL

#3212 Cut Cortex 1.4.0-rc.1
  CHANGELOG.md
  VERSION
Labels: size/S

#3215 Improve DynamoDB BatchWrite error messages
  pkg/chunk/aws/dynamodb_storage_client.go
Labels: size/XS

#3220 Share auth-injector tool
  .gitignore
  tools/auth-injector/main.go
Labels: size/M

#3221 Arbitrary group loading in local rules backend
  integration/chunks_storage_backends_test.go
  pkg/cortex/modules.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
  pkg/ruler/storage.go
Labels: size/M

#3224 Clarify that schema config is used only by the chunks storage
  docs/blocks-storage/_index.md
  docs/configuration/schema-config-reference.md
  pkg/chunk/schema_config.go
Labels: size/S

#3225 Removed the deprecated flag -config-yaml
  CHANGELOG.md
  docs/configuration/arguments.md
  pkg/chunk/schema_config.go
Labels: size/S

#3222 Blocksconvert: added support for specifying date range for tables scan
  tools/blocksconvert/scanner/bigtable_index_reader.go
  tools/blocksconvert/scanner/scanner.go
Labels: size/M

#3217 support snappy cache in query frontend
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/S

#3232 add a QueryWithCursor method for boltdb to help doing multiple queries in a single transaction
  pkg/chunk/local/boltdb_index_client.go
Labels: size/M

#3214 Caching of shuffle-sharded subrings
  CHANGELOG.md
  pkg/ring/model.go
  pkg/ring/model_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/L

#3239 issues templates to gather all the required information in bug reports
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#3233 Added -version flag to Cortex.
  CHANGELOG.md
  cmd/cortex/main.go
  cmd/cortex/main_test.go
  pkg/cortex/cortex.go
Labels: size/S

#3238 ObjectClient List refactoring
  integration/s3_storage_client_test.go
  pkg/alertmanager/alerts/objectclient/store.go
  pkg/alertmanager/storage.go
  pkg/chunk/aws/fixtures.go
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/aws/s3_storage_client_test.go
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/gcp/fixtures.go
  pkg/chunk/gcp/gcs_object_client.go
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/local/fixtures.go
  pkg/chunk/local/fs_object_client.go
  pkg/chunk/local/fs_object_client_test.go
  pkg/chunk/openstack/swift_object_client.go
  pkg/chunk/purger/purger_test.go
  pkg/chunk/storage/factory.go
  pkg/chunk/storage_client.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/storage.go
Labels: size/L

#3242 Fix TestShuffleShardWithCaching
  pkg/ring/ring_test.go
Labels: size/S

#3228 Enforce HTTP method required by most API endpoints
  CHANGELOG.md
  integration/api_endpoints_test.go
  integration/e2e/util.go
  pkg/api/api.go
  pkg/cortex/index.go
Labels: size/L

#3240 Document impact of unbalanced zones on zone-aware replication
  docs/guides/zone-replication.md
Labels: size/XS

#3245 blocksconvert: Retry block upload.
  CHANGELOG.md
  tools/blocksconvert/builder/builder.go
Labels: size/S

#3244 feat: expose S3 HTTP configs for TSDB S3 client
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/backend/s3/bucket_client.go
  pkg/storage/backend/s3/config.go
Labels: size/M

#3246 Fix help message in for lifecycler config
  pkg/ring/lifecycler.go
Labels: size/XS

#3248 Added registered timestamp to instances in the ring
  CHANGELOG.md
  pkg/distributor/distributor_test.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/basic_lifecycler_delegates.go
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ring/basic_lifecycler_test.go
  pkg/ring/http.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/model.go
  pkg/ring/model_test.go
  pkg/ring/ring.go
  pkg/ring/ring.pb.go
  pkg/ring/ring.proto
  pkg/ring/ring_test.go
  pkg/ruler/lifecycle_test.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/XL

#3191 Smooth out spikes in rate of chunk flush ops
  CHANGELOG.md
  pkg/ingester/flush.go
  pkg/ingester/ingester.go
Labels: size/M
