Repository cortexproject/cortex, pull requests merged in 2020-07, with the labels that each got.

#2733 Query frontend readiness
  CHANGELOG.md
  docs/operations/scalable-query-frontend.md
  docs/proposals/scalable-query-frontend.md
  integration/query_frontend_test.go
  pkg/cortex/cortex.go
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend_test.go
Labels: size/L

#2820 Set version to 1.2.0
  CHANGELOG.md
  RELEASE.md
  VERSION
Labels: size/XS

#2778 Fix chunks flushing bugs
  CHANGELOG.md
  integration/chunks_storage_backends_test.go
  pkg/ingester/flush.go
  pkg/ingester/flush_test.go
  pkg/ingester/ingester.go
  pkg/ingester/metrics.go
Labels: size/L

#2824 Clarified that -ingester.min-chunk-length doesn't apply to blocks storage
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/XS

#2788 [memberlist] Add support to join memberlist via SRV records
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/M

#2822 Make store-gateway mandatory when running the blocks storage
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  integration/querier_test.go
  pkg/cortex/modules.go
  pkg/querier/block.go
  pkg/querier/blocks_bucket_stores_service.go
  pkg/querier/blocks_bucket_stores_service_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_store_inmemory_server.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway_test.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/XL

#2834 Fix flaky test in issue 2825
  pkg/ingester/flush_test.go
Labels: size/XS

#2826 Add -store.max-query-length support to blocks storage
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/configuration/config-file-reference.md
  pkg/chunk/chunk_store_test.go
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/validate.go
  tools/doc-generator/main.go
Labels: size/L

#2847 fix typo in changelog
  CHANGELOG.md
Labels: size/XS

#2846 Fix typo in getting-started-chunks.md
  docs/getting-started/getting-started-chunks.md
Labels: size/XS

#2839 Fix memory leak caused by object pool and zero copy
  pkg/ingester/client/timeseries.go
Labels: size/XS

#2842 Update RELEASE doc with 1.3.0 shepherd
  RELEASE.md
Labels: size/XS

#2841 fix a flaky test in purger
  pkg/chunk/purger/purger_test.go
Labels: size/S

#2850 Open up Release process to other end users.
  RELEASE.md
Labels: size/XS

#2843 Improved documentation about limits not supported by blocks storage
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/S

#2835 Make label name character set validation optional
  pkg/distributor/distributor.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/M

#2831 S3 Config Improvements
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/s3_storage_client_test.go
  pkg/chunk/aws/s3_storage_client.go
Labels: size/L

#2768 Experimental Alertmanager API
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/.data-minio/.gitignore
  development/tsdb-blocks-storage-s3/.data-minio/cortex-alertmanager/.gitignore
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/apis.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  go.sum
  integration/alertmanager_test.go
  integration/configs.go
  integration/e2ecortex/client.go
  integration/e2ecortex/services.go
  pkg/alertmanager/alerts/compat.go
  pkg/alertmanager/alerts/configdb/store.go
  pkg/alertmanager/alerts/local/store.go
  pkg/alertmanager/alerts/objectclient/store.go
  pkg/alertmanager/api.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/alertmanager/storage.go
  pkg/api/api.go
  pkg/configs/client/client.go
  pkg/cortex/modules.go
Labels: size/XL

#2858 `make doc` to Fix master
  docs/configuration/config-file-reference.md
Labels: size/M

#2828 Public roadmap for the project
  docs/roadmap.md
Labels: size/M

#2837 Fix a bug about failure to add metrics of multi KV store
  CHANGELOG.md
  pkg/ring/kv/client.go
  pkg/ring/kv/client_test.go
  pkg/ring/kv/mock.go
Labels: size/L

#2817 fix a race in purger managing in process delete requests
  CHANGELOG.md
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/purger_test.go
Labels: size/L

#2862 Upgraded Docker base images to alpine:3.12
  CHANGELOG.md
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
Labels: size/S

#2867 Upgrade Prometheus
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/discovery/dockerswarm/dockerswarm.go
  vendor/github.com/prometheus/prometheus/pkg/rulefmt/rulefmt.go
  vendor/github.com/prometheus/prometheus/promql/parser/generated_parser.y
  vendor/github.com/prometheus/prometheus/promql/parser/generated_parser.y.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/modules.txt
Labels: size/XS

#2870 Compact TSDB on open.
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/M

#2871 Move cover to build image
  .circleci/config.yml
  build-image/Dockerfile
  tools/test
Labels: size/S

#2863 Improved website section index
  docs/case-studies/_index.md
  docs/configuration/_index.md
  docs/getting-started/_index.md
  docs/guides/_index.md
  docs/operations/_index.md
  docs/production/_index.md
  docs/proposals/_index.md
  docs/roadmap.md
  website/layouts/partials/section-index.html
Labels: size/S

#2857 Add a metric to track ruler update failures (errors in loading rules files).
  CHANGELOG.md
  pkg/ruler/ruler.go
Labels: size/XS

#2851 Support multiple Alertmanagers explicitly in the Ruler
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/notifier.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
Labels: size/L

#2852 Added -store.max-chunks-per-query limit support to blocks storage
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/cortex/modules.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/util/validation/limits.go
Labels: size/L

#2872 [Docs] HA Tracker: Add minimum configuration guide.
  docs/production/ha-pair-handling.md
Labels: size/M

#2881 use pointer receiver on lazySeriesSet methods
  pkg/querier/lazyquery/lazyquery.go
Labels: size/XS

#2880 Querier: Unset Host Header if DownstreamUrl is configured
  CHANGELOG.md
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend_test.go
Labels: size/M

#2877 Make Flusher mode to work with blocks-engine
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/flusher/flusher.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
  pkg/util/services/services.go
Labels: size/L

#2888 Fix up;oads => uploads typo
  docs/configuration/config-file-reference.md
  pkg/chunk/azure/blob_storage_client.go
Labels: size/XS

#2854 Adding the Ruler to the Single Binary
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-single-binary/.data-minio/.gitignore
  development/tsdb-blocks-storage-s3-single-binary/.data-minio/cortex-rules/.gitignore
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/configuration/single-process-config.md
  docs/configuration/single-process-config.yaml
  docs/guides/sharded_ruler.md
  integration/api_ruler_test.go
  integration/configs.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
  pkg/ruler/storage.go
Labels: size/L

#2874 Expose hashsum of the config files
  CHANGELOG.md
  cmd/cortex/main.go
  pkg/cortex/runtime_config.go
  pkg/util/runtimeconfig/manager.go
  pkg/util/runtimeconfig/manager_test.go
Labels: size/L

#2878 Replace legacy_rulefmt with prometheus/pkg/rulefmt in ruler
  go.mod
  integration/api_ruler_test.go
  integration/e2ecortex/client.go
  pkg/configs/userconfig/config.go
  pkg/configs/userconfig/config_test.go
  pkg/ruler/api.go
  pkg/ruler/legacy_rulefmt/rulefmt.go
  pkg/ruler/legacy_rulefmt/rulefmt_test.go
  pkg/ruler/legacy_rulefmt/testdata/bad_annotation.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/bad_expr.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/bad_lname.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/duplicate_grp.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/invalid_record_name.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/no_rec_alert.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/noexpr.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/record_and_alert.bad.yaml
  pkg/ruler/legacy_rulefmt/testdata/test.yaml
  pkg/ruler/mapper.go
  pkg/ruler/mapper_test.go
  pkg/ruler/rules/compat.go
  pkg/ruler/rules/store.go
  vendor/modules.txt
Labels: size/XL

#2899 Fixed rulefmt after merging PR #2878
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
Labels: size/S

#2893 sort samples from different series before checking for expected samples
  pkg/testexporter/correctness/simple.go
Labels: size/S

#2900 Clarified supported S3 endpoints for the blocks storage
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/backend/s3/config.go
Labels: size/S

#2865 make fs object client windows compatible and add a method to get pathseparator from object clients
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/gcp/gcs_object_client.go
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/local/fs_object_client.go
  pkg/chunk/local/fs_object_client_test.go
  pkg/chunk/openstack/swift_object_client.go
  pkg/chunk/storage_client.go
Labels: size/M

#2891 Allow for Custom Transport on Ruler s3 Client
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/aws/s3_storage_client_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/storage.go
Labels: size/L

#2905 fix for when sharding is enable query frontend returns 500 for storage errors instead of actual error code
  pkg/querier/queryrange/value.go
Labels: size/XS

#2915 Set a content type for the remote_read response
  CHANGELOG.md
  pkg/querier/remote_read.go
  pkg/querier/remote_read_test.go
Labels: size/XS

#2908 Use correct version of yaml
  integration/e2ecortex/client.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/store_mock_test.go
Labels: size/M

#2914 Move the fakeauth out of the Cortex module so it can be reused in other projects.
  pkg/api/api.go
  pkg/cortex/cortex.go
  pkg/cortex/fake_auth.go
  pkg/util/fakeauth/fake_auth.go
Labels: size/L

#2917 Loads schemacfg with correct flagset
  pkg/chunk/schema_config.go
Labels: size/XS

#2918 Upgrade Prometheus to master
  CHANGELOG.md
  go.mod
  go.sum
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/ruler/ruler.go
  vendor/github.com/prometheus/prometheus/discovery/README.md
  vendor/github.com/prometheus/prometheus/discovery/dockerswarm/dockerswarm.go
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/promql/test.go
  vendor/github.com/prometheus/prometheus/rules/alerting.go
  vendor/github.com/prometheus/prometheus/rules/manager.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/modules.txt
Labels: size/S

#2896 Recommend schema v9 and v10 for production
  docs/architecture.md
  docs/configuration/schema-config-reference.md
Labels: size/XS

#2821 Improve release instructions
  RELEASE.md
Labels: size/S

#2386 add json log support
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/util/log.go
  tools/doc-generator/parser.go
  vendor/github.com/weaveworks/common/logging/format.go
  vendor/github.com/weaveworks/common/logging/gokit.go
  vendor/github.com/weaveworks/common/logging/logrus.go
  vendor/github.com/weaveworks/common/server/server.go
  vendor/modules.txt
Labels: size/S

#2919 Documented how to migrate Thanos/Prometheus storage to Cortex
  docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
Labels: size/M

#2928 Fix the documentation cortex logo.
  website/assets/icons/logo.svg
Labels: size/XS

#2903 Remove global metrics registry and global logger in cache package
  CHANGELOG.md
  integration/chunks_storage_backends_test.go
  pkg/chunk/cache/background.go
  pkg/chunk/cache/background_test.go
  pkg/chunk/cache/cache.go
  pkg/chunk/cache/cache_test.go
  pkg/chunk/cache/fifo_cache.go
  pkg/chunk/cache/fifo_cache_test.go
  pkg/chunk/cache/instrumented.go
  pkg/chunk/cache/memcached.go
  pkg/chunk/cache/memcached_client.go
  pkg/chunk/cache/memcached_test.go
  pkg/chunk/cache/redis_cache.go
  pkg/chunk/cache/redis_cache_test.go
  pkg/chunk/cache/snappy.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/storage/caching_fixtures.go
  pkg/chunk/storage/caching_index_client.go
  pkg/chunk/storage/caching_index_client_test.go
  pkg/chunk/storage/factory.go
  pkg/chunk/storage/factory_test.go
  pkg/chunk/storage/index_client_test.go
  pkg/cortex/modules.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/XL

#2934 Updated limits doc to reflect when 0 means disabled
  docs/configuration/config-file-reference.md
  pkg/querier/queryrange/limits.go
  pkg/util/validation/limits.go
Labels: size/S

#2936 Log a warning when checking the ring and finding a problem
  pkg/ring/lifecycler.go
Labels: size/XS

#2922 Add max chunks per query support to store gateway
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/cortex/modules.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  pkg/util/validation/limits.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go
  vendor/github.com/thanos-io/thanos/pkg/gate/gate.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/swift/swift.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/custom.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/limiter.go
  vendor/github.com/thanos-io/thanos/pkg/store/local.go
  vendor/github.com/thanos-io/thanos/pkg/store/multitsdb.go
  vendor/github.com/thanos-io/thanos/pkg/store/postings_codec.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy.go
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/modules.txt
Labels: size/L

#2904 Manipulate ingesters query min time when -querier.query-ingesters-within is set
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/metadata_handler_test.go
  pkg/querier/querier_test.go
Labels: size/L

#2933 Clarify local website setup and upgrade deps
  .circleci/config.yml
  build-image/Dockerfile
  docs/contributing/how-to-run-website-locally.md
  website/package-lock.json
  website/package.json
Labels: size/S

#2939 Add a `user` label to the query_frontend_queue_length metric
  CHANGELOG.md
  pkg/querier/frontend/frontend.go
Labels: size/S

#2818 Metrics for enqueue/flush reason, and dequeue/flush outcome.
  CHANGELOG.md
  pkg/ingester/flush.go
  pkg/ingester/flush_test.go
  pkg/ingester/metrics.go
Labels: size/M

#2937 Cleanup blocks storage doc
  CHANGELOG.md
  docs/blocks-storage/_index.md
  docs/blocks-storage/production-tips.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/querier.template
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/getting-started/getting-started-with-gossip-ring.md
  docs/proposals/blocks-storage-sharding.md
  docs/proposals/ingesters-migration.md
  integration/.gitignore
  integration/configs.go
  integration/getting_started_single_process_config_test.go
  integration/ingester_hand_over_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  pkg/chunk/storage/factory.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
  pkg/ingester/flush.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/transfer.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/backend/azure/config.go
  pkg/storage/backend/filesystem/config.go
  pkg/storage/backend/gcs/config.go
  pkg/storage/backend/s3/config.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/bucket_client_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
  pkg/storage/tsdb/index_cache.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  tools/doc-generator/main.go
Labels: size/XXL

#2943 bugfix(ruler): fix crashing when manager registers duplicate metrics
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/ruler.go
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/XL

#2954 Fixed basic lifecycler instance registration when only the address differs
  CHANGELOG.md
  pkg/ring/basic_lifecycler.go
  pkg/ring/basic_lifecycler_test.go
Labels: size/S

#2951 Replace usage of sync/atomic with uber-go/atomic
  Makefile
  pkg/chunk/cache/memcached_test.go
  pkg/ingester/mapper.go
  pkg/ingester/rate.go
  pkg/ingester/series_map.go
  pkg/querier/frontend/frontend_test.go
  pkg/querier/queryrange/retry_test.go
  pkg/querier/queryrange/split_by_interval_test.go
  pkg/ring/batch.go
  pkg/ring/kv/memberlist/tcp_transport.go
  pkg/storage/tsdb/ref_cache.go
  pkg/storegateway/bucket_stores_test.go
  pkg/util/events.go
  pkg/util/services/services_test.go
Labels: size/L

#2953 Clarify documentation on series endpoint
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
Labels: size/XS

#2941 Translate errors to PromQL errors by wrapping queryable.
  CHANGELOG.md
  pkg/api/api.go
  pkg/api/queryable.go
  pkg/api/queryable_test.go
  pkg/chunk/chunk_store_utils.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/querier/block.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/chunk_store_queryable.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/querier.go
Labels: size/XL

#2732 Add validation check for chunks and index in schema config
  CHANGELOG.md
  pkg/chunk/schema_config.go
  pkg/chunk/schema_config_test.go
Labels: size/L

#2963 Ruler TenantManager interface
  pkg/cortex/modules.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/L

#2940 Support Snappy compression for gRPC
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/gcp/bigtable_index_client.go
  pkg/chunk/storage/factory.go
  pkg/cortex/cortex.go
  pkg/ingester/client/client.go
  pkg/querier/frontend/worker.go
  pkg/util/grpc/encoding/snappy/snappy.go
  pkg/util/grpc/encoding/snappy/snappy_test.go
  pkg/util/grpcclient/grpcclient.go
Labels: size/L
