Repository cortexproject/cortex, pull requests merged in 2020-10, with the labels that each got.

#3257 Change -frontend.max-queriers-per-user to -frontend.max-queriers-per-tenant
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/shuffle-sharding.md
  integration/querier_sharding_test.go
  pkg/util/validation/limits.go
Labels: size/M

#3218 Speed up the listing of rule groups on the Ruler Configuration API
  CHANGELOG.md
  pkg/chunk/gcp/gcs_object_client.go
  pkg/ruler/rules/objectclient/rule_store.go
Labels: size/M

#3261 Replace SegmentRange with upstream wal.Segments
  pkg/ingester/wal.go
Labels: size/M

#3266 Cut Cortex 1.4.0 stable
  CHANGELOG.md
  VERSION
  docs/production/storage-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#3235 Shuffle-sharding support in Ruler.
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/.data-configstore/api/prom/configs/rules
  development/tsdb-blocks-storage-s3/.data-configstore/api/prom/configs/rules.yaml
  development/tsdb-blocks-storage-s3/.data-minio/.gitignore
  development/tsdb-blocks-storage-s3/.data-minio/cortex-ruler/.gitignore
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  development/tsdb-blocks-storage-s3/goland/ruler-1.run.xml
  development/tsdb-blocks-storage-s3/goland/ruler-2.run.xml
  docs/configuration/config-file-reference.md
  docs/guides/shuffle-sharding.md
  integration/chunks_storage_backends_test.go
  pkg/chunk/storage_client.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/frontend/frontend_querier_queues.go
  pkg/ring/model.go
  pkg/ring/replication_set.go
  pkg/ring/ring.go
  pkg/ruler/api.go
  pkg/ruler/compat.go
  pkg/ruler/manager.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_replication_strategy.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/store.go
  pkg/ruler/rules/store_test.go
  pkg/ruler/store_mock_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
  pkg/util/shard.go
  pkg/util/validation/limits.go
Labels: size/XXL

#3264 Set cortex as user agent for requests
  CHANGELOG.md
  pkg/configs/client/client.go
Labels: size/XS

#3262 Sort the entries in Cortex Services Status by name
  pkg/cortex/status.go
Labels: size/XS

#3267 Added Cortex 1.4.0 to backward compatibility tests
  integration/backward_compatibility_test.go
Labels: size/XS

#3254 Update comment to reflect current state.
  pkg/ruler/api.go
Labels: size/XS

#3270 Clarify 'implements ChunkStore' doc comments
  pkg/chunk/chunk_store.go
  pkg/chunk/series_store.go
  pkg/querier/lazyquery/lazyquery.go
Labels: size/S

#3279 Make it possible to extend Makefile with custom settings.
  .gitignore
  Makefile
  Makefile.local.example
Labels: size/S

#3269 Split listing and loading rule groups in rules.RuleStore interface
  CHANGELOG.md
  integration/chunks_storage_backends_test.go
  pkg/chunk/inmemory_storage_client.go
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/local/local_test.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/objectclient/rule_store_test.go
  pkg/ruler/rules/store.go
  pkg/ruler/rules/store_test.go
  pkg/ruler/storage.go
  pkg/ruler/store_mock_test.go
Labels: size/XL

#3292 Don't set selected attributes when using delimiter.
  CHANGELOG.md
  pkg/chunk/gcp/gcs_object_client.go
Labels: size/S

#3287 Error if the store gateway is run on an invalid engine
  CHANGELOG.md
  pkg/cortex/modules.go
Labels: size/XS

#3291 bump up go-redis/redis to v8.2.3
  go.mod
  go.sum
  vendor/github.com/go-redis/redis/v8/CHANGELOG.md
  vendor/github.com/go-redis/redis/v8/Makefile
  vendor/github.com/go-redis/redis/v8/README.md
  vendor/github.com/go-redis/redis/v8/cluster.go
  vendor/github.com/go-redis/redis/v8/command.go
  vendor/github.com/go-redis/redis/v8/commands.go
  vendor/github.com/go-redis/redis/v8/go.mod
  vendor/github.com/go-redis/redis/v8/go.sum
  vendor/github.com/go-redis/redis/v8/internal/arg.go
  vendor/github.com/go-redis/redis/v8/internal/hashtag/hashtag.go
  vendor/github.com/go-redis/redis/v8/internal/internal.go
  vendor/github.com/go-redis/redis/v8/internal/pool/conn.go
  vendor/github.com/go-redis/redis/v8/internal/proto/reader.go
  vendor/github.com/go-redis/redis/v8/internal/rand/rand.go
  vendor/github.com/go-redis/redis/v8/internal/util.go
  vendor/github.com/go-redis/redis/v8/options.go
  vendor/github.com/go-redis/redis/v8/pubsub.go
  vendor/github.com/go-redis/redis/v8/redis.go
  vendor/github.com/go-redis/redis/v8/renovate.json
  vendor/github.com/go-redis/redis/v8/ring.go
  vendor/github.com/go-redis/redis/v8/sentinel.go
  vendor/golang.org/x/exp/AUTHORS
  vendor/golang.org/x/exp/CONTRIBUTORS
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/rand/exp.go
  vendor/golang.org/x/exp/rand/normal.go
  vendor/golang.org/x/exp/rand/rand.go
  vendor/golang.org/x/exp/rand/rng.go
  vendor/golang.org/x/exp/rand/zipf.go
  vendor/modules.txt
Labels: size/L

#3295 Expose doc for instance_interface_names
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ruler/ruler_ring.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#3298 Redis cache: added parameter to disable SSL certificate verification
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/production/caching.md
  pkg/chunk/cache/redis_client.go
Labels: size/M

#3278 Add injectable middlewares to bucket client
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/config.go
Labels: size/S

#3301 Increase -<prefix>.redis.timeout default from 100ms to 500ms
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/redis_client.go
Labels: size/XS

#3275 Add an ability to load an arbitrary list of Cortex modules
  CHANGELOG.md
  cmd/cortex/main.go
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/util/flagext/stringslicecsv.go
  pkg/util/flagext/stringslicecsv_test.go
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
  tools/doc-generator/parser.go
Labels: size/L

#3309 Blocks compactionLoop: Respect context cancellation faster.
  pkg/ingester/ingester_v2.go
Labels: size/XS

#3310 [BUGFIX] Fix reporting of `cortex_prometheus_rule_group_duration_seconds`
  CHANGELOG.md
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
Labels: size/M

#3307 Use valid grpc header
  CHANGELOG.md
  pkg/util/extract_forwarded.go
Labels: size/XS

#3314 Fixed gRPC connections leaking in rulers when rulers sharding is enabled and APIs called
  CHANGELOG.md
  pkg/ruler/ruler.go
Labels: size/XS

#3312 Auth injector defaults
  tools/auth-injector/main.go
Labels: size/S

#3311 Clarify how to configure auth for BigTable and GCS
  docs/configuration/config-file-reference.md
  pkg/chunk/gcp/bigtable_index_client.go
  pkg/chunk/gcp/gcs_object_client.go
Labels: size/S

#3299 Fixed shuffle sharding consistency when zone-awareness is enabled and the shard size is increased or instances in a new zone are added
  CHANGELOG.md
  pkg/ingester/active_series.go
  pkg/ingester/active_series_test.go
  pkg/querier/frontend/frontend_querier_queues.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ruler/ruler_test.go
  pkg/util/shard.go
  pkg/util/yolo.go
  pkg/util/yolo_test.go
Labels: size/L

#3313 Fix flaky test.
  pkg/ring/kv/consul/client.go
  pkg/ring/ring_test.go
Labels: size/M

#3302 Migrate CircleCI workflows to GitHub Actions (1/3)
  .github/README.md
  .github/workflows/test-build-deploy.yml
Labels: size/L

#3324 Remove artifacts upload from GitHub actions
  .github/workflows/test-build-deploy.yml
Labels: size/S

#3323 Upgrade build-image from Debian stretch to buster
  .circleci/config.yml
  .github/README.md
  .github/workflows/test-build-deploy.yml
  build-image/Dockerfile
  docs/contributing/how-to-update-the-build-image.md
  pkg/chunk/purger/delete_plan.pb.go
  pkg/chunk/storage/caching_index_client.pb.go
  pkg/ingester/client/cortex.pb.go
  pkg/querier/queryrange/queryrange.pb.go
Labels: size/M

#3316 test: add integration test for ruler evaluation delay
  integration/configs.go
  integration/ruler_test.go
Labels: size/M

#3283 Blocksconvert cleaner
  .gitignore
  CHANGELOG.md
  cmd/blocksconvert/main.go
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/builder/fetcher.go
  tools/blocksconvert/cleaner/cleaner.go
  tools/blocksconvert/plan_file.go
  tools/blocksconvert/planprocessor/heartbeat.go
  tools/blocksconvert/planprocessor/service.go
  tools/blocksconvert/scheduler.pb.go
  tools/blocksconvert/scheduler.proto
  tools/blocksconvert/scheduler/plan_status.go
  tools/blocksconvert/scheduler/scheduler.go
  tools/blocksconvert/scheduler/scheduler_test.go
Labels: size/XXL

#3328 Don't return raw buffer from util.ParseProtoReader()
  pkg/ingester/client/client_test.go
  pkg/querier/remote_read.go
  pkg/util/http.go
  pkg/util/push/push.go
Labels: size/S

#3273 Add more documentation on AM templates
  docs/api/_index.md
Labels: size/S

#3335 Increase integration tests timeout
  .circleci/config.yml
  integration/backward_compatibility_test.go
Labels: size/S

#3263 Use Promauto.With() where possible
  pkg/chunk/table_manager.go
  pkg/compactor/syncer_metrics.go
Labels: size/M

#3338 add GetHeaders to the Response interface
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/results_cache.go
Labels: size/S

#3288 feat: separate ruler into ruler and rulerAPI components
  pkg/api/api.go
  pkg/cortex/modules.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
Labels: size/L

#3340 blocksconvert: Scanner uploads files concurrently
  CHANGELOG.md
  tools/blocksconvert/scanner/scanner.go
  tools/blocksconvert/scanner/scanner_test.go
Labels: size/M

#3289 Modify Alertmanager config metrics
  CHANGELOG.md
  integration/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#3252 Add ingesters shuffle sharding support on the read path
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/e2e/metrics_options.go
  integration/e2e/service.go
  integration/ingester_sharding_test.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/ring/replication_set.go
  pkg/ring/replication_set_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  tools/test
Labels: size/XXL

#3351 BugFix: setting -race and code coverage flags for GitHub Actions workflow
  tools/test
Labels: size/XS

#3327 Added section on Cleaner.
  docs/blocks-storage/convert-stored-chunks-to-blocks.md
Labels: size/S

#3234 Correct link for Block Storage reference
  docs/architecture.md
Labels: size/XS

#3356 Export distributor method to get ingester replication set
  pkg/distributor/distributor.go
  pkg/distributor/query.go
Labels: size/S

#3360 Fixed Gossip memberlist members joining when addresses are configured using DNS-based service discovery
  CHANGELOG.md
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/XS

#3354 Fail fast an ingester if unable to load existing TSDBs
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3352 add ingester interface
  pkg/api/api.go
Labels: size/S

#3361 Remove comments that doesn't seem right
  pkg/distributor/ha_tracker.go
Labels: size/XS

#3341 Migrate CircleCI workflows to GitHub Actions (2/3)
  .github/workflows-doc.md
  .github/workflows/scripts/install-docker.sh
  .github/workflows/test-build-deploy.yml
Labels: size/L

#3363 Upgrade Thanos to latest master
  CHANGELOG.md
  go.mod
  go.sum
  pkg/querier/block.go
  pkg/querier/block_test.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway_test.go
  tools/blocksconvert/builder/tsdb.go
  vendor/github.com/thanos-io/thanos/pkg/block/block.go
  vendor/github.com/thanos-io/thanos/pkg/block/index.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/streamed_block_writer.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/resolver.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/helpers.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/matchers.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/custom.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/rpc.proto
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/labelpb/label.go
  vendor/github.com/thanos-io/thanos/pkg/store/labelpb/types.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/labelpb/types.proto
  vendor/github.com/thanos-io/thanos/pkg/store/local.go
  vendor/github.com/thanos-io/thanos/pkg/store/multitsdb.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/custom.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/prompb/types.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/prompb/types.proto
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.proto
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/testutil/series.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/types.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/types.proto
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/modules.txt
Labels: size/XXL

#3346 Avoid deletion of blocks which are not shipped
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3370 Enforce integration tests default flags config to never be overwritten
  integration/alertmanager_test.go
  integration/backward_compatibility_test.go
  integration/chunks_delete_series_test.go
  integration/chunks_storage_backends_test.go
  integration/configs.go
  integration/ingester_flush_test.go
  integration/ingester_hand_over_test.go
  integration/ingester_sharding_test.go
  integration/integration_memberlist_single_binary_test.go
  integration/querier_remote_read_test.go
  integration/querier_sharding_test.go
  integration/querier_streaming_mixed_ingester_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/ruler_test.go
Labels: size/L

#3358 fix common prefixes returned by List method of s3 client
  CHANGELOG.md
  pkg/chunk/aws/s3_storage_client.go
Labels: size/XS

#3285 fix timeout handling in GetObject for azure and gcs
  CHANGELOG.md
  pkg/alertmanager/alerts/objectclient/store.go
  pkg/chunk/azure/blob_storage_client.go
  pkg/chunk/gcp/gcs_object_client.go
  pkg/chunk/storage_client.go
  pkg/chunk/util/util.go
Labels: size/M

#3372 Include the tenant ID as part of the notifier logs
  CHANGELOG.md
  pkg/ruler/manager.go
Labels: size/XS

#3366 Per tenant ruler rule group limits
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/store_mock_test.go
  pkg/util/validation/limits.go
Labels: size/L

#3369 Fixed max global series per user/metric limit when shuffle sharding is enabled
  CHANGELOG.md
  docs/configuration/arguments.md
  integration/ingester_limits_test.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/limiter.go
  pkg/ingester/limiter_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/ring.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  pkg/util/math.go
  pkg/util/shard.go
  pkg/util/shard_test.go
Labels: size/XXL

#3378 Fixed TestIngesterGlobalLimits flakyness
  integration/ingester_limits_test.go
Labels: size/S

#3368 Migrate CircleCI workflows to GitHub Actions (3/3)
  .circleci/config.yml
  .github/workflows/test-build-deploy.yml
Labels: size/L

#3379 Fixed panic in gRPC opentracing instrumentation
  go.mod
  go.sum
  vendor/github.com/opentracing-contrib/go-grpc/LICENSE
  vendor/github.com/opentracing-contrib/go-grpc/client.go
  vendor/github.com/opentracing-contrib/go-grpc/go.mod
  vendor/github.com/opentracing-contrib/go-grpc/go.sum
  vendor/github.com/opentracing-contrib/go-grpc/options.go
  vendor/github.com/opentracing-contrib/go-grpc/server.go
  vendor/modules.txt
Labels: size/XS

#3380 Fixed deploy via GitHub actions
  .github/workflows/test-build-deploy.yml
Labels: size/XS

#3382 export Ingester interface
  pkg/api/api.go
Labels: size/XS

#3381 Fixed TestKV_List_Delete flakyness
  .circleci/config.yml
  .github/workflows/test-build-deploy.yml
  integration/e2e/db/db.go
  integration/e2e/images/images.go
  integration/e2e/service.go
Labels: size/M

#3377 Clarify FD limits for blocks storage
  docs/blocks-storage/production-tips.md
Labels: size/S

#3320 feat: simplify query related modules
  integration/getting_started_single_process_config_test.go
  integration/query_frontend_test.go
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
Labels: size/XL

#3390 Volunteer to release 1.5
  RELEASE.md
Labels: size/XS

#3329 Support metric_relabel_configs in distributor
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/config-file-reference.template
  docs/configuration/v1-guarantees.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  tools/doc-generator/parser.go
Labels: size/L

#3392 Refactored ingester Limiter tests
  pkg/ingester/limiter_test.go
Labels: size/XL

#3276 Fix for #3111 Read form values and request body before sending request to RoundTripper
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend_test.go
Labels: size/L

#3391 Move the compactor to use its own ring operation
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/ring/model.go
  pkg/ring/ring.go
Labels: size/S

#3303 Adding OpenStack Swift support to blocks storage
  .gitignore
  CHANGELOG.md
  development/tsdb-blocks-storage-swift-single-binary/.data-cortex-1/.gitignore
  development/tsdb-blocks-storage-swift-single-binary/.data-cortex-2/.gitignore
  development/tsdb-blocks-storage-swift-single-binary/.dockerignore
  development/tsdb-blocks-storage-swift-single-binary/.gitignore
  development/tsdb-blocks-storage-swift-single-binary/compose-down.sh
  development/tsdb-blocks-storage-swift-single-binary/compose-up.sh
  development/tsdb-blocks-storage-swift-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-swift-single-binary/config/grafana-agent.yaml
  development/tsdb-blocks-storage-swift-single-binary/config/prometheus.yaml
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/docker-compose.yml
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/v1-guarantees.md
  pkg/storage/backend/swift/bucket_client.go
  pkg/storage/backend/swift/config.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/config.go
Labels: size/XL

#3385 Added option to enable/disable specific users for compaction.
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/L

#3343 fix(ruler): properly read OrgID from context
  CHANGELOG.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
Labels: size/M

#3399 Wait until container is actually running, not just created.
  integration/e2e/service.go
  integration/e2e/util.go
Labels: size/M

#3397 Improve Alertmanager logging when serving requests via API/UI
  CHANGELOG.md
  pkg/alertmanager/multitenant.go
Labels: size/XS

#3344 Avoid large blocks on forced compaction of blocks ingester
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3393 Refactored TSDB opening concurrency at startup
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
Labels: size/L

#3400 chore: designate @jtlisi as v1.6.0 release shepherd
  RELEASE.md
Labels: size/XS

#3371 Blocksconvert: Fix chunks ordering in the block.
  CHANGELOG.md
  tools/blocksconvert/builder/tsdb.go
  tools/blocksconvert/builder/tsdb_test.go
Labels: size/L

#3384 Support for specifying SSL certificates in Cassandra client
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cassandra/storage_client.go
  pkg/chunk/cassandra/storage_client_test.go
  pkg/chunk/cassandra/testdata/example.com-key.pem
  pkg/chunk/cassandra/testdata/example.com.ca.pem
  pkg/chunk/cassandra/testdata/example.com.pem
Labels: size/L

#3406 Fix flaky TestIngester_flushing
  pkg/ingester/ingester_v2_test.go
Labels: size/S

#3409 Update list of talks and articles in the doc
  README.md
  docs/_index.md
  docs/blocks-storage/learn-more.md
Labels: size/M

#3373 Upgrade Prometheus to latest master
  CHANGELOG.md
  go.mod
  go.sum
  integration/e2e/scenario_test.go
  pkg/configs/legacy_promql/functions_test.go
  pkg/ingester/ingester_v2_test.go
  pkg/querier/chunk_tar_test.go
  pkg/querier/querier_test.go
  pkg/ruler/ruler_test.go
  vendor/github.com/prometheus/prometheus/discovery/discovery.go
  vendor/github.com/prometheus/prometheus/discovery/registry.go
  vendor/github.com/prometheus/prometheus/notifier/notifier.go
  vendor/github.com/prometheus/prometheus/pkg/labels/labels.go
  vendor/github.com/prometheus/prometheus/pkg/textparse/interface.go
  vendor/github.com/prometheus/prometheus/promql/parser/generated_parser.y.go
  vendor/github.com/prometheus/prometheus/promql/parser/printer.go
  vendor/github.com/prometheus/prometheus/promql/test.go
  vendor/github.com/prometheus/prometheus/promql/value.go
  vendor/github.com/prometheus/prometheus/rules/alerting.go
  vendor/github.com/prometheus/prometheus/scrape/manager.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/storage/fanout.go
  vendor/github.com/prometheus/prometheus/storage/merge.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/codec.go
  vendor/github.com/prometheus/prometheus/storage/remote/intern.go
  vendor/github.com/prometheus/prometheus/storage/remote/max_timestamp.go
  vendor/github.com/prometheus/prometheus/storage/remote/queue_manager.go
  vendor/github.com/prometheus/prometheus/storage/remote/read.go
  vendor/github.com/prometheus/prometheus/storage/remote/storage.go
  vendor/github.com/prometheus/prometheus/storage/remote/write.go
  vendor/github.com/prometheus/prometheus/template/template.go
  vendor/github.com/prometheus/prometheus/tsdb/README.md
  vendor/github.com/prometheus/prometheus/tsdb/block.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/compact.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/fileutil/mmap.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/index/index.go
  vendor/github.com/prometheus/prometheus/tsdb/querier.go
  vendor/github.com/prometheus/prometheus/tsdb/record/record.go
  vendor/github.com/prometheus/prometheus/tsdb/repair.go
  vendor/github.com/prometheus/prometheus/tsdb/tombstones/tombstones.go
  vendor/github.com/prometheus/prometheus/tsdb/tsdbblockutil.go
  vendor/github.com/prometheus/prometheus/tsdb/wal.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/checkpoint.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/watcher.go
  vendor/github.com/prometheus/prometheus/util/testutil/directory.go
  vendor/github.com/prometheus/prometheus/util/testutil/testing.go
  vendor/github.com/prometheus/prometheus/web/api/v1/api.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/modules.txt
Labels: size/XL

#3415 Start 1.5 release
  CHANGELOG.md
Labels: size/XS

#3417 Cut release 1.5.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#3419 Deploy when running github action on a tag
  .github/workflows/test-build-deploy.yml
Labels: size/XS

#3403 Documented limitations and glossary
  docs/configuration/v1-guarantees.md
  docs/guides/glossary.md
  docs/guides/limitations.md
  docs/production/ingesters-with-wal.md
Labels: size/L

#3412 Expose all TSDB metrics in the ingester
  CHANGELOG.md
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#3388 Expose the config hash as a metric.
  CHANGELOG.md
  integration/alertmanager_test.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/multitenant.go
  pkg/util/metrics_helper.go
Labels: size/M

#3421 Fix alertmanager metrics Describe() ordering
  pkg/alertmanager/alertmanager_metrics.go
Labels: size/XS

#3423 Properly calculate image tag in GitHub Actions
  .github/workflows/test-build-deploy.yml
  Makefile
Labels: size/S

#3425 Intern Prometheus MultiError to solve blocking circular dependency between Cortex and Thanos
  Makefile
  pkg/chunk/table_manager.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor.go
  pkg/ingester/wal.go
  pkg/querier/blocks_scanner.go
  pkg/storegateway/bucket_stores.go
  pkg/util/errors.go
  tools/blocksconvert/builder/series.go
  tools/blocksconvert/builder/series_iterator.go
  tools/blocksconvert/builder/symbols_iterator.go
  tools/blocksconvert/scanner/files.go
Labels: size/L

#3374 Frontend scaling
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/shuffle-sharding.md
  pkg/api/api.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/frontend/config.go
  pkg/querier/frontend/downstream_roundtripper.go
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend_test.go
  pkg/querier/frontend/handler.go
  pkg/querier/frontend/worker.go
  pkg/querier/frontend2/frontend.pb.go
  pkg/querier/frontend2/frontend.proto
  pkg/querier/frontend2/frontend2.go
  pkg/querier/frontend2/frontend2_test.go
  pkg/querier/frontend2/frontend_querier_queues.go
  pkg/querier/frontend2/frontend_querier_queues_test.go
  pkg/querier/frontend2/frontend_scheduler_worker.go
  pkg/querier/frontend2/querier_scheduler_worker.go
  pkg/querier/frontend2/scheduler.go
  pkg/querier/frontend2/scheduler_test.go
  pkg/querier/queryrange/retry.go
  pkg/querier/queryrange/roundtrip.go
  pkg/util/dns_watcher.go
  pkg/util/fakeauth/fake_auth.go
  pkg/util/validation/limits.go
  tools/doc-generator/main.go
Labels: size/XXL
