Repository cortexproject/cortex, pull requests merged in 2020-05, with the labels that each got.

#2550 Add Redis cache options used by Redigo
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/redis_cache.go
Labels: size/M

#2552 Run Grafana Agent in the local dev env too
  development/tsdb-blocks-storage-s3-single-binary/.dockerignore
  development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml
  development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
Labels: size/L

#2557 Don't write empty values to the index.
  pkg/chunk/schema.go
Labels: size/XS

#2542 Design doc - Generalize Module Service
  docs/proposals/generalize-modules.md
Labels: size/M

#2532 Avoid sharding sub-aggregations in `querier.parallelise-shardable-queries`
  pkg/querier/astmapper/parallel.go
  pkg/querier/astmapper/parallel_test.go
  pkg/querier/astmapper/shard_summer_test.go
  pkg/querier/queryrange/promql_test.go
  pkg/querier/queryrange/querysharding_test.go
Labels: size/L

#2556 Documented how to mirror traffic with Envoy
  .circleci/config.yml
  Makefile
  build-image/Dockerfile
  docs/operations/requests-mirroring-envoy.yaml
  docs/operations/requests-mirroring-to-secondary-cluster.md
Labels: size/L

#2566 add registerwithprefix function for thanos objstore configs
  pkg/storage/backend/azure/config.go
  pkg/storage/backend/filesystem/config.go
  pkg/storage/backend/gcs/config.go
  pkg/storage/backend/s3/config.go
Labels: size/M

#2562 Add option to limit concurrent queries to Cassandra.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/chunk/cassandra/storage_client.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: size/M

#2567 Cleanup compactor metrics description
  pkg/compactor/compactor_test.go
  pkg/compactor/syncer_metrics.go
  pkg/compactor/syncer_metrics_test.go
Labels: size/L

#2569 Ignore frontend instance on connect error
  CHANGELOG.md
  pkg/querier/frontend/worker.go
Labels: size/XS

#2570 Refactor Cortex struct as part of Generalising Module Service
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
  pkg/cortex/status.go
Labels: size/L

#2568 Do not prefix Thanos objstore client metrics and fix instrumentation in querier
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  pkg/compactor/compactor.go
  pkg/ingester/ingester_v2.go
  pkg/querier/block.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/bucket_client_test.go
  pkg/storegateway/gateway.go
Labels: size/M

#2564 Update storage-aws.md on obsolete aws tags argument.
  docs/production/storage-aws.md
Labels: size/XS

#2560 Remove experimental tag on WAL
  CHANGELOG.md
  docs/architecture.md
  docs/configuration/v1-guarantees.md
  docs/production/ingesters-with-wal.md
  pkg/ingester/wal.go
Labels: size/XS

#2452 Use newer AWS API for paginated queries
  CHANGELOG.md
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/fixtures.go
  pkg/chunk/aws/mock.go
  pkg/chunk/aws/retryer.go
  pkg/util/backoff.go
  pkg/util/backoff_test.go
Labels: size/L

#2580 Track TSDB appender timing
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
Labels: size/M

#2583 Expose more TSDB metrics from ingesters when running blocks storage
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#2573 Track metric with the last successful blocks sync, scan and compaction
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/querier/blocks_bucket_stores_service.go
  pkg/querier/blocks_bucket_stores_service_test.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
Labels: size/L

#2584 Inject Cortex tracer to Thanos gRPC context
  CHANGELOG.md
  pkg/cortex/cortex.go
Labels: size/M

#2581 Reduces allocations in `GetParallelChunks`.
  pkg/chunk/util/parallel_chunk_fetch.go
  pkg/chunk/util/parallel_chunk_fetch_test.go
Labels: size/M

#2585 Add option to enable TSDB WAL compression
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/ingester/ingester_v2.go
  pkg/storage/tsdb/config.go
Labels: size/S

#2586 Fix memory leak in blocks storage ingesters
  CHANGELOG.md
  pkg/ingester/client/compat.go
  pkg/ingester/client/compat_test.go
Labels: size/M

#2572 TSDB: chunks caching
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  go.mod
  go.sum
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/index_cache_test.go
  pkg/storage/tsdb/memcache_client_config.go
  pkg/storage/tsdb/memcache_client_config_test.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/cache/cache.go
  vendor/github.com/thanos-io/thanos/pkg/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/modules.txt
Labels: size/L

#2579 Prepare release 1.1-rc.0
  CHANGELOG.md
  RELEASE.md
  VERSION
Labels: size/M

#2589 Expose TSDB checkpoint metrics from ingesters
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#2502 Add TLS support to HTTP/GRPC clients
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/production/tls.md
  integration/certs/genCerts.sh
  integration/configs.go
  integration/query_frontend_test.go
  integration/util.go
  pkg/configs/client/client.go
  pkg/configs/client/configs_test.go
  pkg/ingester/client/client.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/querier/frontend/worker.go
  pkg/querier/frontend/worker_frontend_manager.go
  pkg/querier/frontend/worker_frontend_manager_test.go
  pkg/querier/frontend/worker_test.go
  pkg/querier/querier.go
  pkg/querier/store_gateway_client.go
  pkg/querier/store_gateway_client_test.go
  pkg/ruler/ruler.go
  pkg/util/grpcclient/grpcclient.go
  pkg/util/tls/tls.go
Labels: size/XL

#2576 Move signal handling out of Server module.
  go.mod
  go.sum
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/cortex/server_service.go
  pkg/cortex/server_service_test.go
  pkg/util/module_service.go
  vendor/github.com/weaveworks/common/server/server.go
  vendor/modules.txt
Labels: size/M

#2590 Properly fix the wrong logging of 200 when write to client fails
  CHANGELOG.md
  go.mod
  go.sum
  pkg/querier/frontend/frontend.go
  vendor/github.com/weaveworks/common/middleware/logging.go
  vendor/github.com/weaveworks/common/middleware/response.go
  vendor/modules.txt
Labels: size/XS

#2553 Update Query Frontend to use Round Robin for Choosing the Next Queue
  CHANGELOG.md
  pkg/querier/frontend/frontend.go
  pkg/querier/frontend/frontend_queues.go
  pkg/querier/frontend/frontend_queues_test.go
  pkg/querier/frontend/queue_test.go
Labels: size/L

#2587 Automatically forget unhealthy Rulers
  CHANGELOG.md
  pkg/ruler/lifecycle.go
  pkg/ruler/lifecycle_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
Labels: size/L

#2555 support for cancellation of delete requests
  pkg/api/api.go
  pkg/chunk/purger/delete_requests_store.go
  pkg/chunk/purger/purger.go
  pkg/chunk/purger/request_handler.go
Labels: size/M

#2559 Generalise Modules Service to make it extensible
  cmd/cortex/main.go
  cmd/cortex/main_test.go
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
  pkg/util/modules/module_service_wrapper.go
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/XL

#2565 Allow starting ingester in JOINING state to auto join
  CHANGELOG.md
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
Labels: size/M

#2598 Bump test timeout
  tools/test
Labels: size/XS

#2599 Added per-tenant in-process sharding support to compactor
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/compactor/blocks_sharding_filter.go
  pkg/compactor/blocks_sharding_filter_test.go
  pkg/compactor/compactor.go
  pkg/ingester/ingester_v2.go
  pkg/querier/block.go
  pkg/querier/block_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/gateway_test.go
Labels: size/L

#2602 Update Thanos to latest master (with caching bucket changes)
  go.mod
  go.sum
  pkg/storage/tsdb/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_config.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/modules.txt
Labels: size/S

#2600 query-tee: Support metadata, rules and alerts routes
  CHANGELOG.md
  cmd/query-tee/proxy.go
  docs/operations/query-tee.md
  pkg/ruler/storage.go
Labels: size/M

#2613 Prepare release 1.1
  CHANGELOG.md
  RELEASE.md
  VERSION
  docs/production/storage-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
  tools/test
Labels: size/M

#2610 Use Ticker for WAL series spreading
  pkg/ingester/wal.go
Labels: size/XS

#2614 Ensures promql's default evaluation interval is set for the query frontend
  CHANGELOG.md
  pkg/cortex/modules.go
Labels: size/XS

#2618 Remove extra whitespace
  CHANGELOG.md
Labels: size/XS

#2608 pkg/ringkv/etcd: supply WithKeysOnly option in List operation
  pkg/ring/kv/etcd/etcd.go
Labels: size/XS

#2617 Ignore time range in /series request for the blocks storage
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/S

#2623 Decoupled blocks deletion from compaction
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/users_scanner.go
  pkg/compactor/users_scanner_test.go
  pkg/storage/tsdb/bucket_client_mock.go
  pkg/util/services/manager.go
Labels: size/XL

#2621 Update dynamodb provisioning link on changelog
  CHANGELOG.md
Labels: size/XS

#2593 Add blocks storage consistency check in the querier
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  docs/configuration/config-file-reference.md
  pkg/querier/blocks_consistency_checker.go
  pkg/querier/blocks_consistency_checker_test.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/querier/querier.go
  pkg/querier/queryrange/querysharding.go
  pkg/querier/queryrange/querysharding_test.go
  pkg/querier/store_gateway_client.go
  pkg/storegateway/bucket_stores.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/XL

#2609 Add per-tenant max cache freshness to query-frontend
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/querier/queryrange/limits.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/util/validation/limits.go
Labels: size/L

#2605 Fixed Thanos trace propagation
  pkg/cortex/cortex.go
  pkg/querier/blocks_store_queryable.go
Labels: size/M

#2626 Metadata caching
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  docs/operations/blocks-storage.template
  go.mod
  go.sum
  pkg/storage/tsdb/bucket_client_mock.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/caching_bucket_test.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/user_bucket_client.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/gcs/gcs.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/inmem.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/swift/swift.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/testing.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_config.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/modules.txt
Labels: size/L

#2628 Rolledback compactor blocks sharding
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  pkg/compactor/blocks_sharding_filter.go
  pkg/compactor/blocks_sharding_filter_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/label_remover_filter.go
  pkg/compactor/label_remover_filter_test.go
  pkg/storage/tsdb/config.go
Labels: size/L

#2620 Fix remote read route registration
  integration/querier_remote_read_test.go
  pkg/api/api.go
Labels: size/L

#2601 Improve Ruler API Documentation
  docs/apis.md
Labels: size/L

#2571 Translate internal store errors to prometheus API errors.
  integration/e2ecortex/client.go
  integration/querier_test.go
  integration/query_frontend_test.go
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
  pkg/chunk/series_store.go
  pkg/querier/chunk_store_queryable.go
  pkg/querier/chunk_store_queryable_test.go
Labels: size/L

#2632 Finish span created in ingester query stream
  pkg/distributor/query.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
Labels: size/S

#2637 Add more tracing spans to read path
  pkg/querier/distributor_queryable.go
  pkg/querier/querier.go
Labels: size/S

#2633 Micro optimization in newBlockQuerierSeries()
  pkg/querier/block.go
  pkg/querier/block_test.go
Labels: size/M

#2630 Remove upload grace period
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/config-file-reference.md
  pkg/querier/block_meta.go
  pkg/querier/blocks_consistency_checker.go
  pkg/querier/blocks_consistency_checker_test.go
  pkg/querier/blocks_scanner.go
  pkg/querier/blocks_scanner_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/L

#2629 Added Cortex 1.0 and 1.1 to integration test.
  .circleci/config.yml
  integration/backward_compatibility_test.go
Labels: size/M

#2639 cassandra-cql-fixup
  CHANGELOG.md
  pkg/chunk/cassandra/storage_client.go
Labels: size/XS

#2647 Upgrade Prometheus to current master
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/discovery/triton/triton.go
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_other.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks_windows.go
  vendor/modules.txt
Labels: size/XS

#2636 Add extra details to query spans.
  pkg/querier/block.go
  pkg/querier/querier.go
Labels: size/XS

#2654 Exported more TSDB head metrics from ingesters
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#2651 Refcache
  CHANGELOG.md
  pkg/storage/tsdb/ref_cache.go
  pkg/storage/tsdb/ref_cache_test.go
Labels: size/L

#2658 Added benchmarks on blocks storage
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/querier/block_test.go
  pkg/util/test/poll.go
Labels: size/L

#2655 Update thanos and renable tracing
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/operations/blocks-storage.md
  go.mod
  go.sum
  pkg/cortex/cortex.go
  pkg/storage/tsdb/bucket_client.go
  pkg/storage/tsdb/bucket_client_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/block/block.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/json_reader.go
  vendor/github.com/thanos-io/thanos/pkg/cache/tracing_cache.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/streamed_block_writer.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/tracing.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/github.com/thanos-io/thanos/pkg/tracing/tracing.go
  vendor/modules.txt
Labels: size/M

#2642 Do not query blocks store for time ranges already covered by ingesters
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/querier/block_meta.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
Labels: size/L

#2659 Upgrade Prometheus to latest master
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/modules.txt
Labels: size/XS

#2646 Ruler Object Storage Base64 Encoding
  integration/api_ruler_test.go
  pkg/ruler/rules/objectclient/rule_store.go
Labels: size/M
