Repository cortexproject/cortex, pull requests merged in 2021-03, with the labels that each got.

#3887 Refactor rulerstore packages
  Makefile
  integration/chunks_storage_backends_test.go
  pkg/chunk/purger/tenant_deletion_api.go
  pkg/chunk/purger/tenant_deletion_api_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/store.go
  pkg/ruler/rulespb/compat.go
  pkg/ruler/rulespb/rules.pb.go
  pkg/ruler/rulespb/rules.proto
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/bucketclient/bucket_client_test.go
  pkg/ruler/rulestore/config.go
  pkg/ruler/rulestore/configdb/store.go
  pkg/ruler/rulestore/configdb/store_test.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/local/local_test.go
  pkg/ruler/rulestore/objectclient/rule_store.go
  pkg/ruler/rulestore/objectclient/rule_store_test.go
  pkg/ruler/rulestore/store.go
  pkg/ruler/storage.go
  pkg/ruler/store_mock_test.go
Labels: size/XL

#3879 Per-tenant retention periods
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/util/validation/limits.go
Labels: size/L

#3896 compactor: Add a note to know when the migration is done
  docs/blocks-storage/production-tips.md
Labels: size/XS

#3892 Reuse FetcherMetrics from Thanos
  go.mod
  go.sum
  pkg/storegateway/bucket_index_metadata_fetcher.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/chunk_bytes_pool.go
  pkg/storegateway/chunk_bytes_pool_test.go
  pkg/storegateway/metadata_fetcher_filters.go
  pkg/storegateway/metadata_fetcher_filters_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/pool/pool.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/L

#3888 AlertStore: implementation using thanos objstore bucket client
  CHANGELOG.md
  Makefile
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/alertmanager.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/alertmanager_test.go
  integration/configs.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client_test.go
  pkg/alertmanager/alertstore/config.go
  pkg/alertmanager/alertstore/configdb/store.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/alertmanager/alertstore/objectclient/store_test.go
  pkg/alertmanager/alertstore/store.go
  pkg/alertmanager/alertstore/store_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/api/api.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
Labels: size/XXL

#3895 Returning 422 (instead 500) when query hit max_chunks_per_query limit with block storage
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/S

#3894 feat: instrument the query layer to track rate-limited queries
  CHANGELOG.md
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/scheduler.go
Labels: size/M

#3897 Fix missing return after writing sharding error
  pkg/alertmanager/distributor.go
Labels: size/XS

#3898 Optimise alertmanager config loading
  CHANGELOG.md
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/configdb/store.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/local/store_test.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/alertmanager/alertstore/store.go
  pkg/alertmanager/alertstore/store_test.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/ruler/rulestore/store.go
  pkg/util/concurrency/runner.go
  pkg/util/concurrency/runner_test.go
Labels: size/XL

#3889 Stream chunks from blocks-ingester to querier
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
  integration/querier_streaming_mixed_ingester_test.go
  pkg/chunk/encoding/chunk_test.go
  pkg/chunk/encoding/factory.go
  pkg/chunk/encoding/prometheus_chunk.go
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/lifecycle_test.go
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/querier_test.go
Labels: size/XL

#3908 Clarify that chunks WAL is different to blocks
  docs/chunks-storage/ingesters-with-wal.md
Labels: size/XS

#3911 Extracted SSE injection from UserBucketClient into SSEBucketClient
  pkg/compactor/blocks_cleaner.go
  pkg/storage/bucket/sse_bucket_client.go
  pkg/storage/bucket/sse_bucket_client_test.go
  pkg/storage/bucket/user_bucket_client.go
  pkg/storage/bucket/user_bucket_client_test.go
  tools/blocksconvert/builder/builder.go
  tools/thanosconvert/thanosconvert.go
Labels: size/XL

#3905 alertmanager: Avoid breaking /api/v1/alerts if legacy prefix is empty
  CHANGELOG.md
  pkg/api/api.go
Labels: size/S

#3899 Move rules deletion from Purger to Ruler API.
  CHANGELOG.md
  docs/api/_index.md
  pkg/api/api.go
  pkg/chunk/purger/tenant_deletion_api.go
  pkg/chunk/purger/tenant_deletion_api_test.go
  pkg/cortex/modules.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/objectclient/rule_store.go
  pkg/ruler/rulestore/store.go
  pkg/ruler/store_mock_test.go
Labels: size/L

#3906 Added S3 SSE support to alertmanager storage
  CHANGELOG.md
  docs/guides/encryption-at-rest.md
  docs/guides/encryption-at-rest.template
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/store_test.go
Labels: size/M

#3917 Fix ruler API
  pkg/ruler/ruler.go
Labels: size/XS

#3900 Expose deletion of AM config via /multitenant_alertmanager/delete_tenant_config
  CHANGELOG.md
  docs/api/_index.md
  pkg/alertmanager/alertstore/store.go
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/api/api.go
Labels: size/M

#3918 Update changelog to indicate that 1.8 release is in progress.
  CHANGELOG.md
Labels: size/XS

#3839 Alertmanager: Replicate state using the Ring
  go.sum
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanagerpb/alertmanager.pb.go
  pkg/alertmanager/alertmanagerpb/alertmanager.proto
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/XL

#3921 Prepare 1.8.0-rc.0.
  CHANGELOG.md
  VERSION
Labels: size/M

#3916 Ruler: optimised <prefix>/api/v1/rules and <prefix>/api/v1/alerts
  CHANGELOG.md
  integration/configs.go
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/ruler/api_test.go
  pkg/ruler/client_pool.go
  pkg/ruler/client_pool_test.go
  pkg/ruler/ruler.go
Labels: size/L

#3909 Docs: disk space estimate for blocks ingesters
  docs/blocks-storage/_index.md
  docs/blocks-storage/production-tips.md
Labels: size/S

#3923 Chore: rename ring.IngesterState to ring.InstanceState
  pkg/alertmanager/alertmanager_ring.go
  pkg/alertmanager/lifecycle.go
  pkg/alertmanager/multitenant_test.go
  pkg/compactor/compactor.go
  pkg/ingester/ingester_v2_test.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/basic_lifecycler_delegates.go
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ring/basic_lifecycler_test.go
  pkg/ring/lifecycler.go
  pkg/ring/model.go
  pkg/ring/ring.go
  pkg/ring/ring.pb.go
  pkg/ring/ring.proto
  pkg/ring/util.go
  pkg/ruler/lifecycle.go
  pkg/ruler/ruler_ring.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
  pkg/storegateway/gateway_test.go
Labels: size/L

#3928 Skip TestAlertmanagerSharding to unblock Cortex development
  integration/alertmanager_test.go
Labels: size/XS

#3901 Fix queriers shuffle-sharding blast radius containment
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/guides/shuffle-sharding.md
  pkg/frontend/config.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/frontendv1pb/frontend.pb.go
  pkg/frontend/v1/frontendv1pb/frontend.proto
  pkg/frontend/v1/queue_test.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/processor_manager.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
  pkg/querier/worker/worker_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/schedulerpb/scheduler.pb.go
  pkg/scheduler/schedulerpb/scheduler.proto
  pkg/util/active_user.go
Labels: size/XL

#3930 Use BasicService in state_replication.go for replication loop.
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/M

#3915 Removed usage of deprecated pkg/ingester/client stuff
  integration/querier_streaming_mixed_ingester_test.go
  pkg/api/api.go
  pkg/chunk/purger/purger.go
  pkg/cortexpb/compat.go
  pkg/cortexpb/compat_test.go
  pkg/distributor/distributor.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
  pkg/distributor/query.go
  pkg/distributor/query_test.go
  pkg/ingester/client/client_test.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/deprecated.go
  pkg/ingester/client/deprecated_test.go
  pkg/ingester/flush_test.go
  pkg/ingester/index/index.go
  pkg/ingester/index/index_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/label_pairs.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/transfer.go
  pkg/ingester/user_metrics_metadata.go
  pkg/ingester/user_state.go
  pkg/ingester/wal.go
  pkg/ingester/wal_test.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/duplicates_test.go
  pkg/querier/querier_test.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
  pkg/querier/queryrange/queryable_test.go
  pkg/querier/queryrange/querysharding_test.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/series_test.go
  pkg/querier/queryrange/value.go
  pkg/querier/queryrange/value_test.go
  pkg/querier/remote_read.go
  pkg/querier/remote_read_test.go
  pkg/querier/timeseries_series_set.go
  pkg/querier/timeseries_series_set_test.go
  pkg/ruler/api.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/pusher_mock_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/chunkcompat/compat.go
  pkg/util/extract/extract.go
  pkg/util/http_test.go
  pkg/util/push/push.go
  pkg/util/push/push_test.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/XXL

#3931 Pass context to WaitReady of alertmanager Peer interface.
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/state_replication.go
  vendor/github.com/prometheus/alertmanager/cluster/cluster.go
  vendor/github.com/prometheus/alertmanager/notify/notify.go
  vendor/modules.txt
Labels: size/S

#3933 Step down as maintainer
  MAINTAINERS
Labels: size/XS

#3910 Cleanup obsolete local files for alertmanager.
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/rules.yaml
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/api.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#3929 Support memcached max_item_size
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cache/memcached_client.go
Labels: size/M

#3935 Update k8s deps to latest version
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS

#3944 Memcached: Fix comment typos
  pkg/chunk/cache/memcached.go
Labels: size/XS

#3936 Use an interface for callbacks into MultitenantAlertmanager.
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/L

#3940 Remove channel in favour of using Service.AwaitReady.
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/M

#3932 Added local backend support to new ruler storage config
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulespb/custom.go
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/config.go
  pkg/ruler/rulestore/configdb/store.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/objectclient/rule_store.go
  pkg/ruler/rulestore/store.go
  pkg/ruler/storage.go
  pkg/ruler/store_mock_test.go
Labels: size/L

#3948 Revert "Prevent failed ingestion from affecting rate limiting in distributor. (#3825)"
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/limiter/rate_limiter.go
  pkg/util/limiter/rate_limiter_test.go
Labels: size/L

#3943 Fix typo in changelog
  CHANGELOG.md
Labels: size/XS

#3953 Prepare Cortex 1.8-rc.1
  CHANGELOG.md
  VERSION
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/limiter/rate_limiter.go
  pkg/util/limiter/rate_limiter_test.go
Labels: size/L

#3947 Chore: remove ingester naming from ReplicationSet
  pkg/alertmanager/distributor.go
  pkg/alertmanager/multitenant.go
  pkg/compactor/compactor.go
  pkg/distributor/distributor.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/batch.go
  pkg/ring/client/ring_service_discovery.go
  pkg/ring/client/ring_service_discovery_test.go
  pkg/ring/replication_set.go
  pkg/ring/replication_set_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ruler/ruler.go
Labels: size/L

#3945 Deprecate old ruler storage config
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/sharded_ruler.md
  pkg/alertmanager/multitenant.go
  pkg/ruler/ruler.go
  pkg/ruler/storage.go
  tools/doc-generator/main.go
Labels: size/L

#3934 Update Prometheus vendoring
  go.mod
  go.sum
  pkg/api/handlers.go
  pkg/api/queryable_test.go
  pkg/compactor/compactor_test.go
  pkg/configs/legacy_promql/bench_test.go
  pkg/configs/legacy_promql/functions_test.go
  pkg/configs/legacy_promql/test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/querier/querier_test.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/storage/tsdb/ref_cache.go
  pkg/storage/tsdb/ref_cache_test.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway_test.go
  vendor/github.com/prometheus/prometheus/NOTICE
  vendor/github.com/prometheus/prometheus/config/config.go
  vendor/github.com/prometheus/prometheus/discovery/README.md
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/promql/functions.go
  vendor/github.com/prometheus/prometheus/promql/parser/functions.go
  vendor/github.com/prometheus/prometheus/promql/parser/generated_parser.y
  vendor/github.com/prometheus/prometheus/promql/parser/generated_parser.y.go
  vendor/github.com/prometheus/prometheus/promql/parser/lex.go
  vendor/github.com/prometheus/prometheus/promql/parser/printer.go
  vendor/github.com/prometheus/prometheus/promql/test.go
  vendor/github.com/prometheus/prometheus/rules/manager.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/scrape/target.go
  vendor/github.com/prometheus/prometheus/storage/fanout.go
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/storage/memoized_iterator.go
  vendor/github.com/prometheus/prometheus/storage/merge.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/read_handler.go
  vendor/github.com/prometheus/prometheus/storage/remote/sigv4.go
  vendor/github.com/prometheus/prometheus/storage/remote/storage.go
  vendor/github.com/prometheus/prometheus/storage/remote/write.go
  vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
  vendor/github.com/prometheus/prometheus/tsdb/CHANGELOG.md
  vendor/github.com/prometheus/prometheus/tsdb/block.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/tsdbblockutil.go
  vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go
  vendor/github.com/prometheus/prometheus/web/api/v1/api.go
  vendor/modules.txt
Labels: size/XXL

#3924 Querier: streamline tracing spans
  CHANGELOG.md
  pkg/api/handlers.go
  pkg/cortex/modules.go
Labels: size/S

#3958 Allow testing of alertmanager gRPC replication in multitenant_test.go.
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#3967 Improve formatting of timestamp too new/old error
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/user_state.go
  pkg/util/validation/validate.go
Labels: size/S

#3969 Optimize metrics tracking on ingester v2Push() errors
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/L

#3961 Add per-user versions of alertmanager state replication metrics.
  pkg/alertmanager/alertmanager_metrics.go
Labels: size/S

#3972 Propagate error returned from TenantID().
  pkg/alertmanager/multitenant.go
Labels: size/XS

#3970 Check type assertion in alertmanager.go
  pkg/alertmanager/alertmanager.go
Labels: size/XS

#3971 Optimize ingester Push() on blocks storage when the per-user or per-metric series limit is reached
  CHANGELOG.md
  pkg/ingester/errors.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/limiter.go
  pkg/ingester/limiter_test.go
  pkg/ingester/user_metrics_metadata.go
  pkg/ingester/user_state.go
Labels: size/L

#3973 Upgraded Prometheus to further optimize ingester Push() on limits exceeded
  CHANGELOG.md
  go.mod
  go.sum
  pkg/api/handlers.go
  pkg/api/queryable_test.go
  pkg/ruler/compat.go
  vendor/github.com/prometheus/prometheus/pkg/exemplar/exemplar.go
  vendor/github.com/prometheus/prometheus/promql/parser/ast.go
  vendor/github.com/prometheus/prometheus/promql/test.go
  vendor/github.com/prometheus/prometheus/rules/manager.go
  vendor/github.com/prometheus/prometheus/rules/recording.go
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/storage/fanout.go
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/write.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/exemplar.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/util/teststorage/storage.go
  vendor/github.com/prometheus/prometheus/web/api/v1/api.go
  vendor/modules.txt
Labels: size/S

#3959 Fix race condition when opening and closing tsdb concurrently
  CHANGELOG.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/M

#3989 Upgrade Prometheus to pick 8594
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/config/config.go
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/modules.txt
Labels: size/XS

#3964 Small optimization to PrometheusResponse marshalling
  CHANGELOG.md
  pkg/frontend/transport/roundtripper.go
  pkg/querier/queryrange/marshaling_test.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
Labels: size/L

#3985 docs: default to blocks for getting started
  README.md
  docs/_index.md
  docs/case-studies/buoyant-cloud.md
  docs/chunks-storage/_index.md
  docs/chunks-storage/chunks-storage-getting-started.md
  docs/chunks-storage/running-chunks-storage-in-production.md
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  docs/getting-started/_index.md
  docs/getting-started/getting-started-blocks.md
  docs/guides/gossip-ring-getting-started.md
Labels: size/L

#3893 Expand instructions on scaling up
  docs/guides/ingesters-scaling-up-and-down.md
Labels: size/XS

#3990 Optimize distributor push on error
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/validation/errors.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/XL

#3981 Use path.Join to concatenate prefix and folder string (#2643)
  pkg/api/api.go
  pkg/api/handlers.go
Labels: size/L

#3977 fix issue where we are not returning all the available ingesters in the ring
  CHANGELOG.md
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/M

#3956 Update README.md
  README.md
  docs/_index.md
Labels: size/XS

#3999 Ignore objects with names that end with / when listing rule groups
  CHANGELOG.md
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/bucketclient/bucket_client_test.go
Labels: size/M

#4001 Optimized metric name extraction in distributor
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/extract/extract.go
  pkg/util/validation/validate.go
Labels: size/M

#4002 Deprecated old alertmanager storage config
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertstore/config.go
  pkg/alertmanager/multitenant.go
  tools/doc-generator/main.go
Labels: size/L

#3925 Implement gRPC based initial state settling in alertmanager.
  integration/alertmanager_test.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerpb/alertmanager.pb.go
  pkg/alertmanager/alertmanagerpb/alertmanager.proto
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
  pkg/ring/replication_set.go
  pkg/ring/replication_set_test.go
Labels: size/XL

#4003 Prepare Cortex 1.8.0 (final) release.
  CHANGELOG.md
  RELEASE.md
  VERSION
  docs/guides/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#3991 Added CHANGELOG entry for PromQL engine optimizations
  CHANGELOG.md
Labels: size/XS

#3891 blocksconvert: optionally reduce timestamp jitter
  CHANGELOG.md
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/builder/tsdb.go
  tools/blocksconvert/builder/tsdb_test.go
Labels: size/M

#4005 Apply review comments consistently to alertmanager/multitenant.go
  pkg/alertmanager/multitenant.go
Labels: size/S

#4006 Merge release-1.8 branch to master
  CHANGELOG.md
  RELEASE.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#4008 Add Cortex 1.8.0 to backward_compatibility_test.go.
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#4007 Update release document on merging release branch to master
  RELEASE.md
Labels: size/S

#4004 chore: update documentation to use new API paths
  development/tsdb-blocks-storage-s3-gossip/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3-gossip/config/prometheus.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/config/grafana-agent.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-swift-single-binary/config/grafana-agent.yaml
  development/tsdb-blocks-storage-swift-single-binary/config/prometheus.yaml
  docs/chunks-storage/aws-tips.md
  docs/chunks-storage/chunks-storage-getting-started.md
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  docs/configuration/v1-guarantees.md
  docs/getting-started/_index.md
  docs/guides/gossip-ring-getting-started.md
  docs/operations/query-auditor.md
  k8s/alertmanager-dep.yaml
  k8s/nginx-config.yaml
  k8s/retrieval-config.yaml
  k8s/ruler-dep.yaml
  tools/query-audit/example-config.yaml
Labels: size/M

#4013 fix: ensure ruler returns 404 when getting missing rule group
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/ruler/api.go
Labels: size/S

#4019 Fix Makefile dependency for alerts.proto.
  Makefile
Labels: size/XS

#4023 chore: mark implemnted proposals accepted
  docs/proposals/scalable-alertmanager.md
  docs/proposals/shuffle-sharding-and-zone-awareness.md
  docs/proposals/tenant-deletion.md
Labels: size/XS

#4009 Fixed typo
  docs/architecture.md
Labels: size/XS

#4015 Fix issue where some test generate test data under src directory
  pkg/alertmanager/multitenant_test.go
  pkg/querier/querier_test.go
Labels: size/S

#4011 Fix bad link to HTTP API docs from ruler guide
  docs/guides/sharded_ruler.md
Labels: size/XS

#4017 fix: ensure ruler forwards alerts with proper EndsAt
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/M

#3968 Fix issue where cached entry size keeps increasing when making tiny query repeatedly
  CHANGELOG.md
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/L

#4024 Disable alertmanager sharding tests.
  integration/alertmanager_test.go
  pkg/alertmanager/multitenant_test.go
Labels: size/XS

#4025 No need to check alert state in sendAlerts()
  pkg/ruler/ruler.go
Labels: size/XS

#3975 Add Retries to Sync Blocks
  pkg/storegateway/bucket_stores.go
Labels: size/S

#4020 Extend alertstore to support read/write of clusterpb.FullState.
  pkg/alertmanager/alertspb/alerts.pb.go
  pkg/alertmanager/alertspb/alerts.proto
  pkg/alertmanager/alertspb/compat.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/configdb/store.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/alertmanager/alertstore/store.go
  pkg/alertmanager/alertstore/store_test.go
Labels: size/L

#4018 Put metric before label value in the "label value too long" error mes…
  CHANGELOG.md
  pkg/util/validation/errors.go
Labels: size/S

#3951 Reduce ingester memory by using TSDB's index
  CHANGELOG.md
  go.mod
  go.sum
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/ref_cache.go
  pkg/storage/tsdb/ref_cache_test.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/github.com/prometheus/prometheus/NOTICE
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/modules.txt
Labels: size/XL

#4027 Use model.Duration for -compactor.blocks-retention-period.
  CHANGELOG.md
  pkg/util/validation/limits.go
Labels: size/XS

#4029 Remove error return value, which was always nil.
  pkg/ingester/ingester_v2.go
Labels: size/S
