Repository cortexproject/cortex, pull requests merged in 2021-05, with the labels that each got.

#4152 Update Prometheus to latest
  go.mod
  go.sum
  pkg/querier/queryrange/promql_test.go
  vendor/github.com/prometheus/prometheus/config/config.go
  vendor/github.com/prometheus/prometheus/discovery/README.md
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/rules/manager.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/modules.txt
Labels: size/XS

#4156 Supress counting not-found as an error when reading alertmanager state.
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
Labels: size/XS

#4154 Specify hints to TSDB querier when querying series
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/M

#4157 Expire long-running e2e containers in Drone CI
  integration/e2e/service.go
Labels: size/XS

#4087 Simplify unit tests runner
  Makefile
  tools/test
Labels: size/L

#4149 First cut at metrics for alertmanager sharding operation.
  CHANGELOG.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/state_persister.go
  pkg/alertmanager/state_persister_test.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/L

#4117 Make mergeQueryable more generically usable
  pkg/cortex/modules.go
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
Labels: size/L

#4128 purger: fix nil value in column range for BatchWrite query
  CHANGELOG.md
  pkg/chunk/purger/delete_requests_store.go
Labels: size/XS

#4151 Distributors rings status
  CHANGELOG.md
  docs/api/_index.md
  pkg/api/api.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_ring.go
  pkg/distributor/distributor_test.go
  pkg/ruler/ruler.go
  pkg/util/http.go
Labels: size/M

#4124 Support ingesting exemplars into TSDB when blocks storage is enabled
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/cortexpb/cortex.pb.go
  pkg/cortexpb/cortex.proto
  pkg/cortexpb/timeseries.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
  pkg/storage/tsdb/config.go
  pkg/util/http_test.go
  pkg/util/validation/errors.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/XL

#4135 Alertmanager: Rate limit email notifier
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/alertmanager/rate_limited_notifier.go
  pkg/alertmanager/rate_limited_notifier_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#4168 Change default values for gRPC keepalive ping options.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
Labels: size/M

#3828 Implement blocksconvert scanner for DynamoDB v9 schema
  CHANGELOG.md
  docs/blocks-storage/convert-stored-chunks-to-blocks.md
  pkg/chunk/aws/dynamodb_index_reader.go
  pkg/chunk/index_reader.go
  tools/blocksconvert/scanner/bigtable_index_reader.go
  tools/blocksconvert/scanner/scanner.go
  tools/blocksconvert/scanner/scanner_processor.go
Labels: size/L

#4173 Add IsModuleRegistered method to modules.Manager
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/S

#4164 Don't force amd64 arch when building docker image for development
  development/tsdb-blocks-storage-s3-gossip/compose-up.sh
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/compose-up.sh
  development/tsdb-blocks-storage-s3/compose-up.sh
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/compose-up.sh
Labels: size/S

#4185 Cut final 1.9.0 release
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/S

#4114 doc:Add to block=storage and create alert-manager configuration docum…
  docs/blocks-storage/_index.md
  docs/guides/alert-manager-configuration.md
Labels: size/M

#4196 Merge release 1.9 to master
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#3795 Add Cassandra support to blocksconvert
  pkg/chunk/cassandra/storage_client.go
  tools/blocksconvert/scanner/cassandra_index_reader.go
  tools/blocksconvert/scanner/scanner.go
Labels: size/L

#4188 scanner: Retry failed uploads
  tools/blocksconvert/scanner/scanner.go
Labels: size/S

#4197 Add release 1.9 to the backwards compat matrix
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#4163 Extend alertmanager limits to cover all integrations.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  pkg/util/validation/notifications_limit_flag.go
  pkg/util/validation/notifications_limit_flag_test.go
Labels: size/L

#4198 Schedule next Cortex releases
  RELEASE.md
Labels: size/XS

#4179 Add support for Max Series Per Query for block storage and streaming ingesters
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
  pkg/util/limiter/query_limiter.go
  pkg/util/limiter/query_limiter_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4186 #4147 added `tenant_id` tag to tracing spans
  CHANGELOG.md
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
  pkg/util/spanlogger/spanlogger.go
  pkg/util/spanlogger/spanlogger_test.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mocklogrecord.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mockspan.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/mocktracer.go
  vendor/github.com/opentracing/opentracing-go/mocktracer/propagation.go
  vendor/modules.txt
Labels: size/L

#4209 Update email address of Bryan Boreham as maintainer
  MAINTAINERS
Labels: size/XS

#4212 Update remote write protobuf definition location
  docs/api/_index.md
Labels: size/XS

#4182 Fixe #4177: mockRuleStore require LoadRuleGroups, and fix ListAllRules
  CHANGELOG.md
  pkg/ruler/ruler.go
  pkg/ruler/store_mock_test.go
Labels: size/M

#4200 return ErrStorageObjectNotFound when object requested for download is not found in Azure blob storage
  pkg/chunk/azure/blob_storage_client.go
Labels: size/S

#4215 Upgrade the go version used in integration tests
  .github/workflows/test-build-deploy.yml
Labels: size/XS

#4165 Build image now supports linux/arm64 as well
  .github/workflows/test-build-deploy.yml
  Makefile
  build-image/Dockerfile
  docs/contributing/how-to-update-the-build-image.md
Labels: size/M

#4201 Added limit for size of configuration file that tenant can upload to Alertmanager.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/validation/limits.go
Labels: size/M

#4223 Alertmanager template limits.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4221 return ErrStorageObjectNotFound when a non-existent object is being deleted
  pkg/chunk/azure/blob_storage_client.go
Labels: size/XS

#4220 Add integration test for scaling alertmanager with sharding enabled.
  integration/alertmanager_test.go
  integration/configs.go
Labels: size/L

#4230 Add missing return statement in memberlist code.
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/XS

#4219 Add the ability to disable OpenCensus within GCS client.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/gcp/gcs_object_client.go
Labels: size/M

#4225 Make handler function for `/config` endpoint overrideable
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
Labels: size/M

#4227 Honor eval delay for ALERTS series
  CHANGELOG.md
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
Labels: size/M

#4216 Add max-chunks-bytes-per-query limiter
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor_test.go
  pkg/distributor/ha_tracker_test.go
  pkg/distributor/query.go
  pkg/ingester/client/custom.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
  pkg/util/limiter/query_limiter.go
  pkg/util/limiter/query_limiter_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4184 Fix status page if cluster is disabled or sharding is enabled
  CHANGELOG.md
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/alertmanager_http.go
  pkg/alertmanager/alertmanager_http_test.go
  pkg/alertmanager/multitenant.go
Labels: size/L

#4222 Add changelog for alertmanager sharding and add experimental warning log.
  CHANGELOG.md
  pkg/alertmanager/multitenant.go
Labels: size/XS

#4211 Build arm64 binaries and packages
  Makefile
  tools/packaging/test-packages
Labels: size/L
