Repository cortexproject/cortex, pull requests merged in 2021-11, with the labels that each got.

#4545 Disable S3 SSE integration tests
  integration/s3_storage_client_test.go
Labels: size/XS

#4541 Update affiliation of Bryan Boreham in Maintainers list
  MAINTAINERS
Labels: size/XS

#4547 Run local KES for S3 integration tests
  integration/certs.go
  integration/e2e/db/db.go
  integration/e2e/images/images.go
  integration/s3_storage_client_test.go
Labels: size/L

#4522 Enhance: redis MSet check the length of keys and values is equal
  pkg/chunk/cache/redis_client.go
Labels: size/XS

#4553 Add northflank to the list of adopters
  ADOPTERS.md
  website/data/adopters.yml
  website/static/logos/northflank.svg
Labels: size/XS

#4558 Update Jacob Lisi entry in MAINTAINERS file
  MAINTAINERS
Labels: size/XS

#4486 Preserve requests headers in PrometheusCodec
  CHANGELOG.md
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  docs/configuration/prometheus-frontend.md
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
  pkg/querier/queryrange/queryrange.pb.go
  pkg/querier/queryrange/queryrange.proto
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/split_by_interval_test.go
Labels: size/M

#4567 Release v1.11.0
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
Labels: size/S

#4569 Merge release 1.11 to master
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
Labels: size/S
