Repository cortexproject/cortex, pull requests merged in 2021-06, with the labels that each got.

#4032 Use non APIPA when assigning IP Address
  CHANGELOG.md
  pkg/util/net.go
Labels: size/M

#4231 Add new metrics to aid troubleshooting tombstone convergence.
  CHANGELOG.md
  integration/integration_memberlist_single_binary_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/ring/kv/memberlist/mergeable.go
  pkg/ring/kv/memberlist/metrics.go
  pkg/ring/model.go
Labels: size/M

#4240 Replace validation error with error in query limiter
  integration/querier_test.go
  pkg/distributor/query.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/util/limiter/query_limiter.go
Labels: size/S

#4243 Clarify limits flags
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/S

#4249 nit: fix typo in metric variable name
  pkg/distributor/ha_tracker.go
Labels: size/XS

#4244 Added target to fetch build image, instead of building it locally.
  Makefile
  docs/contributing/how-to-update-the-build-image.md
Labels: size/S

#4246 Ensure missing runtime ingester settings are nil
  CHANGELOG.md
  pkg/cortex/runtime_config.go
  pkg/cortex/runtime_config_test.go
Labels: size/S

#4251 Fixed regression introduced in #4240
  integration/querier_test.go
  pkg/distributor/query.go
Labels: size/XS

#4252 Fix ruler storage single binary mode
  CHANGELOG.md
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
  docs/configuration/single-process-config.md
  docs/configuration/single-process-config.yaml
  integration/ruler_test.go
  pkg/cortex/modules.go
  pkg/cortex/modules_test.go
  pkg/ruler/rulestore/config.go
  pkg/ruler/rulestore/config_test.go
Labels: size/L

#4237 Update Alertmanager to latest master (f686ff3be2bf).
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  vendor/github.com/go-openapi/runtime/.gitattributes
  vendor/github.com/go-openapi/runtime/.golangci.yml
  vendor/github.com/go-openapi/runtime/.travis.yml
  vendor/github.com/go-openapi/runtime/bytestream.go
  vendor/github.com/go-openapi/swag/.golangci.yml
  vendor/github.com/hashicorp/memberlist/event_delegate.go
  vendor/github.com/hashicorp/memberlist/state.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/github.com/jessevdk/go-flags/.travis.yml
  vendor/github.com/jessevdk/go-flags/README.md
  vendor/github.com/jessevdk/go-flags/check_crosscompile.sh
  vendor/github.com/jessevdk/go-flags/command.go
  vendor/github.com/jessevdk/go-flags/completion.go
  vendor/github.com/jessevdk/go-flags/convert.go
  vendor/github.com/jessevdk/go-flags/error.go
  vendor/github.com/jessevdk/go-flags/flags.go
  vendor/github.com/jessevdk/go-flags/go.mod
  vendor/github.com/jessevdk/go-flags/go.sum
  vendor/github.com/jessevdk/go-flags/group.go
  vendor/github.com/jessevdk/go-flags/help.go
  vendor/github.com/jessevdk/go-flags/ini.go
  vendor/github.com/jessevdk/go-flags/man.go
  vendor/github.com/jessevdk/go-flags/option.go
  vendor/github.com/jessevdk/go-flags/parser.go
  vendor/github.com/jessevdk/go-flags/termsize.go
  vendor/github.com/jessevdk/go-flags/termsize_nosysioctl.go
  vendor/github.com/jessevdk/go-flags/termsize_windows.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_bsdish.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_linux.go
  vendor/github.com/jessevdk/go-flags/tiocgwinsz_other.go
  vendor/github.com/prometheus/alertmanager/asset/assets_vfsdata.go
  vendor/github.com/prometheus/alertmanager/config/config.go
  vendor/github.com/prometheus/alertmanager/dispatch/dispatch.go
  vendor/github.com/prometheus/alertmanager/provider/mem/mem.go
  vendor/github.com/prometheus/alertmanager/provider/provider.go
  vendor/github.com/prometheus/alertmanager/ui/Dockerfile
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/github.com/prometheus/common/model/labels.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/write.go
  vendor/modules.txt
Labels: size/L

#4256 Mark new querier limits as experimental
  docs/configuration/v1-guarantees.md
Labels: size/XS

#4257 Enable active series metrics in the ingester by default
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
Labels: size/XS

#4263 Fix queries failing right after scaling up store-gateways
  CHANGELOG.md
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/storegateway/gateway_ring.go
Labels: size/S

#4254 Dispatcher groups limits
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4253 Alertmanager alerts limits
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4269 Fix default memberlist configuration value for RetransmitMult.
  CHANGELOG.md
  integration/integration_memberlist_single_binary_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/L

#4271 Add "wait ring stability" to store-gateway and fix cold start issue
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  integration/e2ecortex/services.go
  integration/getting_started_with_gossiped_ring_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_ring.go
  pkg/storegateway/bucket_store_inmemory_server.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
  pkg/storegateway/gateway_ring_test.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/sharding_strategy.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/XL

#4181 exemplar querying
  CHANGELOG.md
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/prometheus.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/api/_index.md
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/cortexpb/compat.go
  pkg/distributor/distributor.go
  pkg/distributor/query.go
  pkg/distributor/query_test.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/L

#4277 Filter LabelValues calls with matchers
  CHANGELOG.md
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
Labels: size/M

#4281 New ruler alerts that ignore user-errors
  CHANGELOG.md
  pkg/api/handlers.go
  pkg/cortex/modules.go
  pkg/querier/error_translate_queryable.go
  pkg/querier/error_translate_queryable_test.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/ruler_test.go
Labels: size/L

#4205 Added etcd username and userpassword from config
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/etcd/etcd.go
Labels: size/S

#4286 Chore: fix chunkenc.Iterator comment
  pkg/querier/batch/batch.go
  pkg/querier/iterators/chunk_merge_iterator.go
Labels: size/S

#4285 Bump Ubuntu to 20.04 in CI
  .github/workflows/test-build-deploy.yml
Labels: size/S

#4268 Deprecated Cortex chunks storage
  CHANGELOG.md
  Makefile
  README.md
  build-image/Dockerfile
  docs/_index.md
  docs/architecture.md
  docs/chunks-storage/_index.md
  docs/chunks-storage/aws-tips.md
  docs/chunks-storage/caching.md
  docs/chunks-storage/chunks-storage-getting-started.md
  docs/chunks-storage/ingesters-with-wal.md
  docs/chunks-storage/running-chunks-storage-in-production.md
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  docs/chunks-storage/schema-config.md
  docs/chunks-storage/table-manager.md
  docs/configuration/arguments.md
  docs/guides/deleting-series.md
  docs/guides/encryption-at-rest.md
  docs/guides/encryption-at-rest.template
  docs/guides/glossary.md
  docs/guides/grpc-storage-plugin.md
  docs/guides/ingesters-rolling-updates.md
  k8s/alertmanager-dep.yaml
  k8s/alertmanager-svc.yaml
  k8s/configs-db-dep.yaml
  k8s/configs-db-svc.yaml
  k8s/configs-dep.yaml
  k8s/configs-svc.yaml
  k8s/consul-dep.yaml
  k8s/consul-svc.yaml
  k8s/distributor-dep.yaml
  k8s/distributor-svc.yaml
  k8s/dynamodb-dep.yaml
  k8s/dynamodb-svc.yaml
  k8s/ingester-dep.yaml
  k8s/ingester-svc.yaml
  k8s/memcached-dep.yaml
  k8s/memcached-svc.yaml
  k8s/nginx-config.yaml
  k8s/nginx-dep.yaml
  k8s/nginx-svc.yaml
  k8s/querier-dep.yaml
  k8s/querier-svc.yaml
  k8s/query-frontend-dep.yaml
  k8s/query-frontend-svc.yaml
  k8s/retrieval-config.yaml
  k8s/retrieval-dep.yaml
  k8s/retrieval-svc.yaml
  k8s/ruler-dep.yaml
  k8s/ruler-svc.yaml
  k8s/s3-dep.yaml
  k8s/s3-svc.yaml
  k8s/schema-config.yaml
  k8s/table-manager-dep.yaml
  k8s/table-manager-svc.yaml
Labels: size/XL

#4294 Updated doc about chunks storage deprecation
  docs/configuration/arguments.md
  docs/configuration/config-file-reference.md
  pkg/chunk/storage/factory.go
Labels: size/XS

#4264 docs: added alertmanager_storage docs
  docs/guides/alert-manager-configuration.md
Labels: size/XS

#4302 Added option to ignore specific metrics when checking max-series-per-metric limit.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/user_state.go
  pkg/ingester/user_state_test.go
Labels: size/L

#4298 Add ability to support strict JSON unmarshal for `limits`
  CHANGELOG.md
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/S

#4297 chore: Define interface api.Distributor
  pkg/api/api.go
  pkg/api/handlers.go
Labels: size/S

#4306 Fixed 'wait ring stability' log
  pkg/compactor/compactor.go
  pkg/storegateway/gateway.go
Labels: size/XS

#4305 Fix TestStoreGateway_InitialSyncWithWaitRingStability flakyness
  pkg/storegateway/gateway_test.go
Labels: size/XS

#4312 Expose some ruler types to ease reuse.
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
Labels: size/S

#4258 Fix flakey MaxChunkBytesPerQueryLimit test
  pkg/distributor/distributor_test.go
Labels: size/S

#3976 RedisCache: Use CollectedRequest
  CHANGELOG.md
  pkg/chunk/cache/cache.go
  pkg/chunk/cache/redis_cache.go
  pkg/chunk/cache/redis_cache_test.go
Labels: size/M

#4320 Prepare release 1.10
  CHANGELOG.md
  RELEASE.md
Labels: size/S

#4315 Fix any should be all in docs/architecture.md
  docs/architecture.md
Labels: size/XS

#4260 max chunks per query limit shared between ingesters and storage gateways
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
  pkg/util/limiter/query_limiter.go
  pkg/util/limiter/query_limiter_test.go
  pkg/util/validation/limits.go
Labels: size/L
