Repository cortexproject/cortex, pull requests merged in 2021-04, with the labels that each got.

#4037 doc: Add note about use of curl for experimental Alertmanager API
  docs/api/_index.md
Labels: size/XS

#4044 Convert all validation.Limits durations to model.Duration
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/chunk_store_test.go
  pkg/chunk/testutils/testutils.go
  pkg/cortex/modules.go
  pkg/distributor/distributor_test.go
  pkg/querier/querier_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#4042 chore: update Dockerfiles to use Alpine 3.13
  CHANGELOG.md
  cmd/blocksconvert/Dockerfile
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
Labels: size/S

#4021 Read alertmanager state from storage if peer settling fails.
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/M

#4049 Update capacity planning guide for WAL replay and resharding effects on ingester
  docs/guides/capacity-planning.md
Labels: size/XS

#4026 Small optimization to avoid unnecessary Extents merge when growing cache entry
  CHANGELOG.md
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/M

#4048 Use enums to represent the clients (#1395)
  pkg/chunk/storage/factory.go
Labels: size/M

#4040 Add a metric for the compaction interval config value.
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/S

#3616 Small fix for off-by-one rules limit enforcement
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/ruler.go
Labels: size/M

#4031 Implement periodic writing of alertmanager state to storage.
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/alertmanager/state_persister.go
  pkg/alertmanager/state_persister_test.go
Labels: size/L

#3992 Ingester bounds
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/instance_limits.go
  pkg/ingester/instance_limits_test.go
  pkg/ingester/metrics.go
  pkg/ingester/rate.go
Labels: size/XL

#4066 Querier can now notify about its shutdown without providing any authentication in the context.
  CHANGELOG.md
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
Labels: size/L

#4062 chore: update Go to use Go1.16
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  build-image/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  go.mod
  go.sum
Labels: size/S

#4046 Add memberlist TLS configuration options
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/integration_memberlist_single_binary_test.go
  pkg/ring/kv/memberlist/tcp_transport.go
Labels: size/L

#4070 Move ewmaRate into util/math package, and make it public.
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/ingester/user_state.go
  pkg/util/math/rate.go
  pkg/util/math/rate_test.go
Labels: size/L

#4068 Fixed race condition causing queries to fail right after querier startup with the "empty ring" error
  CHANGELOG.md
  integration/e2ecortex/services.go
  integration/ruler_test.go
  pkg/ring/ring.go
Labels: size/L

#4074 Ruler ignore users
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/allowed_tenants.go
  pkg/util/allowed_tenants_test.go
Labels: size/L

#4077 Remove ReportWriteToErrors field.
  pkg/ring/kv/memberlist/tcp_transport.go
Labels: size/S

#4073 Ingester can now flush only specified users.
  CHANGELOG.md
  docs/api/_index.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/util/allowed_tenants.go
  pkg/util/allowed_tenants_test.go
Labels: size/L

#4078 Fix TestAlertmanager_StateReplicationWithSharding.
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#4071 Distributor limits
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/instance_limits.go
  pkg/ingester/metrics.go
Labels: size/L

#4083 Fix TestAlertmanagerSharding integration test.
  integration/alertmanager_test.go
Labels: size/S

#4069 Allow configuration of Cassandra's host selection policy
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/chunk/cassandra/storage_client.go
Labels: size/S

#4084 Add minimal support for missing routes in alertmanager distributor.
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/multitenant_test.go
Labels: size/XL

#4036 Update roadmap for 2021
  docs/roadmap.md
Labels: size/S

#4081 Validate configured -alertmanager.web.external-url and fail if ends with /
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3-gossip/docker-compose.yml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/rules.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/M

#4038 Update distributors CPU usage in capacity planning doc
  docs/guides/capacity-planning.md
Labels: size/XS

#4088 Fix retries on store-gateway initial sync failure
  CHANGELOG.md
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
Labels: size/M

#4092 [compactor] Run blocks cleaner before ring ready.
  pkg/compactor/compactor.go
Labels: size/S

#4094 Increment cortex_compactor_runs_failed_total if compactor fails to compact a single tenant
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/M

#4091 Expand endpoint testing in alertmanager integration test.
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
Labels: size/L

#3529 add api to list all alertmanager configs and rule groups
  CHANGELOG.md
  docs/api/_index.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/api/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/http.go
  pkg/util/http_test.go
Labels: component/alertmanager, size/L

#4096 Mark instance limits as experimental.
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
  pkg/distributor/distributor.go
  pkg/ingester/ingester_v2.go
Labels: size/S

#3904 alertmanager/ruler: Include affected path upon config access failure
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/objectclient/rule_store.go
Labels: size/M

#4099 Update to latest github.com/weaveworks/common
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/weaveworks/common/middleware/counting_listener.go
  vendor/github.com/weaveworks/common/middleware/instrument.go
  vendor/github.com/weaveworks/common/server/server.go
  vendor/modules.txt
Labels: size/XS

#4103 Fix docker port parsing in integration tests
  integration/e2e/service.go
  integration/e2e/service_test.go
Labels: size/M

#4101 Remove config options deprecated in Cortex 1.6
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/chunk_store.go
  pkg/chunk/chunk_store_test.go
  pkg/cortex/modules.go
  pkg/frontend/config.go
  pkg/storage/tsdb/index_cache.go
Labels: size/L

#4112 Remove deprecated options for setting runtime config file and reload period.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/util/validation/limits.go
Labels: size/S

#4085 Add firewall support to http based alertmanager receiver integrations
  CHANGELOG.md
  docs/blocks-storage/production-tips.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/firewall.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/util/flagext/cidr.go
  pkg/util/flagext/cidr_test.go
  pkg/util/net/firewall_dialer.go
  pkg/util/net/firewall_dialer_test.go
  tools/doc-generator/parser.go
Labels: size/XL

#4110 Fix for alertmanagers not configuring users before becoming ACTIVE.
  pkg/alertmanager/alertmanager_ring.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/S

#4105 Using git to determine cortex project dir for integration tests
  integration/util.go
Labels: size/XS

#4111 stop the index search early based on query params
  pkg/chunk/local/boltdb_index_client.go
Labels: size/XS

#4120 Try to fix TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flakyness
  pkg/alertmanager/multitenant_test.go
Labels: size/S

#4116 doc: Fix formatting of environment variable list
  docs/contributing/how-integration-tests-work.md
Labels: size/XS

#4119 Allow to configure min/max bucket size for the store-gateway chunks pool
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/chunk_bytes_pool.go
  pkg/storegateway/chunk_bytes_pool_test.go
Labels: size/M

#4065 Add concurrency to the mergeQueryable
  CHANGELOG.md
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
  pkg/util/concurrency/runner.go
  pkg/util/concurrency/runner_test.go
Labels: size/L

#4129 Fix for CVE-2021-31232: Alertmanager can expose local files content via specially crafted config
  CHANGELOG.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/XL

#4130 Fix docker port parsing in integration tests (#4103)
  integration/e2e/service.go
  integration/e2e/service_test.go
Labels: size/M

#4131 Fix docker port parsing in integration tests (#4103)
  integration/e2e/service.go
  integration/e2e/service_test.go
Labels: size/M

#4132 Merge release 1.8 branch
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
  pkg/alertmanager/api_test.go
Labels: size/M

#4126 Implement quorum reads and response merging for /v1/alerts.
  integration/alertmanager_test.go
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/merger/merger.go
  pkg/alertmanager/merger/v1_alerts.go
  pkg/alertmanager/merger/v1_alerts_test.go
Labels: size/L

#4134 Hot fix to avoid process to block indefinitely on shutdown
  CHANGELOG.md
  cmd/cortex/main.go
Labels: size/XS

#4133 Update Thanos to latest and use label matchers in LabelValues call.
  CHANGELOG.md
  go.mod
  go.sum
  integration/e2ecortex/client.go
  integration/getting_started_single_process_config_test.go
  integration/querier_test.go
  pkg/querier/blocks_store_queryable.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/header.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.proto
  vendor/modules.txt
Labels: size/M

#4137 Update changelog for 1.9 release in progress.
  CHANGELOG.md
Labels: size/XS

#4122 Fix TestStreamWriteYAMLResponse flakyness
  pkg/util/http_test.go
Labels: size/XS

#4127 Implement quorum reads and merging for /v2/alerts and /v2/alerts/groups.
  go.mod
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/merger/v2_alert_groups.go
  pkg/alertmanager/merger/v2_alert_groups_test.go
  pkg/alertmanager/merger/v2_alerts.go
  pkg/alertmanager/merger/v2_alerts_test.go
  vendor/modules.txt
Labels: size/XL

#4125 Enforce "max chunks per query" limit in ingesters too
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-gossip/config/runtime.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/runtime.yaml
  development/tsdb-blocks-storage-s3/config/runtime.yaml
  docs/configuration/config-file-reference.md
  pkg/chunk/chunk_store.go
  pkg/chunk/composite_store.go
  pkg/chunk/series_store.go
  pkg/chunk/storage/factory.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/custom.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/gateway_test.go
  pkg/util/labels.go
  pkg/util/labels_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#4140 Add logs to investigate TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flaky in CI
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/S

#4139 Prepare 1.9.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/S

#4143 Allow to override Alertmanager receivers firewall settings on a per-tenant basis
  CHANGELOG.md
  docs/blocks-storage/production-tips.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/firewall.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/cortex/modules.go
  pkg/util/net/firewall_dialer.go
  pkg/util/net/firewall_dialer_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4121 Make iterations metric per rule_group
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
Labels: size/M

#4144 Optimized getMetricsWithLabelNames() helper
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/M, type/performance

#4145 Upgrade prometheus/common and disallow new OAuth2 client_secret_file in Alertmanager
  go.mod
  go.sum
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: size/M

#4141 Implement quorum reads and merging for /v2/silences and /v2/silence/id
  integration/alertmanager_test.go
  integration/e2ecortex/client.go
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/merger/v2_silence_id.go
  pkg/alertmanager/merger/v2_silence_id_test.go
  pkg/alertmanager/merger/v2_silences.go
  pkg/alertmanager/merger/v2_silences_test.go
Labels: size/L

#4148 prevent not found objects from incrementing thanos_objstore_bucket_operation_failures_total during deletion marker migration
  pkg/storage/tsdb/bucketindex/markers.go
  pkg/storage/tsdb/bucketindex/markers_test.go
Labels: size/M

#4150 Fixed TestMultitenantAlertmanager_FirewallShouldBlockHTTPBasedReceiversWhenEnabled flakyness
  pkg/alertmanager/multitenant_test.go
Labels: size/XS

#4146 Implement quorum reads and merging for /v1/silences and /v1/silence/id
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/merger/v1_silence_id.go
  pkg/alertmanager/merger/v1_silence_id_test.go
  pkg/alertmanager/merger/v1_silences.go
  pkg/alertmanager/merger/v1_silences_test.go
Labels: size/L
