Repository cortexproject/cortex, pull requests merged in 2021-07, with the labels that each got.

#4336 Fix bug with counting of clusters for deleted elected replicas.
  CHANGELOG.md
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
Labels: size/M

#4262 Add timeout for waiting on compactor to become ACTIVE in the ring.
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_ring.go
  pkg/compactor/compactor_test.go
  pkg/ring/ring.go
  pkg/ring/util.go
  pkg/ring/util_test.go
Labels: size/L

#4341 MergeIterator: allocate less memory at first
  CHANGELOG.md
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/batch/merge.go
Labels: size/S

#4276 Expose default configuration values for memberlist.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/ring/kv/memberlist/kv_init_service_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/L

#4342 Allow setting ring heartbeat timeout to zero to disable timeout check.
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager_ring.go
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ring/model.go
  pkg/ring/model_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ruler/ruler_ring.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#4317 Add a new config and metric for reporting ruler query execution wall time.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/frontend/transport/handler.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/M

#4337 Add a security doc
  docs/_index.md
  docs/guides/security.md
Labels: size/S

#4345 Optimise memberlist kv store access by storing data unencoded.
  CHANGELOG.md
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/ring/kv/memberlist/mergeable.go
  pkg/ring/kv/memberlist/metrics.go
  pkg/ring/model.go
Labels: size/L

#4344 Allow disabling of ring heartbeats by setting relevant options to zero.
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager_ring.go
  pkg/compactor/compactor_ring.go
  pkg/distributor/distributor_ring.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/lifecycler.go
  pkg/ruler/ruler_ring.go
  pkg/storegateway/gateway_ring.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/L

#4346 Expose configuration of memberlist packet compression.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/integration_memberlist_single_binary_test.go
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/M

#4348 Attempt at making SyncOnRingTopologyChanges test more reliable.
  pkg/alertmanager/multitenant_test.go
Labels: size/S

#4349 Fix StateReplicationWithSharding_InitialSyncFromPeers flaking.
  pkg/alertmanager/multitenant_test.go
Labels: size/XS

#4274 Proposal for time series deletion with block storage
  docs/proposals/block-storage-time-series-deletion.md
Labels: size/L

#4353 Fix integration TestAlertmanagerSharding flaking.
  integration/alertmanager_test.go
Labels: size/XS

#4361 Fix integration TestSingleBinaryWithMemberlistScaling flaking.
  integration/integration_memberlist_single_binary_test.go
Labels: size/XS

#4362 Update go version in build image to 1.16.6
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
  docs/contributing/how-to-upgrade-golang-version.md
Labels: size/S

#4335 Fix ruler query failure reporting
  CHANGELOG.md
  integration/e2e/db/db.go
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/api/handlers.go
  pkg/querier/error_translate_queryable.go
  pkg/querier/error_translate_queryable_test.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
Labels: size/L

#4343 Add per-user query metrics for series and bytes returned
  CHANGELOG.md
  pkg/distributor/query.go
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
Labels: size/L

#4304 Prevent read on TSDB once closeAllTSDB function has been called
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
Labels: size/L

#4379 Update comment on rate-limit error
  pkg/distributor/distributor.go
Labels: size/XS

#4380 Upgrade Prometheus to LabelNames with matchers
  CHANGELOG.md
  go.mod
  go.sum
  pkg/configs/legacy_promql/engine_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/chunk_store_queryable.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/duplicates_test.go
  pkg/querier/error_translate_queryable.go
  pkg/querier/error_translate_queryable_test.go
  pkg/querier/lazyquery/lazyquery.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/queryrange/promql_test.go
  pkg/querier/queryrange/queryable.go
  pkg/querier/queryrange/test_utils.go
  pkg/querier/remote_read_test.go
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/querier/tenantfederation/merge_queryable_test.go
  vendor/github.com/prometheus/prometheus/storage/interface.go
  vendor/github.com/prometheus/prometheus/storage/merge.go
  vendor/github.com/prometheus/prometheus/storage/noop.go
  vendor/github.com/prometheus/prometheus/storage/remote/read.go
  vendor/github.com/prometheus/prometheus/storage/secondary.go
  vendor/github.com/prometheus/prometheus/tsdb/block.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/index/index.go
  vendor/github.com/prometheus/prometheus/tsdb/querier.go
  vendor/github.com/prometheus/prometheus/web/api/v1/api.go
  vendor/modules.txt
Labels: size/L
