Repository cortexproject/cortex, pull requests merged in 2021-12, with the labels that each got.

#4562 queryrange: retry: do not retry if context is canceled
  CHANGELOG.md
  pkg/querier/queryrange/retry.go
Labels: size/XS

#4571 Add config option to omit exporting rule_group label on ruler metrics
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/manager.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/ruler.go
Labels: size/L

#4561 distributor-queryable tests: make time go forward
  pkg/querier/distributor_queryable_test.go
Labels: size/XS

#4583 Distributor: fix bug in merging exemplars
  CHANGELOG.md
  pkg/distributor/query.go
  pkg/distributor/query_test.go
Labels: size/M

#4584 Changelog: cleanup
  CHANGELOG.md
Labels: size/XS

#4581 Introduce `http` config settings in Azure storage
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/contributing/how-to-run-website-locally.md
  pkg/storage/bucket/azure/bucket_client.go
  pkg/storage/bucket/azure/config.go
  pkg/storage/bucket/azure/config_test.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/http/config.go
  pkg/storage/bucket/http/config_test.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
Labels: size/XL

#4585 Update Thanos to latest main
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/google/btree/btree.go
  vendor/github.com/google/btree/go.mod
  vendor/github.com/thanos-io/thanos/pkg/block/block.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/block/index.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/reader_pool.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/hash.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/markers.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/block/writer.go
  vendor/github.com/thanos-io/thanos/pkg/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/cache/redis.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go
  vendor/github.com/thanos-io/thanos/pkg/compact/blocks_cleaner.go
  vendor/github.com/thanos-io/thanos/pkg/compact/clean.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/streamed_block_writer.go
  vendor/github.com/thanos-io/thanos/pkg/compact/planner.go
  vendor/github.com/thanos-io/thanos/pkg/compact/retention.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/resolver.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/memcache/provider.go
  vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/helpers.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/gcs/gcs.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/swift/swift.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/runutil/runutil.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/store/local.go
  vendor/github.com/thanos-io/thanos/pkg/store/multitsdb.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy.go
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/github.com/thanos-io/thanos/pkg/tracing/http.go
  vendor/github.com/thanos-io/thanos/pkg/tracing/tracing.go
  vendor/modules.txt
Labels: size/L
