Repository cortexproject/cortex, pull requests merged in 2021-02, with the labels that each got.

#3758 Expose index-header lazy load option and recommends bucket index
  docs/blocks-storage/production-tips.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/config.go
Labels: size/M

#3765 skipLabelNameValidation can now be set per request so no longer needed in config
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/S

#3722 Alertmanager: Remove alertmanager instead of pausing
  CHANGELOG.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/ruler/manager.go
Labels: size/XL

#3761 Fix RingServiceDiscovery logic on empty ring
  CHANGELOG.md
  pkg/ring/client/ring_service_discovery.go
  pkg/ring/client/ring_service_discovery_test.go
Labels: size/S

#3744 Enable @ modifier with result cache handling
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/L

#3762 Chore: renamed ring.IngesterDesc to ring.InstanceDesc
  pkg/alertmanager/alertmanager_ring_test.go
  pkg/alertmanager/lifecycle.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/ingester/transfer.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/basic_lifecycler_delegates.go
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ring/basic_lifecycler_test.go
  pkg/ring/batch.go
  pkg/ring/client/ring_service_discovery_test.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/merge_test.go
  pkg/ring/model.go
  pkg/ring/model_test.go
  pkg/ring/replication_set.go
  pkg/ring/replication_set_test.go
  pkg/ring/replication_set_tracker.go
  pkg/ring/replication_set_tracker_test.go
  pkg/ring/replication_strategy.go
  pkg/ring/replication_strategy_test.go
  pkg/ring/ring.go
  pkg/ring/ring.pb.go
  pkg/ring/ring.proto
  pkg/ring/ring_test.go
  pkg/ring/util.go
  pkg/ring/util_test.go
  pkg/ruler/lifecycle.go
  pkg/ruler/ruler_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring_test.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/XL

#3752 feat: add TLS support for communication from the Ruler-->AM
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/e2ecortex/services.go
  integration/ruler_test.go
  integration/util.go
  pkg/ruler/notifier.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
  pkg/util/http.go
Labels: size/L

#3767 Fixing tests
  go.mod
  go.sum
  pkg/ingester/flush_test.go
  pkg/ingester/rate_test.go
  pkg/ring/kv/kv_test.go
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/modules.txt
Labels: size/M

#3773 Log on parse error of @ modifier cache check
  pkg/querier/queryrange/results_cache.go
Labels: size/XS

#3778 fix: ensure global loggers are set
  CHANGELOG.md
  pkg/util/log.go
Labels: size/XS

#3783 Allow downstream projects to customise compactor
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/L

#3787 Fix concurrency in TestWatchPrefix
  pkg/ring/kv/kv_test.go
Labels: size/S

#3789 Upgrade Thanos
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/modules.txt
Labels: size/XS

#3780 chore: use embedded logger for Ingester & Flusher structs
  Makefile
  pkg/cortex/modules.go
  pkg/flusher/flusher.go
  pkg/ingester/flush.go
  pkg/ingester/flush_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/lifecycle_test.go
  pkg/ingester/mapper.go
  pkg/ingester/mapper_test.go
  pkg/ingester/transfer.go
  pkg/ingester/user_state.go
  pkg/ingester/wal.go
Labels: size/L

#3791 Revert PR 3765
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/S

#3777 Update Grafana Cloud offering description
  README.md
  docs/_index.md
Labels: size/S

#3792 Clarify DNS service discovery
  docs/configuration/arguments.md
Labels: size/XS

#3782 Cleanup tenant data in ingester
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/metrics.go
  pkg/ingester/user_metrics_metadata.go
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/L

#3784 Cleanup metrics exported by distributor for inactive tenants
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
  pkg/util/active_user.go
  pkg/util/active_user_test.go
  pkg/util/metrics_helper.go
  pkg/util/validation/validate.go
Labels: size/XL

#3785 feat: Emit per-tenant limit overrides as metrics
  CHANGELOG.md
  Makefile
  docs/guides/overrides-exporter-runtime.yaml
  docs/guides/overrides-exporter.md
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/util/validation/exporter.go
  pkg/util/validation/exporter_test.go
Labels: size/L

#3800 Add more TSDB metrics for ingester to emit
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#3796 Add validation to http_prefix setting
  CHANGELOG.md
  pkg/cortex/cortex.go
  pkg/cortex/cortex_test.go
Labels: size/M

#3803 Don't truncate error on long series
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/S

#3807 Fixed 'could not guess file size' when uploading global deletion marks
  CHANGELOG.md
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
Labels: size/XS

#3770 thanosconvert: convert block meta from Thanos to Cortex
  CHANGELOG.md
  cmd/thanosconvert/Dockerfile
  cmd/thanosconvert/main.go
  docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
  docs/configuration/v1-guarantees.md
  tools/thanosconvert/thanosconvert.go
  tools/thanosconvert/thanosconvert_test.go
Labels: size/XL

#3808 Small HA tracker cleanup
  integration/kv_test.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
Labels: size/XL

#3810 Add S3 KMS support to blocks storage client
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  integration/s3_storage_client_test.go
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/aws/sse_config.go
  pkg/chunk/aws/sse_config_test.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
Labels: size/L

#3813 Removed deprecated -querier.split-queries-by-day
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/cortex.go
  pkg/querier/queryrange/roundtrip.go
Labels: size/S

#3815 Fix ring tokens sorting regression introduced in #3601
  pkg/ring/lifecycler.go
  pkg/ring/model.go
  pkg/ring/tokens.go
  pkg/ring/tokens_test.go
Labels: size/M

#3816 Fix ring tokens sorting regression introduced in #3601 (#3815)
  pkg/ring/lifecycler.go
  pkg/ring/model.go
  pkg/ring/tokens.go
  pkg/ring/tokens_test.go
Labels: size/M

#3822 Release 1.7-RC.1
  CHANGELOG.md
  VERSION
Labels: size/XS

#3809 HA tracker KV store cleanup
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
  integration/kv_test.go
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker.pb.go
  pkg/distributor/ha_tracker.proto
  pkg/distributor/ha_tracker_test.go
  pkg/ring/kv/etcd/etcd.go
  pkg/util/time.go
Labels: size/L

#3750 Tenant deletion: ruler support.
  CHANGELOG.md
  pkg/chunk/inmemory_storage_client.go
  pkg/chunk/purger/blocks_purger_api.go
  pkg/chunk/purger/blocks_purger_api_test.go
  pkg/cortex/modules.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/mapper.go
  pkg/ruler/ruler.go
  pkg/ruler/rules/local/local.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/objectclient/rule_store_test.go
  pkg/ruler/rules/store.go
  pkg/ruler/store_mock_test.go
Labels: size/L

#3819 Fix broken url in docs
  docs/getting-started/getting-started-with-gossip-ring.md
Labels: size/XS

#3830 Upgrade Thanos
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/compact/planner.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/pool/pool.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket_factory.go
  vendor/modules.txt
Labels: size/S

#3824 Randomly distribute queries across store-gateways
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
Labels: size/L

#3818 Handle the case of large step causing single pt extents
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/M

#3825 Prevent failed ingestion from affecting rate limiting in distributor.
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/limiter/rate_limiter.go
  pkg/util/limiter/rate_limiter_test.go
Labels: size/L

#3833 Change ingester to return 400 instead of 429 on series/metadata limits.
  CHANGELOG.md
  pkg/ingester/errors.go
  pkg/ingester/ingester_test.go
Labels: size/XS

#3835 (1.7 release) Handle the case of large step causing single pt extents (#3818)
  pkg/querier/queryrange/results_cache.go
  pkg/querier/queryrange/results_cache_test.go
Labels: size/M

#3671 Alertmanager Distributor
  CHANGELOG.md
  Makefile
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/docker-compose.yml
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager_client.go
  pkg/alertmanager/alertmanager_ring.go
  pkg/alertmanager/alertmanagerpb/alertmanager.pb.go
  pkg/alertmanager/alertmanagerpb/alertmanager.proto
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/multitenant.go
  pkg/api/api.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/frontend/transport/handler.go
  pkg/util/http.go
  pkg/util/http_test.go
Labels: size/XL

#3801 Better error messages for rate-limits hit
  pkg/ingester/limiter.go
  pkg/ingester/limiter_test.go
Labels: size/S

#3836 Allow to configure the partitioner max gap size
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
Labels: size/XS

#3840 Updating VERSION & CHANGELOG for 1.7.0-rc.2
  CHANGELOG.md
  VERSION
Labels: size/XS

#3837 Introduce NamedService interface that allows service to return a name.
  pkg/util/services/basic_service.go
  pkg/util/services/basic_service_test.go
  pkg/util/services/failure_watcher.go
  pkg/util/services/service.go
  pkg/util/services/services.go
Labels: size/M

#3543 fix panic in inverted index delete operation when expected fp is not present
  pkg/ingester/index/index.go
  pkg/ingester/index/index_test.go
Labels: size/M

#3826 Cleanup of query-frontend and query-scheduler metrics for inactive users.
  CHANGELOG.md
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/frontend/config.go
  pkg/frontend/frontend_test.go
  pkg/frontend/transport/handler.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/queue_test.go
  pkg/frontend/v2/frontend.go
  pkg/querier/queryrange/roundtrip.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/active_user.go
Labels: size/L

#3829 Name services for better logging on failure
  pkg/ring/client/pool.go
  pkg/ring/kv/memberlist/kv_init_service.go
  pkg/ring/lifecycler.go
  pkg/ring/ring.go
Labels: size/S

#3844 doc: add shuffle sharding FAQ
  docs/guides/shuffle-sharding.md
Labels: size/XS

#3846 Move distributor metrics to Distributor struct.
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
Labels: size/L

#3811 Add per-tenant S3 KMS SSE encryption key support to blocks storage
  CHANGELOG.md
  Makefile
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  docs/guides/encryption-at-rest.md
  docs/guides/encryption-at-rest.template
  pkg/chunk/purger/blocks_purger_api.go
  pkg/chunk/purger/blocks_purger_api_test.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/modules.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/querier/blocks_finder_bucket_index.go
  pkg/querier/blocks_finder_bucket_index_test.go
  pkg/querier/blocks_finder_bucket_scan.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
  pkg/storage/bucket/user_bucket_client.go
  pkg/storage/bucket/user_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
  pkg/storage/tsdb/bucketindex/markers.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_test.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storegateway/bucket_index_metadata_fetcher.go
  pkg/storegateway/bucket_index_metadata_fetcher_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_fetcher_filters_test.go
  pkg/util/validation/limits.go
  tools/blocksconvert/builder/builder.go
  tools/doc-generator/main.go
  tools/thanosconvert/thanosconvert.go
Labels: size/XL

#3852 Rename Blocks Purger to Tenant Deletion.
  pkg/api/api.go
  pkg/chunk/purger/tenant_deletion_api.go
  pkg/chunk/purger/tenant_deletion_api_test.go
  pkg/cortex/modules.go
Labels: size/M

#3843 Create an interface to access per-tenant limit overrides
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/util/validation/exporter.go
  pkg/util/validation/exporter_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#3849 Delete cached shuffle-shard subring when user is inactive.
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/M

#3805 RuleStore: implementation using thanos objstore bucket client
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/configs.go
  integration/ruler_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/ruler/rulestore/bucket_client.go
  pkg/ruler/rulestore/bucket_client_test.go
  pkg/ruler/rulestore/config.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/prefixed_bucket_client.go
Labels: size/XXL

#3851 Cleanup meta sync files in compactor for un-owned users.
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/L

#3853 Cleanup local sync dirs for users that don't belong to store-gateways shard anymore.
  CHANGELOG.md
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/metadata_fetcher_metrics.go
Labels: size/L

#3842 Mention to disable marks migration in compactor production tips
  docs/blocks-storage/production-tips.md
Labels: size/XS

#3850 Apply jitter to the configured timeout for performing idle compactions.
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
  pkg/storage/tsdb/config.go
  pkg/util/time.go
  pkg/util/time_test.go
Labels: size/M

#3855 Upgrade thanos in cortex to backport 3814
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/io.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.proto
  vendor/golang.org/x/text/unicode/bidi/bidi.go
  vendor/golang.org/x/text/unicode/bidi/core.go
  vendor/modules.txt
Labels: size/XS

#3857 Warn in CHANGELOG to disable mark migration
  CHANGELOG.md
Labels: size/XS

#3861 Updating CHANGELOG and VERSION for 1.7 release
  CHANGELOG.md
  VERSION
  docs/guides/running-chunks-storage-with-cassandra.md
  k8s/alertmanager-dep.yaml
  k8s/configs-dep.yaml
  k8s/distributor-dep.yaml
  k8s/ingester-dep.yaml
  k8s/querier-dep.yaml
  k8s/query-frontend-dep.yaml
  k8s/ruler-dep.yaml
  k8s/table-manager-dep.yaml
Labels: size/M

#3821 chore: remove global logger from the querier package
  Makefile
  pkg/api/handlers.go
  pkg/cortex/modules.go
  pkg/querier/astmapper/parallel.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/chunk_tar_test.go
  pkg/querier/duplicates_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/queryrange/promql_test.go
  pkg/querier/queryrange/querysharding_test.go
  pkg/querier/queryrange/results_cache_test.go
  pkg/querier/queryrange/roundtrip_test.go
  pkg/querier/remote_read.go
  pkg/querier/remote_read_test.go
  pkg/querier/worker/frontend_processor_test.go
  pkg/querier/worker/worker_test.go
Labels: size/L

#3820 chore: remove global logger from the ruler package
  Makefile
  integration/chunks_storage_backends_test.go
  pkg/chunk/purger/tenant_deletion_api_test.go
  pkg/cortex/modules.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/objectclient/rule_store_test.go
  pkg/ruler/storage.go
Labels: size/L

#3864 Adding v1.7.0 to back-compat tests & github actions
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#3867 Upgrade Thanos to add Bucket.Iter() recursive listing support
  go.mod
  go.sum
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/prefixed_bucket_client.go
  pkg/storage/bucket/user_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storegateway/sharding_strategy.go
  tools/thanosconvert/thanosconvert_test.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/filesystem/filesystem.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/gcs/gcs.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/inmem.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/swift/swift.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/testing.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/tracing.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/caching_bucket.go
  vendor/modules.txt
Labels: size/S

#3868 Chore: merge ruler store tests
  pkg/ruler/rules/objectclient/rule_store.go
  pkg/ruler/rules/objectclient/rule_store_test.go
  pkg/ruler/rulestore/bucket_client.go
  pkg/ruler/rulestore/bucket_client_test.go
Labels: size/XL

#3860 Fixed TimeToMilliseconds() used in integration tests
  integration/e2e/util.go
  integration/e2e/util_test.go
Labels: size/M

#3856 Add functions to access cortexpb pool
  pkg/cortexpb/compat.go
  pkg/cortexpb/timeseries.go
  pkg/cortexpb/timeseries_test.go
Labels: size/M

#3870 Refactoring: use PrefixedBucketClient in UserBucketClient
  pkg/storage/bucket/prefixed_bucket_client.go
  pkg/storage/bucket/user_bucket_client.go
Labels: size/M

#3869 Use recursive iter in ruler store client
  CHANGELOG.md
  pkg/ruler/rulestore/bucket_client.go
  pkg/ruler/rulestore/bucket_client_test.go
Labels: size/L

#3863 avoid allocating new label Builder in loop
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/M

#3876 Update migration doc
  docs/blocks-storage/migrate-from-chunks-to-blocks.md
Labels: size/S

#3878 Add thanosconvert binary to .gitignore
  .gitignore
Labels: size/XS

#3872 Add JSON tags to Limits object for JSON serialization
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#3883 Upgrade opentracing dependency to remove fork
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS

#3881 Refactored alertmanager storage packages
  Makefile
  integration/alertmanager_test.go
  pkg/alertmanager/alertspb/alerts.pb.go
  pkg/alertmanager/alertspb/alerts.proto
  pkg/alertmanager/alertspb/compat.go
  pkg/alertmanager/alertstore/config.go
  pkg/alertmanager/alertstore/configdb/store.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/alertmanager/alertstore/store.go
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#3871 Add documentation for S3 SSE support to ruler
  CHANGELOG.md
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3-single-binary/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/config/rules.yaml
  development/tsdb-blocks-storage-swift-single-binary/config/cortex.yaml
  docs/guides/encryption-at-rest.md
  docs/guides/encryption-at-rest.template
Labels: size/L

#3859 Documented how to scale up / down ingesters
  docs/guides/ingesters-rolling-updates.md
  docs/guides/ingesters-scaling-up-and-down.md
Labels: size/M

#3880 Added metrics to track chunk bytes pool behaviour
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/chunk_bytes_pool.go
  pkg/storegateway/chunk_bytes_pool_test.go
Labels: size/L

#3858 Updated shuffle-sharding doc
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  docs/guides/shuffle-sharding.md
  pkg/querier/querier.go
Labels: size/M

#3877 Added metrics to track partitioner behaviour
  CHANGELOG.md
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/partitioner.go
  pkg/storegateway/partitioner_test.go
Labels: size/L
