Repository cortexproject/cortex, pull requests merged in 2021-08, with the labels that each got.

#4366 Fix Ingesters unable to re-join the cluster then `unregister_on_shutdown=false` + `-ingester.heartbeat-period=0`
  CHANGELOG.md
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
Labels: size/L

#4395 Update to version 1.10
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
Labels: size/S

#4406 Merge release 1.10 to master
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
Labels: size/S

#4405 Update community call times.
  README.md
Labels: size/XS

#4328 Don't try to compact blocks marked for deletion.
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/S

#4382 Adding AlertManager SNS Receiver Implementation
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/util/validation/notifications_limit_flag.go
  vendor/github.com/aws/aws-sdk-go/service/sns/api.go
  vendor/github.com/aws/aws-sdk-go/service/sns/doc.go
  vendor/github.com/aws/aws-sdk-go/service/sns/errors.go
  vendor/github.com/aws/aws-sdk-go/service/sns/service.go
  vendor/github.com/prometheus/alertmanager/asset/assets_vfsdata.go
  vendor/github.com/prometheus/alertmanager/config/config.go
  vendor/github.com/prometheus/alertmanager/config/notifiers.go
  vendor/github.com/prometheus/alertmanager/notify/notify.go
  vendor/github.com/prometheus/alertmanager/notify/sns/sns.go
  vendor/github.com/prometheus/alertmanager/template/default.tmpl
  vendor/github.com/prometheus/common/sigv4/LICENSE
  vendor/github.com/prometheus/common/sigv4/Makefile
  vendor/github.com/prometheus/common/sigv4/go.mod
  vendor/github.com/prometheus/common/sigv4/go.sum
  vendor/github.com/prometheus/common/sigv4/sigv4.go
  vendor/github.com/prometheus/common/sigv4/sigv4_config.go
  vendor/modules.txt
Labels: size/XS

#4419 Memberlist now forwards only changes, not full original received message
  CHANGELOG.md
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/L

#4420 Memberlist ignore old tombstones
  CHANGELOG.md
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/L

#4425 Replace use of global loggers in the module subsystem
  pkg/cortex/modules.go
  pkg/util/module_service.go
  pkg/util/modules/module_service_wrapper.go
  pkg/util/modules/modules.go
  pkg/util/modules/modules_test.go
Labels: size/M

#4417 Fix bug where querier may not be able to achieve max-concurrent
  CHANGELOG.md
  pkg/querier/worker/worker.go
  pkg/querier/worker/worker_test.go
Labels: size/M

#4407 Add release 1.10 to the backwards compatibility matrix
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/S

#4386 Reduce flakiness on chunk flush tests
  pkg/ingester/ingester_test.go
Labels: size/S

#4434 frontend: permit passing a custom http.RoundTripper
  pkg/frontend/config.go
  pkg/frontend/downstream_roundtripper.go
Labels: size/XS

#4429 querier: exhaust response body before closing
  pkg/querier/queryrange/roundtrip.go
Labels: size/XS
