Repository cortexproject/cortex, pull requests merged in 2022-01, with the labels that each got.

#4503 Adds new metric for dropped samples in ingester
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/validation/validate.go
Labels: size/L

#4597 Disable block deletion marks migration by default
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/production-tips.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
Labels: size/S

#4500 Add a note about remote read in HA Pair handling
  docs/guides/ha-pair-handling.md
Labels: size/M

#4602 Upgrade Go to 1.17.5 for integration tests + Dockerfiles
  .github/workflows/test-build-deploy.yml
  build-image/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
Labels: size/S

#4604 Rebuild and update build image from master.
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
Labels: size/S

#4601 Upgrade dskit and pass empty service name to dskit/grpcutil.Resolver.Resolve
  CHANGELOG.md
  go.mod
  go.sum
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/lifecycle_test.go
  pkg/ruler/lifecycle_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/dns_watcher.go
  vendor/github.com/grafana/dskit/closer/closer.go
  vendor/github.com/grafana/dskit/concurrency/runner.go
  vendor/github.com/grafana/dskit/crypto/tls/tls.go
  vendor/github.com/grafana/dskit/flagext/day.go
  vendor/github.com/grafana/dskit/flagext/register.go
  vendor/github.com/grafana/dskit/grpcutil/dns_resolver.go
  vendor/github.com/grafana/dskit/grpcutil/naming.go
  vendor/github.com/grafana/dskit/internal/math/math.go
  vendor/github.com/grafana/dskit/kv/consul/client.go
  vendor/github.com/grafana/dskit/kv/consul/mock.go
  vendor/github.com/grafana/dskit/kv/etcd/etcd.go
  vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go
  vendor/github.com/grafana/dskit/kv/memberlist/mergeable.go
  vendor/github.com/grafana/dskit/kv/memberlist/tcp_transport.go
  vendor/github.com/grafana/dskit/math/math.go
  vendor/github.com/grafana/dskit/math/rate.go
  vendor/github.com/grafana/dskit/middleware/grpc.go
  vendor/github.com/grafana/dskit/ring/basic_lifecycler.go
  vendor/github.com/grafana/dskit/ring/http.go
  vendor/github.com/grafana/dskit/ring/lifecycler.go
  vendor/github.com/grafana/dskit/ring/model.go
  vendor/github.com/grafana/dskit/ring/replication_set.go
  vendor/github.com/grafana/dskit/ring/replication_strategy.go
  vendor/github.com/grafana/dskit/ring/ring.go
  vendor/github.com/grafana/dskit/ring/ticker.go
  vendor/github.com/grafana/dskit/ring/tokens.go
  vendor/github.com/grafana/dskit/ring/util.go
  vendor/github.com/grafana/dskit/runtimeconfig/manager.go
  vendor/github.com/grafana/dskit/time/time.go
  vendor/modules.txt
Labels: size/XL

#4613 Reintroduce util/runtimeconfig package
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/util/runtimeconfig/manager.go
  pkg/util/runtimeconfig/manager_test.go
  vendor/modules.txt
Labels: size/L

#4477 Federated ruler proposal
  docs/proposals/federated-ruler.md
Labels: size/M

#4612 Reintroduce grpc* packages
  go.mod
  pkg/alertmanager/alertmanager_client.go
  pkg/chunk/gcp/bigtable_index_client.go
  pkg/configs/client/client.go
  pkg/cortex/cortex.go
  pkg/distributor/query.go
  pkg/frontend/v2/frontend.go
  pkg/ingester/client/client.go
  pkg/ingester/client/cortex_util_test.go
  pkg/querier/store_gateway_client.go
  pkg/querier/store_gateway_client_test.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
  pkg/ruler/client_pool.go
  pkg/ruler/client_pool_test.go
  pkg/ruler/notifier.go
  pkg/ruler/ruler.go
  pkg/scheduler/scheduler.go
  pkg/util/dns_watcher.go
  pkg/util/grpcclient/backoff_retry.go
  pkg/util/grpcclient/grpcclient.go
  pkg/util/grpcclient/instrumentation.go
  pkg/util/grpcclient/ratelimit.go
  pkg/util/grpcclient/ratelimit_test.go
  pkg/util/grpcencoding/snappy/snappy.go
  pkg/util/grpcencoding/snappy/snappy_test.go
  pkg/util/grpcutil/dns_resolver.go
  pkg/util/grpcutil/health_check.go
  pkg/util/grpcutil/health_check_test.go
  pkg/util/grpcutil/naming.go
  pkg/util/grpcutil/util.go
  pkg/util/tls/test/tls_integration_test.go
  pkg/util/tls/tls.go
  pkg/util/tls/tls_test.go
  tools/blocksconvert/planprocessor/service.go
  vendor/modules.txt
Labels: size/XXL

#4614 Reintroduce pkg/util/concurrency, in place of dskit/concurrency
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/alertmanager/api.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor_test.go
  pkg/frontend/frontend_test.go
  pkg/ingester/ingester_v2.go
  pkg/querier/tenantfederation/merge_queryable.go
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ruler/ruler.go
  pkg/storegateway/bucket_index_metadata_fetcher_test.go
  pkg/util/concurrency/buffer.go
  pkg/util/concurrency/runner.go
  pkg/util/concurrency/runner_test.go
  vendor/github.com/grafana/dskit/internal/math/math.go
  vendor/modules.txt
Labels: size/L

#4615 Reintroduce pkg/util/limiter/rate_limiter.go, in place of dskit/limiter
  pkg/distributor/distributor.go
  pkg/distributor/ingestion_rate_strategy.go
  pkg/distributor/ingestion_rate_strategy_test.go
  pkg/util/limiter/rate_limiter.go
  pkg/util/limiter/rate_limiter_test.go
  vendor/modules.txt
Labels: size/L

#4619 Reintroduce pkg/util/middleware, in place of dskit/middleware
  pkg/chunk/gcp/instrumentation.go
  pkg/querier/worker/scheduler_processor.go
  pkg/util/grpcclient/instrumentation.go
  pkg/util/middleware/grpc.go
  pkg/util/middleware/grpc_test.go
  vendor/modules.txt
Labels: size/M

#4618 Reintroduce pkg/util/test, in place of dskit/test
  pkg/ring/basic_lifecycler_delegates_test.go
  pkg/ring/basic_lifecycler_test.go
  pkg/ring/lifecycler_test.go
  pkg/ring/ring_test.go
  pkg/util/test/test/poll.go
  vendor/modules.txt
Labels: size/XS

#4616 Reintroduce pkg/util/backoff in place of dskit/backoff
  integration/e2e/composite_service.go
  integration/e2e/service.go
  integration/e2e/service_test.go
  integration/integration_memberlist_single_binary_test.go
  pkg/chunk/aws/dynamodb_storage_client.go
  pkg/chunk/aws/dynamodb_table_client.go
  pkg/chunk/aws/fixtures.go
  pkg/chunk/aws/retryer.go
  pkg/compactor/compactor.go
  pkg/frontend/v2/frontend_scheduler_worker.go
  pkg/ingester/transfer.go
  pkg/querier/blocks_finder_bucket_scan.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/scheduler_processor.go
  pkg/ring/kv/consul/client.go
  pkg/ring/kv/etcd/etcd.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/tcp_transport_test.go
  pkg/ring/util.go
  pkg/storegateway/bucket_stores.go
  pkg/util/backoff/backoff.go
  pkg/util/backoff/backoff_test.go
  pkg/util/grpcclient/backoff_retry.go
  pkg/util/grpcclient/grpcclient.go
  tools/blocksconvert/builder/builder.go
  tools/blocksconvert/cleaner/cleaner.go
  tools/blocksconvert/scanner/scanner.go
  vendor/github.com/grafana/dskit/concurrency/buffer.go
  vendor/github.com/grafana/dskit/concurrency/runner.go
  vendor/github.com/grafana/dskit/internal/math/math.go
  vendor/modules.txt
Labels: size/L

#4622 Drop dependency on grafana/dskit/runutil
  integration/ca/ca.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/objectclient/store.go
  pkg/chunk/local/fs_object_client.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/util/runutil/runutil.go
  pkg/util/runutil/runutil_test.go
  vendor/modules.txt
Labels: size/M

#4623 Drop dependency on grafana/dskit/multierror
  go.mod
  go.sum
  pkg/compactor/compactor_test.go
  pkg/util/concurrency/runner.go
  pkg/util/multierror/multierror.go
  pkg/util/runutil/runutil.go
  vendor/github.com/grafana/dskit/LICENSE
  vendor/modules.txt
Labels: size/XS

#4113 RFC: Add integration test for etcd
  integration/backward_compatibility_test.go
  integration/blocks_storage_backends_test.go
  integration/e2ecortex/services.go
  integration/ingester_limits_test.go
  integration/ingester_sharding_test.go
  integration/querier_remote_read_test.go
  integration/querier_sharding_test.go
  integration/querier_streaming_mixed_ingester_test.go
  integration/querier_tenant_federation_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/ruler_test.go
  integration/zone_aware_test.go
Labels: size/L

#4624 Add shuffle sharding grouper/planner (Clone of PR 4357)
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/XXL

#4625 fix PR number
  CHANGELOG.md
Labels: size/XS

#4574 update tenant retention proposal doc with implemented status
  docs/proposals/tenant_retention.md
Labels: size/XS

#4586 docs: reconcile service list with `cortex -modules`
  docs/architecture.md
Labels: size/XS

#4518 doc: Add note about the Alertmanager URL path
  pkg/ruler/ruler.go
Labels: size/XS

#4595 Add length and limit to error messages when label names and values are too long
  CHANGELOG.md
  pkg/util/validation/errors.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/M

#4596 Set appropriate headers in /services endpoint.
  CHANGELOG.md
  pkg/cortex/status.go
Labels: size/XS

#4629 Add Alan Protasio as maintainer
  MAINTAINERS
Labels: size/XS

#4388 distributor: don't return 5xx on a single ingester outage
  pkg/distributor/distributor_test.go
  pkg/ring/batch.go
Labels: size/L

#4635 Add step to submit PR to CNCF maintainer list
  docs/contributing/how-to-add-a-maintainer.md
Labels: size/S

#4633 Query Frontend: Fix slow query logging if 'LogQueriesLongerThan' is set to < 0
  CHANGELOG.md
  pkg/frontend/frontend_test.go
  pkg/frontend/transport/handler.go
Labels: size/L
