Repository cortexproject/cortex, pull requests merged in 2022-04, with the labels that each got.

#4698 Stepping down as maintainer.
  MAINTAINERS
Labels: size/XS

#4686 Fix incorrectly named cache metrics
  CHANGELOG.md
  pkg/chunk/cache/instrumented.go
Labels: size/XS

#4701 Docs update: the correct word is loses
  docs/architecture.md
Labels: size/XS

#4702 Enable thanos series limiter in store-gateway
  CHANGELOG.md
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/gateway_test.go
Labels: size/L

#4683 Implement max series limit in distributor for `/series` API
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/L

#4707 Introduce SkipBlocksWithOutOfOrderChunksEnabled feature
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/L

#4433 Add shuffle-sharding for the compactor
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/guides/shuffle-sharding.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/util/validation/limits.go
Labels: size/XL

#4716 Fix/concurrent map interaction
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/M

#4720 Remove mention of CNCF calendar for community meetings, which is usually out of sync
  README.md
Labels: size/XS

#4721 Abandoning release 1.12
  CHANGELOG.md
  RELEASE.md
Labels: size/S

#4675 docs: clarify store-gateway lazy-load behavior
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/config.go
Labels: size/S

#4570 Downstream url documentation
  docs/architecture.md
  docs/configuration/prometheus-frontend.md
  docs/configuration/prometheus-frontend.yml
Labels: size/XS
