Repository cortexproject/cortex, pull requests merged in 2022-09, with the labels that each got.

#4645 Redirect to valid thanos filestystem doc page
  docs/blocks-storage/_index.md
Labels: size/XS

#4849 Using tls client config as the other clients on cortex
  docs/configuration/config-file-reference.md
  pkg/tracing/tracing.go
Labels: size/M

#4803 feat: Added support for logging of HTTP Headers
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/api/api.go
  pkg/api/api_test.go
  pkg/api/middlewares.go
  pkg/api/middlewares_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/ingester/ingester.go
  pkg/querier/queryrange/roundtrip.go
  pkg/util/grpcclient/instrumentation.go
  pkg/util/grpcutil/grpc_interceptors_test.go
  pkg/util/grpcutil/util.go
  pkg/util/log/log.go
  pkg/util/log/log_test.go
  pkg/util/log/wrappers.go
Labels: size/XL

#4848 Add new limit: max_series_label_size_bytes
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor_test.go
  pkg/util/validation/errors.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/M

#4805 Introduced lock file to shuffle sharding grouper
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/block_visit_marker.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
  pkg/storage/bucket/client_mock.go
Labels: size/XL

#4850 Fix Build after https://github.com/cortexproject/cortex/pull/4841
  pkg/compactor/block_visit_marker.go
  pkg/compactor/shuffle_sharding_planner.go
Labels: size/XS

#4794 Make s3 bucket lookup type configurable
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  integration/e2ecortex/storage.go
  pkg/cortex/cortex_test.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
  pkg/storage/bucket/sse_bucket_client_test.go
Labels: size/M

#4851 Remove use of io/ioutil package because it's deprecated
  .gitignore
  .golangci.yml
  cmd/cortex/main.go
  integration/api_endpoints_test.go
  integration/e2e/scenario_test.go
  integration/e2e/service.go
  integration/e2e/util.go
  integration/querier_remote_read_test.go
  integration/util.go
  pkg/alertmanager/alertmanager_http_test.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/local/store_test.go
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/alertmanager/distributor.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
  pkg/api/handlers_test.go
  pkg/compactor/block_visit_marker.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/configs/api/api.go
  pkg/frontend/frontend_test.go
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/roundtripper.go
  pkg/frontend/v1/frontend_test.go
  pkg/ingester/ingester_test.go
  pkg/querier/metadata_handler_test.go
  pkg/querier/queryrange/marshaling_test.go
  pkg/querier/queryrange/query_range.go
  pkg/querier/queryrange/query_range_test.go
  pkg/querier/queryrange/roundtrip.go
  pkg/querier/queryrange/roundtrip_test.go
  pkg/querier/queryrange/split_by_interval_test.go
  pkg/querier/remote_read_test.go
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/local/local_test.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/testutil/objstore.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway_test.go
  pkg/util/http_test.go
  pkg/util/process/collector.go
  pkg/util/process/collector_test.go
  pkg/util/tls/test/tls_integration_test.go
  pkg/util/tls/tls.go
  pkg/util/tls/tls_test.go
  tools/query-audit/config.go
  tools/querytee/proxy_backend.go
  tools/querytee/proxy_test.go
  tools/thanosconvert/thanosconvert_test.go
  tools/website/website.go
Labels: size/L

#4758 Proposal for implementing HA for ruler
  docs/proposals/ruler-ha.md
  website/static/images/proposals/ruler-ha-alerts-for-state-graph.png
Labels: size/M

#4832 Proposal for ring multikey
  docs/proposals/ring-multikey.md
  website/static/images/proposals/ring-multikey-latency.png
  website/static/images/proposals/ring-multikey-sequence.png
Labels: size/L

#4855 Add label name to labelValueTooLongError
  CHANGELOG.md
  pkg/util/validation/errors.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/S

#4840 Modifying https://github.com/cortexproject/cortex/pull/4422 to retry only for GET Requests
  CHANGELOG.md
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
Labels: size/M

#4856 Refactor on the Querier/QF tripperware
  Makefile
  pkg/api/middlewares.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/tripperware/instrumentation.go
  pkg/querier/tripperware/limits.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/queryrange/limits.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/marshaling_test.go
  pkg/querier/tripperware/queryrange/promql_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/queryrange.pb.go
  pkg/querier/tripperware/queryrange/queryrange.proto
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
  pkg/querier/tripperware/queryrange/retry.go
  pkg/querier/tripperware/queryrange/retry_test.go
  pkg/querier/tripperware/queryrange/series_test.go
  pkg/querier/tripperware/queryrange/split_by_interval.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
  pkg/querier/tripperware/queryrange/step_align.go
  pkg/querier/tripperware/queryrange/step_align_test.go
  pkg/querier/tripperware/queryrange/test_utils.go
  pkg/querier/tripperware/queryrange/test_utils_test.go
  pkg/querier/tripperware/queryrange/value.go
  pkg/querier/tripperware/queryrange/value_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/querier/tripperware/util.go
  tools/doc-generator/main.go
Labels: size/XXL

#4858 Removing dead code from chunks storage
  pkg/querier/astmapper/astmapper.go
  pkg/querier/astmapper/astmapper_test.go
  pkg/querier/astmapper/embedded.go
  pkg/querier/astmapper/parallel.go
  pkg/querier/astmapper/parallel_test.go
  pkg/querier/astmapper/shard_summer.go
  pkg/querier/astmapper/shard_summer_test.go
  pkg/querier/astmapper/subtree_folder.go
  pkg/querier/astmapper/subtree_folder_test.go
  pkg/querier/tripperware/queryrange/promql_test.go
  pkg/querier/tripperware/queryrange/test_utils.go
  pkg/querier/tripperware/queryrange/test_utils_test.go
Labels: size/XXL

#4853 Add log message for partial failure on push
  pkg/ingester/ingester.go
Labels: size/XS

#4862 Respecting `-tracing.otel.sample-ratio` configuration when enabling OpenTelemetry tracing with X-ray
  CHANGELOG.md
  pkg/tracing/sampler/sampling.go
  pkg/tracing/sampler/sampling_test.go
  pkg/tracing/tracing.go
Labels: size/L

#4865 Fixing Flaky AM test
  pkg/alertmanager/distributor_test.go
Labels: size/S

#4866 Add release 1.11.1 to the backwards compatibility matrix
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#4867 Fix tiny issue of doc in RandomRatioBased
  pkg/tracing/sampler/sampling.go
Labels: size/XS

#4864 Graduating `stream-chunks-when-using-blocks` configuration
  CHANGELOG.md
  docs/configuration/v1-guarantees.md
  integration/ruler_test.go
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: size/L

#4870 Ignore not found errors when compacting users
  pkg/compactor/compactor.go
Labels: size/XS

#4874 Follow up of 4870 - Ignore 404 on `thanos_objstore_bucket_operation_failures_total` only when fetching the markers
  pkg/compactor/block_visit_marker.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/M

#4873 Rename block visit marker and update visit time to int64
  pkg/compactor/block_visit_marker.go
  pkg/compactor/block_visit_marker_test.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/L

#4876 Remove Bryan Boreham from MAINTAINERS file
  MAINTAINERS
Labels: size/XS

#4869 Using `sortSeries` from Select to decided to sort the response on DistributorQueryable
  pkg/querier/distributor_queryable.go
  pkg/querier/duplicates_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/remote_read_test.go
  pkg/querier/series/series_set.go
  pkg/querier/series/series_set_test.go
  pkg/querier/tenantfederation/merge_queryable_test.go
  pkg/querier/timeseries_series_set.go
  pkg/querier/timeseries_series_set_test.go
  pkg/querier/tripperware/queryrange/series_test.go
  pkg/querier/tripperware/queryrange/value.go
Labels: size/L

#4861 Refactor: move the `Purger` to different directory
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/middlewares.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/purger/tenant_deletion_api.go
  pkg/purger/tenant_deletion_api_test.go
  pkg/purger/tombstones.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/series/series_set.go
  pkg/ruler/ruler_test.go
Labels: size/S

#4877 QueryFronted should send request to queriers when query_range has start==end
  CHANGELOG.md
  pkg/querier/tripperware/queryrange/split_by_interval.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
Labels: size/S

#4843 add proposal for timeseries partitioning in compactor
  docs/proposals/timeseries-partitioning-in-compactor.md
  website/static/images/proposals/timeseries-partitioning-in-compactor-compact.png
  website/static/images/proposals/timeseries-partitioning-in-compactor-grouping.png
  website/static/images/proposals/timeseries-partitioning-in-compactor-modulo-partition.png
  website/static/images/proposals/timeseries-partitioning-in-compactor-partitions.png
Labels: size/L

#4863 Vertical query sharding - leveraging thanos implementation
  CHANGELOG.md
  Makefile
  docs/configuration/v1-guarantees.md
  pkg/cortex/modules.go
  pkg/ingester/ingester.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_middlewares.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/instantquery.pb.go
  pkg/querier/tripperware/instantquery/instantquery.proto
  pkg/querier/tripperware/instantquery/shard_by_query_test.go
  pkg/querier/tripperware/limits.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/querier/tripperware/shard_by.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
  pkg/querysharding/util.go
  pkg/util/validation/limits.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analysis.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/modules.txt
Labels: size/XXL

#4883 Update adopters section on index page
  website/data/adopters.yml
  website/static/logos/grafana.svg
Labels: size/M

#4881 Adding HA tracker kv store type validation
  pkg/distributor/ha_tracker.go
  pkg/distributor/ha_tracker_test.go
Labels: size/S

#4854 Implement max_fetched_data_bytes_per_query limit
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/frontend/transport/handler.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
  pkg/util/limiter/query_limiter.go
  pkg/util/limiter/query_limiter_test.go
  pkg/util/validation/limits.go
Labels: size/L

#4887 chore: update thanos to bring compaction run duration log
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/modules.txt
Labels: size/XS
