Repository cortexproject/cortex, pull requests merged in 2022-12, with the labels that each got.

#5000 Ingester: Added configuration to set the size of the tsdb in-memory queue used before flushing chunks to the disk
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/metrics.go
  pkg/storage/tsdb/config.go
Labels: size/M

#4991 Make max outstanding queries per tenant config in limits
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/frontend/frontend_test.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/queue_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/validation/limits.go
Labels: size/L

#5010 Add /api/v1/query_exemplars route support to query-tee
  CHANGELOG.md
  cmd/query-tee/main.go
Labels: size/XS

#5009 Add a static handler for buildinfo static API
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/cortex/modules.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
Labels: size/M

#5013 Ready for 1.14 release
  CHANGELOG.md
  VERSION
Labels: size/XS

#5014 Merge release 1.14 to master
  CHANGELOG.md
  VERSION
Labels: size/S

#5015 Adding compatibility tests for 1.13 and 1.14
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#5012 Merge background contexts of all ingester pushes into one in distributor
  pkg/distributor/distributor.go
Labels: size/M

#5029 Increase upper bound for queue duration histogram bucket
  CHANGELOG.md
  pkg/frontend/v1/frontend.go
  pkg/scheduler/scheduler.go
Labels: size/XS

#5030 Add counter metrics for total requests going to queue
  CHANGELOG.md
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/scheduler.go
Labels: size/S

#5037 Logging Vertical Sharding info on query stats
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/v1/frontendv1pb/frontend.pb.go
  pkg/frontend/v1/frontendv1pb/frontend.proto
  pkg/frontend/v2/frontend_test.go
  pkg/frontend/v2/frontendv2pb/frontend.pb.go
  pkg/frontend/v2/frontendv2pb/frontend.proto
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
  pkg/querier/tripperware/shard_by.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/scheduler_processor.go
Labels: size/L

#5027 Ingester: Metadata APIs should honour QueryIngestersWithin when QueryStoreForLabels is enabled
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/L

#5041 Building Arm Images
  .github/workflows/scripts/install-docker.sh
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  push-images
Labels: size/M

#5044 Fix tracing.NewRandomRatioBased panic
  CHANGELOG.md
  pkg/tracing/sampler/sampling.go
  pkg/tracing/sampler/sampling_test.go
  pkg/tracing/tracing.go
Labels: size/L

#5047 Remove flapping test in tracing sampling
  pkg/tracing/sampler/sampling_test.go
Labels: size/XS

#5045 Fix opsgenie validation
  CHANGELOG.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
Labels: size/M

#5055 Fixed no compact block got grouped in shuffle sharding grouper
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
Labels: size/M

#5028 Let blocks_cleaner delete blocks concurrently
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
Labels: size/M

#5074 Fix objstore tracing instrumentation
  CHANGELOG.md
  pkg/cortex/tracing.go
Labels: size/XS

#5072 Test example config with filesystem backend
  integration/getting_started_single_process_config_local_test.go
Labels: size/M

#5075 Create Span for the codec MergeResponse method
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/split_by_interval.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
  pkg/querier/tripperware/shard_by.go
Labels: size/M

#5069 switch encoding/json to json iter
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
Labels: size/L

#5073 Run integration tests in parallel
  .github/workflows/test-build-deploy.yml
  .golangci.yml
  Makefile
  integration/alertmanager_test.go
  integration/asserts.go
  integration/backward_compatibility_test.go
  integration/configs.go
  integration/integration_memberlist_single_binary_test.go
  integration/querier_remote_read_test.go
  integration/querier_sharding_test.go
  integration/querier_tenant_federation_test.go
  integration/querier_test.go
  integration/ruler_test.go
  integration/util.go
Labels: size/M
