Repository cortexproject/cortex, pull requests merged in 2022-07, with the labels that each got.

#4771 Ensure that compaction continues for block with incomplete time-range
  CHANGELOG.md
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
Labels: size/L

#4774 Prepare for 1.13 rc1
  CHANGELOG.md
  VERSION
Labels: size/XS

#4772 fix cortex_compactor_remaining_planned_compactions not set after plan generation
  CHANGELOG.md
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
Labels: size/M

#4776 Fix CHANGELOG after merge from main branch
  CHANGELOG.md
Labels: size/XS

#4784 Compactor: Download and Upload block files in parallel
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/compactor/compactor.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/block.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/azure/azure.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/objstore.go
  vendor/modules.txt
Labels: size/M

#4532 Return data fetched from a subset of store-gateways instead of returning error if a single store-gateway fails
  CHANGELOG.md
  integration/querier_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/L

#4788 Ready for 1.13 release
  CHANGELOG.md
  VERSION
Labels: size/XS

#4792 Fix dependabot issue in package-lock.json second try
  website/package-lock.json
  website/package.json
Labels: size/XS

#4793 merge VERSION and CHANGELOG update from release-1.13 branch back to main branch
  CHANGELOG.md
  VERSION
Labels: size/XS

#4787 Update/thanos blocks
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/compactor/compactor.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  vendor/github.com/minio/minio-go/v7/api-put-object-streaming.go
  vendor/github.com/minio/minio-go/v7/api.go
  vendor/github.com/minio/minio-go/v7/hook-reader.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/tracing/tracing.go
  vendor/modules.txt
Labels: size/M

#4785 let redis cache logs log with context
  pkg/chunk/cache/redis_cache.go
  pkg/chunk/cache/snappy.go
  pkg/querier/queryrange/results_cache.go
Labels: size/S

#4783 DoBatch preference to 4xx if error
  CHANGELOG.md
  pkg/distributor/distributor_test.go
  pkg/ring/batch.go
Labels: size/S

#4806 Fix updateCachedShippedBlocks - Thanos Update
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/M

#4804 Join memberlist on starting with no retry
  CHANGELOG.md
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
Labels: size/M

#4801 Fix alertmanager log message
  pkg/alertmanager/multitenant.go
Labels: size/XS
