Repository cortexproject/cortex, pull requests merged in 2022-08, with the labels that each got.

#4809 Grafana Cloud uses Mimir now, so remove Grafana Cloud as hosted service in documents
  README.md
  docs/_index.md
Labels: size/S

#4816 Upgrade Hugo
  build-image/Dockerfile
Labels: size/M

#4818 add support for msi in bucket client
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/bucket/azure/bucket_client.go
  pkg/storage/bucket/azure/config.go
  pkg/storage/bucket/azure/config_test.go
Labels: size/M

#4813 merge Prometheus metrics for removed user to avoid having to recompute metrics from scratch everytime
  pkg/util/metrics_helper.go
  pkg/util/metrics_helper_test.go
Labels: size/L

#4823 Upate update build image instruction with things to note about GOPROXY
  docs/contributing/how-to-update-the-build-image.md
Labels: size/XS

#4824 remove ingester v2
  pkg/ingester/flush.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2.go
  pkg/ingester/ingester_v2_test.go
Labels: size/XXL

#4825 Disable TSDB Isolation
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: size/XS

#4827 Upgrade build image to use go 1.19
  build-image/Dockerfile
Labels: size/S

#4830 Fix Cortex website search function
  website/layouts/partials/search-input.html
Labels: size/XS

#4829 Use the new GO 1.19 build image
  .github/workflows/test-build-deploy.yml
  .golangci.yml
  CHANGELOG.md
  Makefile
  cmd/cortex/main_test.go
  cmd/thanosconvert/main.go
  docs/contributing/how-to-run-website-locally.md
  integration/asserts.go
  integration/blocks_storage_backends_test.go
  integration/e2e/scenario_test.go
  integration/e2e/service_test.go
  integration/e2ecortex/client.go
  integration/getting_started_single_process_config_test.go
  integration/getting_started_with_gossiped_ring_test.go
  integration/ingester_limits_test.go
  integration/ingester_sharding_test.go
  integration/integration_memberlist_single_binary_test.go
  integration/querier_remote_read_test.go
  integration/querier_sharding_test.go
  integration/querier_tenant_federation_test.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/util.go
  pkg/configs/db/db.go
  pkg/configs/legacy_promql/ast.go
  pkg/configs/legacy_promql/engine.go
  pkg/configs/legacy_promql/parse.go
  pkg/configs/legacy_promql/test.go
  pkg/cortex/modules.go
  pkg/ingester/active_series.go
  pkg/ingester/ingester.go
  pkg/querier/astmapper/shard_summer.go
  pkg/querier/astmapper/subtree_folder.go
  pkg/querier/error_translate_queryable.go
  pkg/ring/kv/etcd/mock.go
  pkg/ruler/ruler.go
  pkg/ruler/rulestore/local/local.go
  pkg/storage/tsdb/config.go
  pkg/tenant/resolver.go
  pkg/tenant/tenant.go
  pkg/util/log/log.go
  pkg/util/log/wrappers.go
  pkg/util/services/basic_service.go
  pkg/util/services/service.go
  pkg/util/validation/errors.go
  pkg/util/validation/limits_test.go
Labels: size/L

#4767 fixing unnecessary fields in rule_groups api
  CHANGELOG.md
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/http.go
Labels: size/M

#4808 Ruler external support
  CHANGELOG.md
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/cortex/modules_test.go
Labels: size/L

#4839 Follow up of 4532 - Return data fetched from a subset of store-gateways instead of returning error if a single store-gateway fails
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/M

#4800 add log to identify request cache hit and cache miss
  pkg/querier/queryrange/results_cache.go
Labels: size/S

#4846 Update my username
  MAINTAINERS
Labels: size/XS

#4847 [ingesters] Send heartbeat during wall replay
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/distributor/distributor.go
  pkg/ingester/ingester.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
  pkg/ring/ring_test.go
Labels: size/L

#4384 fix commit
  pkg/util/services/basic_service.go
Labels: size/XS
