Repository cortexproject/cortex, pull requests merged in 2022-06, with the labels that each got.

#4745 Reduce the number of series that are kept in memory while streaming from ingesters
  CHANGELOG.md
  pkg/cortexpb/compat.go
  pkg/distributor/distributor.go
Labels: size/XS

#4747 Add rand to sparse requests for rejoin memberlist cluster
  CHANGELOG.md
  pkg/ring/kv/memberlist/memberlist_client.go
Labels: size/M

#4718 fix leaking notifier in ruler when user is removed
  CHANGELOG.md
  pkg/ruler/manager.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler_test.go
Labels: size/L

#4750 Add limit time for gossip on ring
  CHANGELOG.md
  pkg/ring/merge_test.go
  pkg/ring/model.go
Labels: size/S

#4754 Organize changelog
  CHANGELOG.md
Labels: size/XS

#4756 skip compaction if there is only 1 block available for shuffle-sharding compactor
  CHANGELOG.md
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/M

#4759 Start 1.13.0 release
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#4760 Update VERSION for 1.13 release RC
  VERSION
Labels: size/XS

#4762 Update 1.x Guarantees doc to call out compactor shuffle sharding is experimental
  docs/configuration/v1-guarantees.md
Labels: size/XS

#4765 Removing fingerprint calculator from the lock on the GetSeries API
  pkg/distributor/distributor.go
  pkg/util/limiter/query_limiter_test.go
Labels: size/M
