Repository cortexproject/cortex, pull requests merged in 2022-02, with the labels that each got.

#4533 If frontend copy body return error, log it
  pkg/frontend/transport/handler.go
Labels: size/XS

#4636 update defaultReplicationStrategy to not fail with extend-write when a single instance is unhealthy
  CHANGELOG.md
  pkg/ring/replication_strategy.go
  pkg/ring/replication_strategy_test.go
Labels: size/M

#4649 Prep release 1.12.0
  CHANGELOG.md
  RELEASE.md
Labels: size/S
