Repository cortexproject/cortex, pull requests merged in 2022-11, with the labels that each got.

#4943 KubeCon NA 2022 is done, remove the info links
  README.md
  docs/_index.md
Labels: size/XS

#4944 Add signing release artifacts instruction
  RELEASE.md
Labels: size/S

#4946 Add instruction to upload signing public key
  RELEASE.md
Labels: size/XS

#4947 Add instruction on how to generate SBOM as part of release process
  RELEASE.md
Labels: size/M

#4950 Add trademark notice to website footer
  website/layouts/partials/footer.html
Labels: size/M

#4880 update getting started doc
  docs/getting-started/_index.md
Labels: size/S

#4949 Upload global marker before local
  CHANGELOG.md
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
Labels: size/XS

#4907 grab 'status' label for cortex_alertmanager_alerts_received_total metric
  CHANGELOG.md
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
Labels: size/S

#4955 Support sharding subqueries in instant query QF
  CHANGELOG.md
  go.mod
  go.sum
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/instantquery.pb.go
  pkg/querier/tripperware/instantquery/instantquery.proto
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/merge_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/miekgdns/resolver.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/limiter.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy_heap.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/types.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/types.proto
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/modules.txt
Labels: size/L

#4960 Always request querier to return gzipped response
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/queryrange/query_range.go
Labels: size/M

#4961 Upgrde build docker engine to latest version
  .github/workflows/scripts/install-docker.sh
  integration/e2e/service.go
Labels: type/chore, size/XS

#4959 [Vote] Ben Ye (yeya24) as new Cortex maintainers
  MAINTAINERS
Labels: size/XS, Vote

#4962 Add OpenSSf badge
  README.md
Labels: size/XS

#4963 Update Thanos to get latest querysharding fix
  go.mod
  go.sum
  pkg/querier/tripperware/test_shard_by_query_utils.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analysis.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/modules.txt
Labels: size/XS

#4968 Start 1.14 Release
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#4969 1.14.0 Release Preparation
  CHANGELOG.md
  VERSION
Labels: size/S

#4973 Update README with KubeCon talk video and slides
  README.md
Labels: size/S

#4975 fix response error to be ungzipped when status code is not 2xx
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_test.go
Labels: size/L

#4979 Bump RC version
  VERSION
Labels: size/XS

#4983 Chunks can be migrated on v1.13.1
  CHANGELOG.md
Labels: size/XS

#4977 Update architecture diagram and doc
  docs/architecture.md
  images/architecture.png
  website/static/images/architecture.png
Labels: size/M

#4985 Add clomonitor badge to README
  README.md
Labels: size/XS

#4978 Support Prometheus /api/v1/status/buildinfo API on Querier/QFE
  CHANGELOG.md
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
Labels: size/M

#4970 Make querier_sharding_test less brittle
  integration/querier_sharding_test.go
Labels: size/M

#4987 Upgrade build image to use go 1.19.3
  build-image/Dockerfile
Labels: size/XS

#4988 Build Cortex with go 1.19.3
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
Labels: size/S

#4972 Add active series to all user stats page
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/http_admin.go
  pkg/distributor/http_server.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: size/M

#4994 Try out dependantbot auto dependencies update
  .github/dependabot.yml
Labels: size/S

#5001 Combine upgrade-golang-version with update the build image
  docs/contributing/how-to-update-the-build-image.md
  docs/contributing/how-to-upgrade-golang-version.md
Labels: size/S

#4976 limit get series API call time range when start param is not specified
  CHANGELOG.md
  docs/api/_index.md
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/L

#5005 Log query params in query frontend when error
  CHANGELOG.md
  pkg/frontend/transport/handler.go
Labels: size/M

#5006 Add note about thanos downsampled block migration
  cmd/thanosconvert/main.go
  docs/blocks-storage/migrate-storage-from-thanos-and-prometheus.md
  pkg/querier/block.go
  tools/thanosconvert/thanosconvert.go
Labels: size/S
