Repository cortexproject/cortex, pull requests merged in 2022-03, with the labels that each got.

#4499 pkg/ruler: Add external_labels option
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/manager.go
  pkg/ruler/notifier.go
  pkg/ruler/notifier_test.go
  pkg/ruler/ruler.go
  tools/doc-generator/parser.go
Labels: size/M

#4663 [Release 1.11] Update to Go v1.16.15
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
Labels: size/S

#4664 Release 1.11.1
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
Labels: size/XS

#4671 Fix broadcast of messages larger than 64KB
  go.mod
  go.sum
  integration/integration_memberlist_single_binary_test.go
  vendor/github.com/hashicorp/memberlist/net.go
  vendor/github.com/hashicorp/memberlist/state.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/modules.txt
Labels: size/XS

#4655 Start release 1.12
  CHANGELOG.md
  VERSION
Labels: size/XS

#4652 Avoid leaking secrets on /config HTTP API endpoint
  integration/alertmanager_test.go
  integration/s3_storage_client_test.go
  pkg/chunk/aws/s3_storage_client.go
  pkg/chunk/aws/s3_storage_client_test.go
  pkg/ring/kv/consul/client.go
Labels: size/M

#4695 Start release 1.12
  VERSION
Labels: size/XS

#4696 Release 1.12
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  VERSION
  build-image/Dockerfile
  go.mod
  go.sum
  integration/integration_memberlist_single_binary_test.go
  vendor/github.com/hashicorp/memberlist/net.go
  vendor/github.com/hashicorp/memberlist/state.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/modules.txt
Labels: size/S

#4699 Small typo
  CHANGELOG.md
Labels: size/XS
