Repository cortexproject/cortex, pull requests merged in 2022-05, with the labels that each got.

#4726 Step down from maintainer
  MAINTAINERS
Labels: size/XS

#4730 Add Friedrich Gonzalez as maintainer
  MAINTAINERS
Labels: size/XS

#4731 Update how to add maintainer
  docs/contributing/how-to-add-a-maintainer.md
Labels: size/XS

#4732 Update community meetings information
  README.md
  docs/contributing/how-to-add-a-maintainer.md
Labels: size/XS

#4737 Include changelog number for #4499 #4601 #4707 #4708
  CHANGELOG.md
Labels: size/XS

#4739 Fix memory leak in distributor due to cluster label
  CHANGELOG.md
  pkg/distributor/ha_tracker.go
  pkg/util/strings.go
Labels: size/S

#4665 test: use `T.TempDir` to create temporary test directory
  pkg/alertmanager/alertstore/local/store_test.go
  pkg/alertmanager/multitenant_test.go
  pkg/chunk/local/boltdb_index_client_test.go
  pkg/chunk/local/fs_object_client_test.go
  pkg/chunk/storage/factory_test.go
  pkg/compactor/compactor_test.go
  pkg/ingester/flush_test.go
  pkg/ingester/ingester_test.go
  pkg/ingester/ingester_v2_test.go
  pkg/ingester/wal_test.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/querier/chunk_tar_test.go
  pkg/querier/querier_test.go
  pkg/ruler/api_test.go
  pkg/ruler/lifecycle_test.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulestore/local/local_test.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway_test.go
  pkg/util/process/collector_test.go
  pkg/util/tls/test/tls_integration_test.go
  pkg/util/tls/tls_test.go
  tools/blocksconvert/builder/series_test.go
  tools/blocksconvert/builder/tsdb_test.go
  tools/blocksconvert/scanner/scanner_test.go
Labels: size/XL

#4729 Upload blocks no compaction marks to the global location and introduce a new `cortex_bucket_blocks_marked_for_no_compaction_count` metric
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor_test.go
  pkg/storage/tsdb/bucketindex/markers.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_test.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storage/tsdb/testutil/block_mock.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/metadata_fetcher_filters_test.go
Labels: size/L

#4725 Add streaming for ingester metadata APIs
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/cortex_util.go
  pkg/ingester/client/cortex_util_test.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_v2.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
Labels: size/XL

#4743 Add notice for chunk storage removal
  README.md
  docs/chunks-storage/_index.md
Labels: size/S

#4741 Re-enable proxy_url for alertmanager receivers
  CHANGELOG.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
Labels: size/S
