Repository cortexproject/cortex, pull requests merged in 2022-10, with the labels that each got.

#4890 Templates in use are being removed by alertmanager cleanup logic
  CHANGELOG.md
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/local/store_test.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#4891 Cheery pick fix for issue #4888
  CHANGELOG.md
  VERSION
  docs/chunks-storage/running-chunks-storage-with-cassandra.md
  pkg/alertmanager/alertstore/local/store.go
  pkg/alertmanager/alertstore/local/store_test.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#4893 Upgrade fpm image
  Makefile
  packaging/fpm/Dockerfile
Labels: size/XS

#4875 [Vote] Governance update around maintainership
  GOVERNANCE.md
Labels: size/S

#4898 Enhance Traces with pod information
  CHANGELOG.md
  pkg/tracing/tracing.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/doc.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/exception.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/http.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/resource.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/schema.go
  vendor/go.opentelemetry.io/otel/semconv/v1.10.0/trace.go
  vendor/modules.txt
Labels: size/M

#4901 Add Emeritus Maintainer section to README
  README.md
Labels: size/XS

#4897 Enable AWS SDK for go authentication to fix IMDSv1 issue
  CHANGELOG.md
  pkg/storage/bucket/s3/bucket_client.go
Labels: size/XS

#4902 Remove default config from getting started examples
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-local.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
Labels: size/S

#4909 preallocate memory
  pkg/ruler/rulestore/configdb/store.go
Labels: size/XS

#4905 Improve the limits docs
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/S

#4913 Updated the README to Reference Kubecon talks!
  README.md
Labels: size/XS

#4914 Updated to have Kubecon NA Talks!
  docs/_index.md
Labels: size/XS

#4906 Cache user overrides in `distributor.Push` to reduce lock contention.
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/util/validation/limits.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/L

#4920 update function signature to use v1.QueryEngine
  pkg/api/handlers.go
  pkg/cortex/cortex.go
  pkg/querier/querier.go
  pkg/ruler/compat.go
Labels: size/M

#4919 New Emeritus maintainers
  MAINTAINERS
  README.md
Labels: size/XS

#4889 chore: make grpc compression configurable for store gateway and alertmanager client
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager_client.go
  pkg/querier/store_gateway_client.go
Labels: size/M

#4929 chore: Update Thanos
  go.mod
  go.sum
  pkg/querier/tripperware/test_shard_by_query_utils.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go
  vendor/modules.txt
Labels: size/XS

#4882 Update proposal for timeseries partitioning in compactor
  docs/proposals/timeseries-partitioning-in-compactor.md
Labels: size/L

#4921 treat interrupted compactions different than failures
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/M

#4935 Enable PromQL `@` modifier always
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/querier/querier.go
Labels: size/M

#4939 Update deprecated flag metric name in doc
  docs/configuration/v1-guarantees.md
Labels: size/XS

#4934 Remove duplicate log message
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: size/XS

#4942 Set github token permission default to read-all
  .github/workflows/test-build-deploy.yml
Labels: size/XS

#4918 Make cortex_bucket_store_blocks_loaded metric per user
  CHANGELOG.md
  integration/getting_started_with_gossiped_ring_test.go
  integration/querier_test.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores_test.go
Labels: size/M
