Repository cortexproject/cortex, pull requests merged in 2023-11, with the labels that each got.

#5627 Fix querier limiter bug under multiselect
  CHANGELOG.md
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
Labels: size/L

#5624 Add new TSDB metrics from Prometheus
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#5630 Update go version to 1.21.3
  .github/workflows/test-build-deploy.yml
  Makefile
  build-image/Dockerfile
Labels: size/S

#5631 Fix flaky TestQueryFrontendNoRetryChunkPool test
  integration/query_frontend_test.go
Labels: size/XS

#5632 Prepare 1.16.0 release
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#5637 Merge release 1.15 to master
  CHANGELOG.md
  VERSION
Labels: size/S

#5638 add/support enabled_tenants and disabled_tenants feature in storegateway
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storegateway/bucket_index_metadata_fetcher_test.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
  pkg/storegateway/sharding_strategy.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/L

#5639 Prepare 1.16.0-rc release
  CHANGELOG.md
  VERSION
Labels: size/M

#5644 chore: pkg import only once
  pkg/configs/db/postgres/postgres.go
  pkg/cortexpb/compat_test.go
  pkg/querier/batch/batch.go
  pkg/querier/worker/frontend_processor.go
  pkg/ring/lifecycler.go
  pkg/util/log/log.go
  pkg/util/log/wrappers.go
Labels: size/M

#5643 Log rule group info prior to rule group evaluation
  pkg/ruler/manager.go
Labels: size/S

#5619 Replace inmemory index cache to fastcache based implementation
  CHANGELOG.md
  go.mod
  go.sum
  integration/querier_test.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/inmemory_index_cache.go
  pkg/storage/tsdb/inmemory_index_cache_test.go
  pkg/storage/tsdb/multilevel_cache_test.go
  vendor/github.com/VictoriaMetrics/fastcache/LICENSE
  vendor/github.com/VictoriaMetrics/fastcache/README.md
  vendor/github.com/VictoriaMetrics/fastcache/bigcache.go
  vendor/github.com/VictoriaMetrics/fastcache/fastcache.go
  vendor/github.com/VictoriaMetrics/fastcache/file.go
  vendor/github.com/VictoriaMetrics/fastcache/malloc_heap.go
  vendor/github.com/VictoriaMetrics/fastcache/malloc_mmap.go
  vendor/modules.txt
Labels: size/XL

#5477 Add cortex_ingester_tsdb_data_replay_duration_seconds metric
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/S

#5653 Skip listing rule groups in CreateRuleGroup api if max rule groups limit is not set
  pkg/ruler/api.go
  pkg/ruler/ruler.go
Labels: size/S

#5645 Upgrade objstore and change Azure bucket client
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/bucket/azure/bucket_client.go
  pkg/storage/bucket/azure/config.go
  pkg/storage/bucket/azure/config_test.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/core.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/exported/exported.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/constants.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/internal/shared/shared.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/policy/policy.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/pager.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_bearer_token.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_http_header.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_include_response.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_key_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_retry.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/policy_sas_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/request.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/transport_default_dialer_other.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/transport_default_dialer_wasm.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime/transport_default_http_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azidentity.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_assertion_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_certificate_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/client_secret_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/confidential_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/device_code_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/errors.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/interactive_browser_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/on_behalf_of_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/public_client.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/syncer.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-pre.ps1
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources.bicep
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/username_password_credential.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
  vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/workload_identity.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/providers/azure/helpers.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/modules.txt
Labels: size/L

#5655 Fix param_query omitted in query frontend query stats log
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
Labels: size/M

#5656 Add querier.max-subquery-steps to make subquery step size check optional
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/query_frontend_test.go
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
Labels: size/M

#5657 Cherrypick commits to release 1.16 for new RC
  CHANGELOG.md
  VERSION
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/query_frontend_test.go
  pkg/cortex/modules.go
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/querier.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
Labels: size/L

#5658 Ready for 1.16.0 release
  CHANGELOG.md
  VERSION
Labels: size/XS

#5660 Merge release 1.16 to master
  CHANGELOG.md
  VERSION
Labels: size/M

#5661 Make multilevel cache backfilling async
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/async_op.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/redis_client.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go
  vendor/github.com/thanos-io/thanos/pkg/extkingpin/path_content_reloader.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/modules.txt
Labels: size/L

#5679 Fix distributor sends native histograms
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/M

#5670 Fix async backfill loop issue
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
Labels: size/L

#5676 Move tenant-deletion-mark to a global dir
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor_test.go
  pkg/purger/tenant_deletion_api_test.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storage/tsdb/tenant_deletion_mark_test.go
  pkg/storage/tsdb/users_scanner.go
  pkg/storage/tsdb/users_scanner_test.go
  pkg/util/allowed_tenants.go
Labels: size/L

#5684 Upgrade Alpine to 3.18
  CHANGELOG.md
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
  packaging/fpm/Dockerfile
Labels: size/S

#5685 increase patch version for google.golang.org/grpc
  go.mod
  go.sum
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XS

#5683 Add compactor start duration in seconds metric
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/M

#5605 Query priority
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/frontend/config.go
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_test.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/limits.go
  pkg/querier/tripperware/priority.go
  pkg/querier/tripperware/priority_test.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
  pkg/scheduler/queue/user_request_queue.go
  pkg/scheduler/queue/user_request_queue_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
  pkg/util/http.go
  pkg/util/httpgrpcutil/header.go
  pkg/util/priority_queue.go
  pkg/util/priority_queue_test.go
  pkg/util/time.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  tools/doc-generator/parser.go
Labels: size/XXL

#5686 Improve async processor handling enabled items, optimize code further
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
Labels: size/L

#5688 Log traceID when it is a OTEL span
  pkg/util/log/wrappers.go
Labels: size/S
