Repository cortexproject/cortex, pull requests merged in 2023-03, with the labels that each got.

#5190 fixed data race check in querier/tripperware/
  pkg/querier/tripperware/test_shard_by_query_utils.go
Labels: size/XS

#5159 Update Dockerfile
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
  docs/contributing/how-to-update-the-build-image.md
  docs/contributing/how-to-upgrade-golang-version.md
  go.mod
  go.sum
  integration/ruler_test.go
  pkg/ingester/instance_limits.go
  pkg/querier/iterators/compatibe_chunk_iterator.go
  pkg/ring/kv/dynamodb/client_test.go
  pkg/ring/kv/dynamodb/dynamodb.go
  pkg/ruler/compat.go
  pkg/util/allowed_tenants_test.go
  vendor/go4.org/unsafe/assume-no-moving-gc/assume-no-moving-gc.go
  vendor/go4.org/unsafe/assume-no-moving-gc/untested.go
  vendor/modules.txt
Labels: size/M

#5191 reorder cortex config reference
  docs/configuration/config-file-reference.md
  tools/doc-generator/main.go
Labels: size/XXL

#5192 Decrease log level for ingester partial failure
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: size/XS

#5188 Fixed issue that shuffle sharding planner return error if block is under visit by other compactor
  CHANGELOG.md
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
Labels: size/XS

#5193 Reuse write request from distributor to Ingesters
  CHANGELOG.md
  pkg/cortexpb/slicesPool.go
  pkg/cortexpb/slicesPool_test.go
  pkg/cortexpb/timeseries.go
  pkg/cortexpb/timeseries_test.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/client.go
Labels: size/L

#5202 Fix read reader multiple times in QFE
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/frontend/transport/handler.go
Labels: size/M

#5198 Add fetched samples and chunks count into querier stats
  CHANGELOG.md
  pkg/distributor/query.go
  pkg/frontend/transport/handler.go
  pkg/ingester/client/custom.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
Labels: size/L

#5200 Add query fuzz test with promqlsmith
  .github/workflows/test-build-deploy.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  integration/e2e/db/db.go
  integration/e2e/util.go
  integration/query_fuzz_test.go
  vendor/github.com/cortexproject/promqlsmith/.gitignore
  vendor/github.com/cortexproject/promqlsmith/.go-version
  vendor/github.com/cortexproject/promqlsmith/.golangci.yml
  vendor/github.com/cortexproject/promqlsmith/LICENSE
  vendor/github.com/cortexproject/promqlsmith/Makefile
  vendor/github.com/cortexproject/promqlsmith/README.md
  vendor/github.com/cortexproject/promqlsmith/promqlsmith.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: size/L

#5208 Update promqlsmith version
  go.mod
  go.sum
  integration/query_fuzz_test.go
  vendor/github.com/cortexproject/promqlsmith/README.md
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/promqlsmith.go
  vendor/modules.txt
Labels: size/S

#5213 Implement grpc.Compressor.DecompressedSize for snappy to optimize memory allocations
  CHANGELOG.md
  pkg/util/grpcencoding/snappy/snappy.go
Labels: size/S

#5217 Fix S3 BucketWithRetries upload empty content issue
  CHANGELOG.md
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
Labels: type/bug, size/L

#5221 Update Thanos
  CHANGELOG.md
  go.mod
  go.sum
  pkg/storegateway/gateway_test.go
  vendor/github.com/thanos-io/thanos/pkg/extkingpin/flags.go
  vendor/github.com/thanos-io/thanos/pkg/extprom/http/instrument_server.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/custom.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/prompb/samples.go
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go
  vendor/modules.txt
Labels: size/S

#5223 Fix changelog order to be CFEB
  CHANGELOG.md
Labels: size/M

#5224 Fix nil error got returned when there was error after retry
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
Labels: size/M

#5225 Fail query fuzzer test if inconsistent
  integration/query_fuzz_test.go
Labels: size/XS

#5215 Implementing Snappy Block Encoding
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/util/grpcclient/grpcclient.go
  pkg/util/grpcencoding/encoding_test.go
  pkg/util/grpcencoding/snappy/snappy.go
  pkg/util/grpcencoding/snappy/snappy_test.go
  pkg/util/grpcencoding/snappyblock/snappyblock.go
  pkg/util/grpcencoding/zstd/zstd.go
Labels: size/L

#4964 Support out of order samples ingestion
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/series.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
  pkg/util/validation/limits.go
Labels: size/L

#5227 Add build info API to doc
  docs/api/_index.md
Labels: size/L

#5234 [chore] Update prometheus to bring in compactor improvements
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/model/labels/labels.go
  vendor/github.com/prometheus/prometheus/model/labels/labels_string.go
  vendor/github.com/prometheus/prometheus/prompb/types.pb.go
  vendor/github.com/prometheus/prometheus/prompb/types.proto
  vendor/github.com/prometheus/prometheus/scrape/scrape.go
  vendor/github.com/prometheus/prometheus/scrape/target.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/codec.go
  vendor/github.com/prometheus/prometheus/tsdb/chunkenc/chunk.go
  vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go
  vendor/github.com/prometheus/prometheus/tsdb/chunks/head_chunks.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/head_append.go
  vendor/github.com/prometheus/prometheus/tsdb/head_read.go
  vendor/github.com/prometheus/prometheus/tsdb/querier.go
  vendor/modules.txt
Labels: size/XS

#5235 prepare 1.15 release
  CHANGELOG.md
  VERSION
Labels: size/S

#5239 Store Gateway: Convert metrics from summary to histograms
  CHANGELOG.md
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
Labels: size/L

#5240 Catch context error in the s3 bucket client
  CHANGELOG.md
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
Labels: size/S

#5233 Add unit test for resolveConflicts function
  pkg/ring/model_test.go
Labels: size/M
