Repository cortexproject/cortex, pull requests merged in 2023-12, with the labels that each got.

#5690 Fix compactor test
  pkg/compactor/compactor_test.go
Labels: size/S

#5698 Do not count 404 errors when checking if tenant deletion markers exists
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/ingester/ingester_test.go
  pkg/purger/tenant_deletion_api.go
  pkg/purger/tenant_deletion_api_test.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storage/tsdb/tenant_deletion_mark_test.go
  pkg/storage/tsdb/testutil/objstore.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
Labels: size/L

#5691 Fix cleaner not discovering deleted users from global dir
  pkg/compactor/compactor_test.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/storage/tsdb/users_scanner.go
  pkg/storage/tsdb/users_scanner_test.go
  tools/thanosconvert/thanosconvert_test.go
Labels: size/M

#5682 use caching bucket for compactor, except cleaner
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storegateway/bucket_stores.go
Labels: size/L

#5694 Remove unused tombstones loader and cache gen code
  integration/querier_tenant_federation_test.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
  pkg/api/middlewares.go
  pkg/chunk/cache/cache_gen.go
  pkg/chunk/cache/cache_gen_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/purger/tombstones.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/series/series_set.go
  pkg/querier/series/series_set_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
  pkg/ruler/ruler_test.go
Labels: size/XL

#5704 fix query priority throws 5xx when 4xx
  pkg/querier/tripperware/priority.go
  pkg/querier/tripperware/priority_test.go
  pkg/querier/tripperware/roundtrip.go
Labels: size/M

#5705 Expose query priority enabled and default priority to cli flags
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/XS

#5687 Clean up older compatibility test images
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/S

#5703 Log split queries at query frontend
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/frontend/transport/roundtripper.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
Labels: size/M

#5708 Upgrade Thanos version to commit fc1a6edf7acc82ec21ebc9fd641ce7afc4fe…
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/rules/rulespb/rpc.proto
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/tracing_index_cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/modules.txt
Labels: size/XS

#5712 filter out blocks marked for deletion in the bucket index ids fetcher…
  pkg/compactor/compactor.go
  pkg/storage/tsdb/bucketindex/block_ids_fetcher.go
  pkg/storage/tsdb/bucketindex/block_ids_fetcher_test.go
Labels: size/S

#5717 Filter empty labels from sharding key
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/M

#5719 Query Frontend: queries with negative offset should check whether it is cacheable or not
  CHANGELOG.md
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
Labels: size/M
