Repository cortexproject/cortex, pull requests merged in 2023-02, with the labels that each got.

#5117 fix response status code panic
  pkg/frontend/transport/handler.go
Labels: size/XS

#5116 Support enabled_tenants and disabled_tenants in alertmanager
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#5119 Fix Segmentation fault on ingester due race condition when reading blocks that are being deleted
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: size/L

#5118 query frontend: get error message from response body if err is nil
  pkg/frontend/transport/handler.go
Labels: size/M

#5080 Make TSDB max exemplars config per tenant
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/runtime-config.yaml
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/storage/tsdb/config.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#5122 Rename max exemplars limit flag to ingester.max-exemplars.
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
Labels: size/XS

#5132 Update Dockerfiles to use Alpine 3.17
  CHANGELOG.md
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
  packaging/fpm/Dockerfile
Labels: size/S

#5136 Dynamodb kv batch on slices
  CHANGELOG.md
  pkg/ring/kv/dynamodb/client.go
  pkg/ring/kv/dynamodb/dynamodb.go
  pkg/ring/kv/dynamodb/dynamodb_test.go
Labels: size/L

#5140 Fix conflict schema url when initializing resources
  pkg/tracing/tracing.go
  pkg/tracing/tracing_test.go
Labels: size/M

#5141 Using otel tracer sampler
  CHANGELOG.md
  pkg/tracing/sampler/sampling.go
  pkg/tracing/sampler/sampling_test.go
  pkg/tracing/tracing.go
Labels: size/L

#5138 Remove Weave cloud and Grafana Cloud Reference from docs page
  docs/_index.md
Labels: component/documentation, size/S

#5142 initialize querier stats in QFE only if it is not enabled
  pkg/frontend/transport/handler.go
Labels: size/S

#5057 Add redis as index cache and caching bucket backend
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/config-file-reference.md
  integration/e2e/cache/cache.go
  integration/e2e/images/images.go
  integration/querier_test.go
  pkg/cortexpb/compat_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/redis_client_config.go
  pkg/storage/tsdb/redis_client_config_test.go
Labels: size/XXL

#5148 Fix sorted queries do not produce sorted results for shardable queries
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/split_by_interval.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
  pkg/querier/tripperware/shard_by.go
Labels: size/L

#5164 Update README.md for chunk deprecation note
  README.md
Labels: size/XS

#5167 Disable `ValidateJsonRawMessage` flag from jsoniter
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/queryrange/query_range.go
Labels: size/XS

#5166 StoreGateway: Allow filtering out recent blocks during sync
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/querier/blocks_finder_bucket_index.go
  pkg/querier/blocks_finder_bucket_index_test.go
  pkg/querier/blocks_finder_bucket_scan.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/metadata_fetcher_filters.go
  pkg/storegateway/metadata_fetcher_filters_test.go
Labels: size/L

#5169 Fix returning 5XX for limits errors in series API
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/S

#5170 Fix the incorrect ordering for topk and bottomk in shardable queries
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
Labels: size/L

#5173 remove unnecessary sprintf
  pkg/util/limiter/query_limiter.go
Labels: size/XS

#5176 Add a trace span for merging series from ingesters
  pkg/distributor/query.go
Labels: size/XS

#5135 Retry logic for S3 bucket client
  CHANGELOG.md
  pkg/storage/bucket/s3/bucket_client.go
Labels: size/L
