Repository cortexproject/cortex, pull requests merged in 2023-10, with the labels that each got.

#5581 add context timeout for waitInstanceState call for alertmanager and s…
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager_ring.go
  pkg/alertmanager/multitenant.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#5587 Support filtered index cache
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/index_cache_test.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/parallel_bucket.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/filter_cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go
  vendor/github.com/thanos-io/thanos/pkg/tenancy/tenancy.go
  vendor/modules.txt
Labels: size/L

#5592 Add AM aggregation group metrics
  CHANGELOG.md
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
Labels: size/M

#5594 Fix log message missing key field
  pkg/ring/kv/dynamodb/client.go
  pkg/tracing/tracing.go
Labels: size/XS

#5598 Update thanos version to latest main branch
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/httpconfig/http.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/XS

#5604 Add contextual information and query statistics to log
  CHANGELOG.md
  pkg/ruler/compat.go
Labels: size/M

#5608 Upgrade thanos to latest main
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy.go
  vendor/modules.txt
Labels: size/XS

#5612 upgrade thanos to latest main
  go.mod
  go.sum
  vendor/github.com/thanos-io/promql-engine/execution/storage/filter.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/modules.txt
Labels: size/S

#5609 Add metric to measure rule group load time
  CHANGELOG.md
  pkg/ruler/ruler.go
Labels: size/M

#5596 Multi level cache: check context add latency histogram
  CHANGELOG.md
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
Labels: size/M

#5618 Upgrade go version to 1.21.0
  .github/workflows/test-build-deploy.yml
  Makefile
  build-image/Dockerfile
  cmd/cortex/main.go
  go.mod
  go.sum
  pkg/ring/ring_test.go
  pkg/storegateway/gateway_test.go
  pkg/util/grpcencoding/encoding_test.go
  pkg/util/metrics_helper_test.go
  pkg/util/tls/test/tls_integration_test.go
Labels: size/L

#5617 upgrade thanos to latest main
  go.mod
  go.sum
  pkg/querier/blocks_consistency_checker_test.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storegateway/gateway_test.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/extprom/http/instrument_tenant_server.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analysis.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analyzer.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go
  vendor/modules.txt
Labels: size/L

#5622 Put query field at the end of query stats log
  pkg/frontend/transport/handler.go
Labels: size/S

#5625 Ingester: Always upload compacted blocks
  CHANGELOG.md
  pkg/ingester/ingester.go
Labels: size/XS
