Repository cortexproject/cortex, pull requests merged in 2023-08, with the labels that each got.

#5493 feat(alertmanager): add support for webex,discord,telegram receivers
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/util/validation/notifications_limit_flag.go
  vendor/github.com/prometheus/alertmanager/notify/discord/discord.go
  vendor/github.com/prometheus/alertmanager/notify/telegram/telegram.go
  vendor/github.com/prometheus/alertmanager/notify/webex/webex.go
  vendor/gopkg.in/telebot.v3/.gitignore
  vendor/gopkg.in/telebot.v3/LICENSE
  vendor/gopkg.in/telebot.v3/README.md
  vendor/gopkg.in/telebot.v3/admin.go
  vendor/gopkg.in/telebot.v3/api.go
  vendor/gopkg.in/telebot.v3/bot.go
  vendor/gopkg.in/telebot.v3/callback.go
  vendor/gopkg.in/telebot.v3/chat.go
  vendor/gopkg.in/telebot.v3/commands.go
  vendor/gopkg.in/telebot.v3/context.go
  vendor/gopkg.in/telebot.v3/editable.go
  vendor/gopkg.in/telebot.v3/errors.go
  vendor/gopkg.in/telebot.v3/file.go
  vendor/gopkg.in/telebot.v3/game.go
  vendor/gopkg.in/telebot.v3/inline.go
  vendor/gopkg.in/telebot.v3/inline_types.go
  vendor/gopkg.in/telebot.v3/input_types.go
  vendor/gopkg.in/telebot.v3/markup.go
  vendor/gopkg.in/telebot.v3/media.go
  vendor/gopkg.in/telebot.v3/message.go
  vendor/gopkg.in/telebot.v3/middleware.go
  vendor/gopkg.in/telebot.v3/options.go
  vendor/gopkg.in/telebot.v3/payments.go
  vendor/gopkg.in/telebot.v3/payments_data.go
  vendor/gopkg.in/telebot.v3/poll.go
  vendor/gopkg.in/telebot.v3/poller.go
  vendor/gopkg.in/telebot.v3/sendable.go
  vendor/gopkg.in/telebot.v3/stickers.go
  vendor/gopkg.in/telebot.v3/telebot.go
  vendor/gopkg.in/telebot.v3/update.go
  vendor/gopkg.in/telebot.v3/video_chat.go
  vendor/gopkg.in/telebot.v3/web_app.go
  vendor/gopkg.in/telebot.v3/webhook.go
  vendor/modules.txt
Labels: size/M

#5489 StoreGateway: fix store gateway shuffle sharding consistency issue when shard size change by 1
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/blocks-storage/store-gateway.template
  docs/configuration/v1-guarantees.md
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
  pkg/ring/util_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_ring.go
  pkg/storegateway/sharding_strategy.go
  pkg/storegateway/sharding_strategy_test.go
Labels: size/XL

#5499 Query Frontend: Handle context error before decoding and merging responses
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/results_cache.go
Labels: size/L

#5503 allow compactor unregisteronshutdown to be configurable
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor_ring.go
Labels: size/S

#5496 Re-enqueue 429 requests if there are multiple query-schedulers
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_scheduler_worker.go
Labels: size/M

#5504 Update thanos version to latest main
  go.mod
  go.sum
  pkg/querier/tripperware/test_shard_by_query_utils.go
  vendor/github.com/redis/rueidis/README.md
  vendor/github.com/redis/rueidis/client.go
  vendor/github.com/redis/rueidis/cluster.go
  vendor/github.com/redis/rueidis/cmds.go
  vendor/github.com/redis/rueidis/docker-compose.yml
  vendor/github.com/redis/rueidis/helper.go
  vendor/github.com/redis/rueidis/internal/cmds/builder.go
  vendor/github.com/redis/rueidis/internal/util/parallel.go
  vendor/github.com/redis/rueidis/message.go
  vendor/github.com/redis/rueidis/mux.go
  vendor/github.com/redis/rueidis/pipe.go
  vendor/github.com/redis/rueidis/resp.go
  vendor/github.com/redis/rueidis/ring.go
  vendor/github.com/redis/rueidis/rueidis.go
  vendor/github.com/redis/rueidis/sentinel.go
  vendor/github.com/thanos-io/thanos/pkg/querysharding/analysis.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/internal/event/tag/tag.go
  vendor/golang.org/x/tools/internal/gcimporter/bexport.go
  vendor/golang.org/x/tools/internal/gcimporter/bimport.go
  vendor/golang.org/x/tools/internal/gcimporter/gcimporter.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gcimporter/ureader_yes.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: size/M

#5502 if no change detected, retry
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/dynamodb/client.go
  pkg/ring/kv/dynamodb/client_test.go
  pkg/ring/kv/dynamodb/metrics.go
Labels: size/M

#5509 need to set return consumed capacity in input
  pkg/ring/kv/dynamodb/dynamodb.go
Labels: size/S

#5511 Fix Cortex Tools reference in docs
  docs/guides/alert-manager-configuration.md
Labels: size/XS

#5506 Add index stats info to bucket index
  CHANGELOG.md
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/bucketindex/index_test.go
Labels: size/M

#5515 Update Thanos objsstore
  go.mod
  go.sum
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/prefixed_bucket_client.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
  pkg/storage/bucket/sse_bucket_client.go
  pkg/storage/bucket/sse_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/testutil/objstore.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/README.md
  vendor/github.com/thanos-io/objstore/inmem.go
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/prefixed_bucket.go
  vendor/github.com/thanos-io/objstore/providers/azure/azure.go
  vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
  vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/objstore/providers/swift/swift.go
  vendor/github.com/thanos-io/objstore/testing.go
  vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go
  vendor/modules.txt
Labels: size/L

#5519 Fix sync bucket index status
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
Labels: size/M

#5518 Update GitHub wording in navbar
  website/layouts/partials/navbar.html
Labels: size/XS

#5524 Adding the userId on the compact dir path
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/M

#5526 Refactor to avoid keep the "limits override" 2 times on compactor
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/cortex/modules.go
Labels: size/S

#5528 Add support for Limit field on RuleGroup which got introduced in https://github.com/prometheus/prometheus/pull/9260
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/ruler.go
  pkg/ruler/rulespb/compat.go
  pkg/ruler/rulespb/rules.pb.go
  pkg/ruler/rulespb/rules.proto
  pkg/ruler/store_mock_test.go
Labels: size/M

#5532 Add new metric for store gateway chunk refetches
  CHANGELOG.md
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
Labels: size/S

#5517 add configurable final-sleep time for basic lifecycler
  CHANGELOG.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/alertmanager/alertmanager_ring.go
  pkg/alertmanager/multitenant_test.go
  pkg/ring/basic_lifecycler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_test.go
  pkg/storegateway/gateway_ring.go
Labels: size/M

#5535 Fix possible division by zero during compactor config validation
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
Labels: size/S

#5533 Add feature flag to enable build info API
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/api/handlers_test.go
Labels: size/M

#5540 Updating Minio
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/minio/minio-go/v7/api-putobject-snowball.go
  vendor/github.com/minio/minio-go/v7/api.go
  vendor/github.com/minio/minio-go/v7/pkg/credentials/iam_aws.go
  vendor/github.com/minio/minio-go/v7/pkg/replication/replication.go
  vendor/github.com/minio/minio-go/v7/pkg/s3utils/utils.go
  vendor/modules.txt
Labels: size/XS

#5543 Update alertmanager version and memberlist version
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_http_test.go
  pkg/alertmanager/multitenant.go
  pkg/util/validation/notifications_limit_flag.go
  vendor/github.com/benbjohnson/clock/clock.go
  vendor/github.com/hashicorp/memberlist/config.go
  vendor/github.com/hashicorp/memberlist/label.go
  vendor/github.com/hashicorp/memberlist/memberlist.go
  vendor/github.com/hashicorp/memberlist/net.go
  vendor/github.com/hashicorp/memberlist/peeked_conn.go
  vendor/github.com/hashicorp/memberlist/queue.go
  vendor/github.com/hashicorp/memberlist/security.go
  vendor/github.com/hashicorp/memberlist/state.go
  vendor/github.com/hashicorp/memberlist/transport.go
  vendor/github.com/hashicorp/memberlist/util.go
  vendor/github.com/prometheus/alertmanager/asset/assets_vfsdata.go
  vendor/github.com/prometheus/alertmanager/cluster/cluster.go
  vendor/github.com/prometheus/alertmanager/cluster/tls_config.go
  vendor/github.com/prometheus/alertmanager/cluster/tls_transport.go
  vendor/github.com/prometheus/alertmanager/config/config.go
  vendor/github.com/prometheus/alertmanager/config/notifiers.go
  vendor/github.com/prometheus/alertmanager/notify/msteams/msteams.go
  vendor/github.com/prometheus/alertmanager/notify/notify.go
  vendor/github.com/prometheus/alertmanager/notify/slack/slack.go
  vendor/github.com/prometheus/alertmanager/notify/webhook/webhook.go
  vendor/github.com/prometheus/alertmanager/template/default.tmpl
  vendor/github.com/prometheus/alertmanager/template/email.html
  vendor/github.com/prometheus/alertmanager/template/email.tmpl
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/postings.go
  vendor/modules.txt
Labels: size/M
