Repository cortexproject/cortex, pull requests merged in 2023-07, with the labels that each got.

#5420 Handling CMK AccessDenied errors
  go.mod
  go.sum
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/querier/blocks_finder_bucket_index.go
  pkg/querier/blocks_finder_bucket_index_test.go
  pkg/querier/error_translate_queryable.go
  pkg/querier/error_translate_queryable_test.go
  pkg/storage/bucket/client.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/prefixed_bucket_client.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
  pkg/storage/bucket/sse_bucket_client.go
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/storage_test.go
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storage/tsdb/testutil/objstore.go
  pkg/storage/tsdb/util.go
  pkg/storegateway/bucket_index_metadata_fetcher.go
  pkg/storegateway/bucket_index_metadata_fetcher_test.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/util/errors/errors.go
  pkg/util/validation/limits.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/inmem.go
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/prefixed_bucket.go
  vendor/github.com/thanos-io/objstore/providers/azure/azure.go
  vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
  vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/objstore/providers/swift/swift.go
  vendor/github.com/thanos-io/objstore/testing.go
  vendor/github.com/thanos-io/objstore/tracing.go
  vendor/modules.txt
Labels: size/XL

#5441 fix retry on markers
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/testutil/objstore.go
Labels: size/L

#5380 Unify README.md and docs/_index.md
  README.md
  docs/_index.md
  tools/website/web-pre.sh
Labels: size/L

#5443 Includes known issue in v1.14.0 changelog
  CHANGELOG.md
Labels: size/XS

#5442 Changing return code from storegateway for CMK errors
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storage/bucket/sse_bucket_client.go
  pkg/storage/bucket/sse_bucket_client_test.go
  pkg/storage/tsdb/testutil/objstore.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/util/errors/errors.go
  pkg/util/errors/errors_test.go
Labels: size/L

#5447 Fix query frontend v2 failed to cancel request
  CHANGELOG.md
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_scheduler_worker.go
Labels: size/S

#5450 Query Frontend: log request user agent
  pkg/frontend/transport/handler.go
Labels: size/XS

#5446 Implementing Bucket index sync status file
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/querier/blocks_finder_bucket_index.go
  pkg/querier/blocks_finder_bucket_index_test.go
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/caching_bucket_test.go
  pkg/storage/tsdb/testutil/objstore.go
Labels: size/XL

#5451 Implementing multi level index cache
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/factory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/modules.txt
Labels: size/XL

#5453 Remove user from state key metric value
  CHANGELOG.md
  pkg/alertmanager/alertmanager_metrics.go
  pkg/alertmanager/alertmanager_metrics_test.go
  pkg/alertmanager/state_replication.go
  pkg/alertmanager/state_replication_test.go
Labels: size/L

#5456 add alert name in error log
  CHANGELOG.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_test.go
Labels: size/S

#5459 Updated Thanos to latest
  go.mod
  go.sum
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_planner.go
  pkg/compactor/shuffle_sharding_planner_test.go
  pkg/cortex/tracing.go
  pkg/storage/bucket/client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client_test.go
  pkg/storage/tsdb/bucketindex/markers_test.go
  pkg/storage/tsdb/bucketindex/updater_test.go
  pkg/storage/tsdb/testutil/objstore.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/README.md
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/tracing.go
  vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go
  vendor/github.com/thanos-io/objstore/tracing/tracing.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/block/metadata/meta.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/compact/planner.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/modules.txt
Labels: size/M

#5462 [chore] Update Thanos
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/store/postings_codec.go
  vendor/modules.txt
Labels: size/XS

#5460 Add ingester flag to customize message in limiter error messages
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/limiter.go
  pkg/ingester/limiter_test.go
  pkg/ingester/user_state_test.go
Labels: size/M

#5457 Avoid concurrency cleaners
  CHANGELOG.md
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
Labels: size/M

#5472 Remove deprecated ingester metrics
  pkg/ingester/metrics.go
Labels: size/M

#5475 fix multilevel cache with inmemory and memcached
  integration/querier_test.go
  pkg/storage/tsdb/index_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
Labels: size/M

#5478 Fix flaky integration test of multi level index cache
  integration/e2e/metrics.go
  integration/querier_test.go
Labels: size/S

#5476 Fix querier try store gateways on different zones
  CHANGELOG.md
  pkg/querier/blocks_store_balanced_set.go
  pkg/querier/blocks_store_balanced_set_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/blocks_store_replicated_set.go
  pkg/querier/blocks_store_replicated_set_test.go
  pkg/ring/replication_set.go
Labels: size/L

#5482 Fix flaky on thanos_memcached_operations_total metrics
  integration/e2e/metrics.go
  integration/querier_test.go
Labels: size/M

#5484 Unify subquery step size check in a single place
  pkg/cortex/modules.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/shard_by_query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/roundtrip.go
Labels: size/M

#5486 Backfill lower caches on the multi cache implementation
  integration/querier_test.go
  pkg/storage/tsdb/multilevel_cache.go
  pkg/storage/tsdb/multilevel_cache_test.go
Labels: size/M

#5487 Add Label values Batch, Delete, Put for ddb metrics.
  CHANGELOG.md
  pkg/ring/kv/dynamodb/dynamodb.go
  pkg/ring/kv/dynamodb/dynamodb_test.go
  pkg/ring/kv/dynamodb/metrics.go
Labels: size/M

#5480 disallow instance with older timestamp to update instance with newer …
  CHANGELOG.md
  pkg/ring/basic_lifecycler.go
  pkg/ring/model.go
  pkg/ring/model_test.go
Labels: size/M
