Repository cortexproject/cortex, pull requests merged in 2023-05, with the labels that each got.

#5313 Add cortex 1.15.1 to compatibility test
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#5317 Ignore arm64 and amd64 binaries in .gitignore
  .gitignore
Labels: size/XS

#5303 Support other storage backend options for runtime configuration file
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/configs.go
  integration/runtime_config_test.go
  pkg/cortex/modules.go
  pkg/cortex/runtime_config.go
  pkg/cortex/runtime_config_test.go
  pkg/storage/bucket/client.go
  pkg/util/runtimeconfig/manager.go
  pkg/util/runtimeconfig/manager_test.go
  tools/doc-generator/main.go
Labels: size/XL

#5312 Add user label to ruler query and write metrics
  CHANGELOG.md
  integration/ruler_test.go
  pkg/ruler/compat.go
Labels: size/L

#5299 upgrade to go 1.20.4
  .github/workflows/test-build-deploy.yml
  Makefile
  build-image/Dockerfile
Labels: size/S

#5319 Add span on push for distributor and ingester
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/ingester/ingester.go
  pkg/ring/batch.go
Labels: size/L

#5322 Add additional tracing span for merging labels responses
  pkg/distributor/distributor.go
Labels: size/S

#5323 Reject small subquery step size in query frontend
  CHANGELOG.md
  integration/query_frontend_test.go
  pkg/cortex/modules.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/shard_by_query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/step_align.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/querier/tripperware/subquery.go
  pkg/querier/tripperware/subquery_test.go
Labels: size/L

#5333 Check context done when uploading visit marker
  pkg/compactor/block_visit_marker.go
Labels: size/XS

#5331 Cherry pick "upgrade to Go 1.20.4" from main branch
  .github/workflows/test-build-deploy.yml
  Makefile
  build-image/Dockerfile
Labels: size/S

#5334 Exposing Thanos accept-malformed-index to Cortex compactor
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/shuffle_sharding_grouper.go
Labels: size/S

#5297 Avoid expensive log.Valuer evaluation for disallowed level
  CHANGELOG.md
  pkg/util/log/log.go
  pkg/util/log/log_test.go
Labels: size/M

#5337 Add change log entry for Go runtime upgrade
  CHANGELOG.md
Labels: size/XS

#5340 fix grpc encoding BenchmarkCompress
  pkg/util/grpcencoding/encoding_test.go
Labels: size/XS

#5336 Release and bump version to 1.15.2
  CHANGELOG.md
  VERSION
Labels: size/XS

#5338 Make AM grpc MaxRecvMsgSize and MaxSendMsgSize configurable
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager_client.go
Labels: size/S

#5344 Update README.md
  README.md
Labels: size/S

#5343 Bucket index updater should ignore meta not found for partial blocks
  CHANGELOG.md
  pkg/storage/tsdb/bucketindex/updater.go
  pkg/storage/tsdb/bucketindex/updater_test.go
Labels: size/M

#5347 Improving Performance on the API Gzip Handler
  CHANGELOG.md
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/api_test.go
  vendor/github.com/NYTimes/gziphandler/.gitignore
  vendor/github.com/NYTimes/gziphandler/.travis.yml
  vendor/github.com/NYTimes/gziphandler/CODE_OF_CONDUCT.md
  vendor/github.com/NYTimes/gziphandler/CONTRIBUTING.md
  vendor/github.com/NYTimes/gziphandler/README.md
  vendor/github.com/NYTimes/gziphandler/gzip.go
  vendor/github.com/NYTimes/gziphandler/gzip_go18.go
  vendor/github.com/klauspost/compress/flate/deflate.go
  vendor/github.com/klauspost/compress/flate/dict_decoder.go
  vendor/github.com/klauspost/compress/flate/fast_encoder.go
  vendor/github.com/klauspost/compress/flate/huffman_bit_writer.go
  vendor/github.com/klauspost/compress/flate/huffman_code.go
  vendor/github.com/klauspost/compress/flate/huffman_sortByFreq.go
  vendor/github.com/klauspost/compress/flate/huffman_sortByLiteral.go
  vendor/github.com/klauspost/compress/flate/inflate.go
  vendor/github.com/klauspost/compress/flate/inflate_gen.go
  vendor/github.com/klauspost/compress/flate/level1.go
  vendor/github.com/klauspost/compress/flate/level2.go
  vendor/github.com/klauspost/compress/flate/level3.go
  vendor/github.com/klauspost/compress/flate/level4.go
  vendor/github.com/klauspost/compress/flate/level5.go
  vendor/github.com/klauspost/compress/flate/level6.go
  vendor/github.com/klauspost/compress/flate/regmask_amd64.go
  vendor/github.com/klauspost/compress/flate/regmask_other.go
  vendor/github.com/klauspost/compress/flate/stateless.go
  vendor/github.com/klauspost/compress/flate/token.go
  vendor/github.com/klauspost/compress/gzhttp/LICENSE
  vendor/github.com/klauspost/compress/gzhttp/README.md
  vendor/github.com/klauspost/compress/gzhttp/compress.go
  vendor/github.com/klauspost/compress/gzhttp/transport.go
  vendor/github.com/klauspost/compress/gzhttp/writer/gzkp/gzkp.go
  vendor/github.com/klauspost/compress/gzhttp/writer/interface.go
  vendor/github.com/klauspost/compress/gzip/gunzip.go
  vendor/github.com/klauspost/compress/gzip/gzip.go
  vendor/modules.txt
Labels: size/L

#5348 Use prometheus stable tag
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS

#5171 Refactored distributor HATracker into its own package
  pkg/distributor/distributor.go
  pkg/distributor/distributor_ha_tracker.go
  pkg/distributor/distributor_test.go
  pkg/ha/ha_tracker.go
  pkg/ha/ha_tracker.pb.go
  pkg/ha/ha_tracker.proto
  pkg/ha/ha_tracker_http.go
  pkg/ha/ha_tracker_test.go
  pkg/util/validation/limits.go
Labels: size/XL

#5349 Optimize the decoding of SampleStream
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/query.go
Labels: size/M

#5279 Return a more friendly error message when there is no configuration file
  cmd/cortex/main.go
  cmd/cortex/main_test.go
Labels: size/S

#5350 include query_length field in query stats log
  CHANGELOG.md
  pkg/frontend/transport/handler.go
Labels: size/XS

#5346 Add joining to read operation
  CHANGELOG.md
  pkg/ring/model_test.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/M

#5342 Make sure partial block with only visit marker can be cleaned
  CHANGELOG.md
  pkg/compactor/block_visit_marker.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor_test.go
Labels: size/M

#5351 [chore] Update Thanos
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/cache.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/memcached.go
  vendor/github.com/thanos-io/thanos/pkg/store/opts.go
  vendor/github.com/thanos-io/thanos/pkg/store/telemetry.go
  vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go
  vendor/modules.txt
Labels: size/XS

#5360 Add a per user query counter metric
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
Labels: size/S

#5356 Add metrics for rejected queries in QFE
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
Labels: size/L

#5364 Revert new cortex_queries_total metric
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
Labels: size/S

#5367 Fix a typo
  docs/configuration/config-file-reference.md
  docs/configuration/config-file-reference.template
  website/static/images/architecture.png
Labels: size/XS

#5372 Don't sort get series in ingesters if one matcher set only
  pkg/ingester/ingester.go
Labels: size/M
