Repository cortexproject/cortex, pull requests merged in 2023-09, with the labels that each got.

#5544 Retry WriteIndex on bucketUpload
  pkg/storage/tsdb/bucketindex/storage.go
  pkg/storage/tsdb/bucketindex/storage_test.go
Labels: size/S

#5542 [AlertManager] Handling CMK AccessDenied errors
  CHANGELOG.md
  pkg/alertmanager/alertspb/compat.go
  pkg/alertmanager/alertstore/bucketclient/bucket_client.go
  pkg/alertmanager/alertstore/store_test.go
  pkg/alertmanager/api.go
  pkg/alertmanager/state_replication.go
Labels: size/L

#5550 Making GCInterval Configurable
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanager_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/S

#5551 update bucket sync status when refreshing the cache
  pkg/storage/tsdb/bucketindex/loader.go
  pkg/storage/tsdb/bucketindex/loader_test.go
Labels: size/S

#5552 Creating new metric around chunks bytespool
  CHANGELOG.md
  pkg/storegateway/chunk_bytes_pool.go
  pkg/storegateway/chunk_bytes_pool_test.go
Labels: size/M

#5521 disable rule groups
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/util/validation/limits.go
  tools/doc-generator/parser.go
Labels: size/L

#5556 Update thanos version to bring posting fetch optimization
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  pkg/storegateway/bucket_stores.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/header.go
  vendor/github.com/thanos-io/thanos/pkg/block/indexheader/lazy_binary_reader.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy_heap.go
  vendor/github.com/thanos-io/thanos/pkg/testutil/e2eutil/prometheus.go
  vendor/modules.txt
Labels: size/M

#5557 Small enhancement to doc generator to account for slices
  docs/configuration/config-file-reference.md
  pkg/util/validation/limits.go
  tools/doc-generator/main.go
  tools/doc-generator/parser.go
Labels: size/L

#5553 Add max-inflight-requests limit to store gateway
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/gateway.go
Labels: size/L

#5558 Retry more errors in block storage querier
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/M

#5505 Batch adding series to query limiter to optimize locking
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/query.go
  pkg/util/limiter/query_limiter.go
  pkg/util/limiter/query_limiter_test.go
Labels: size/L

#5561 Add generic retry in query frontend
  CHANGELOG.md
  pkg/cortex/modules.go
  pkg/frontend/config.go
  pkg/frontend/frontend_test.go
  pkg/frontend/transport/retry.go
  pkg/frontend/transport/retry_test.go
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/queue_test.go
  pkg/frontend/v2/frontend.go
  pkg/frontend/v2/frontend_test.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/retry.go
  pkg/querier/tripperware/queryrange/retry_test.go
Labels: size/XL

#5563 Fail to load singe rulegroup cause rulers to halt the sync of all rulegroups.
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/api_test.go
  pkg/ruler/lifecycle_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/ruler/rulestore/bucketclient/bucket_client_test.go
  pkg/ruler/rulestore/configdb/store.go
  pkg/ruler/rulestore/local/local.go
  pkg/ruler/rulestore/store.go
  pkg/ruler/store_mock_test.go
Labels: size/L

#5514 add some logs to ring batch to help debug remotewrite errors from rul…
  pkg/distributor/distributor_test.go
  pkg/ring/batch.go
Labels: size/S

#5570 can not use errors wrap, otherwise httpgrpc error will be converted t…
  pkg/distributor/distributor_test.go
  pkg/ring/batch.go
  pkg/util/httpgrpcutil/errors.go
Labels: size/M

#5373 Track number of get series request requests in QFE
  CHANGELOG.md
  pkg/querier/tripperware/roundtrip.go
Labels: size/XS

#5573 Add more duration info to SG request stats log
  CHANGELOG.md
  go.mod
  go.sum
  pkg/querier/blocks_store_queryable.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
  vendor/github.com/dgryski/go-metro/LICENSE
  vendor/github.com/dgryski/go-metro/README
  vendor/github.com/dgryski/go-metro/metro.py
  vendor/github.com/dgryski/go-metro/metro128.go
  vendor/github.com/dgryski/go-metro/metro64.go
  vendor/github.com/dgryski/go-metro/metro_amd64.s
  vendor/github.com/dgryski/go-metro/metro_stub.go
  vendor/github.com/seiflotfy/cuckoofilter/.gitignore
  vendor/github.com/seiflotfy/cuckoofilter/LICENSE
  vendor/github.com/seiflotfy/cuckoofilter/README.md
  vendor/github.com/seiflotfy/cuckoofilter/bucket.go
  vendor/github.com/seiflotfy/cuckoofilter/cuckoofilter.go
  vendor/github.com/seiflotfy/cuckoofilter/doc.go
  vendor/github.com/seiflotfy/cuckoofilter/scalable_cuckoofilter.go
  vendor/github.com/seiflotfy/cuckoofilter/util.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/README.md
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/providers/azure/azure.go
  vendor/github.com/thanos-io/objstore/providers/azure/helpers.go
  vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/async_op.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/compact/downsample/downsample.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/flushable.go
  vendor/github.com/thanos-io/thanos/pkg/store/hintspb/custom.go
  vendor/github.com/thanos-io/thanos/pkg/store/hintspb/hints.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/hintspb/hints.proto
  vendor/github.com/thanos-io/thanos/pkg/store/prometheus.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy_heap.go
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/github.com/thanos-io/thanos/pkg/stringset/set.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/L

#5569 retry chunk pool exhaustion error in querier, not in query frontend
  integration/query_frontend_test.go
  pkg/frontend/transport/retry.go
  pkg/frontend/transport/retry_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/tripperware/query.go
Labels: size/L

#5575 Do no use tenant key on S3 KMS SSE when uploading deletion marker
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/ingester/ingester_test.go
  pkg/purger/tenant_deletion_api.go
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storage/tsdb/tenant_deletion_mark_test.go
Labels: size/M

#5565 Check context before notifying frontend and scheduler
  CHANGELOG.md
  pkg/querier/worker/scheduler_processor.go
Labels: size/XS
