Repository cortexproject/cortex, pull requests merged in 2023-04, with the labels that each got.

#5241 Cherry-pick fixes to release 1.15 branch
  CHANGELOG.md
  VERSION
  pkg/querier/batch/batch.go
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/batch/merge.go
  pkg/querier/batch/non_overlapping.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
  pkg/storegateway/bucket_store_metrics.go
  pkg/storegateway/bucket_store_metrics_test.go
Labels: size/L

#5242 Fix typos and a grammar error
  docs/contributing/_index.md
  docs/contributing/how-to-update-the-build-image.md
Labels: size/XS

#5249 Fix typo in architecture diagram
  images/architecture.png
Labels: size/XS

#5248 fix compactor unit test error
  pkg/compactor/compactor_test.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/client_test.go
Labels: size/M

#5257 fix remote read error in query frontend
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/frontend/transport/handler.go
Labels: size/L

#5259 Cherry-pick fixes to release 1.15 for new RC
  CHANGELOG.md
  VERSION
  integration/e2ecortex/client.go
  integration/query_frontend_test.go
  pkg/frontend/transport/handler.go
Labels: size/L

#5261 Cherrypick #5260 to release 1.15 branch
  CHANGELOG.md
  integration/query_frontend_test.go
  pkg/frontend/transport/handler.go
  pkg/querier/tripperware/queryrange/split_by_interval.go
Labels: size/M

#5274 Ready for release 1.15.0
  CHANGELOG.md
  VERSION
Labels: size/XS

#5284 Update thanos promql engine to latest
  go.mod
  go.sum
  vendor/github.com/thanos-community/promql-engine/engine/engine.go
  vendor/github.com/thanos-community/promql-engine/execution/aggregate/hashaggregate.go
  vendor/github.com/thanos-community/promql-engine/execution/aggregate/khashaggregate.go
  vendor/github.com/thanos-community/promql-engine/execution/aggregate/scalar_table.go
  vendor/github.com/thanos-community/promql-engine/execution/aggregate/vector_table.go
  vendor/github.com/thanos-community/promql-engine/execution/binary/scalar.go
  vendor/github.com/thanos-community/promql-engine/execution/binary/table.go
  vendor/github.com/thanos-community/promql-engine/execution/binary/vector.go
  vendor/github.com/thanos-community/promql-engine/execution/execution.go
  vendor/github.com/thanos-community/promql-engine/execution/function/functions.go
  vendor/github.com/thanos-community/promql-engine/execution/function/histogram.go
  vendor/github.com/thanos-community/promql-engine/execution/function/operator.go
  vendor/github.com/thanos-community/promql-engine/execution/parse/errors.go
  vendor/github.com/thanos-community/promql-engine/execution/parse/functions.go
  vendor/github.com/thanos-community/promql-engine/execution/scan/matrix_selector.go
  vendor/github.com/thanos-community/promql-engine/execution/step_invariant/step_invariant.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/distribute.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/filter.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/merge_selects.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/plan.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/propagate_selectors.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/sort_matchers.go
  vendor/github.com/thanos-community/promql-engine/logicalplan/trim_sorts.go
  vendor/github.com/thanos-community/promql-engine/parser/ast.go
  vendor/github.com/thanos-community/promql-engine/parser/functions.go
  vendor/github.com/thanos-community/promql-engine/parser/generated_parser.y
  vendor/github.com/thanos-community/promql-engine/parser/generated_parser.y.go
  vendor/github.com/thanos-community/promql-engine/parser/lex.go
  vendor/github.com/thanos-community/promql-engine/parser/parse.go
  vendor/github.com/thanos-community/promql-engine/parser/prettier.go
  vendor/github.com/thanos-community/promql-engine/parser/prettier_rules.md
  vendor/github.com/thanos-community/promql-engine/parser/printer.go
  vendor/github.com/thanos-community/promql-engine/parser/value.go
  vendor/modules.txt
Labels: size/XS

#5287 Fix error log in query fuzzer testcase
  integration/query_fuzz_test.go
Labels: size/XS

#5286 Handle grpc code resource exhausted for store gateway
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/query_fuzz_test.go
  integration/zone_aware_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/error_translate_queryable.go
Labels: size/L

#5288 log query response size in QFE and querier
  pkg/cortex/modules.go
  pkg/frontend/transport/handler.go
  pkg/querier/worker/frontend_processor.go
  pkg/querier/worker/scheduler_processor.go
  pkg/querier/worker/worker.go
Labels: size/M

#5290 Validating new fields on the PagerDuty AM config
  CHANGELOG.md
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
Labels: size/M

#5293 Test and fix alertmanager-ui with sharding
  CHANGELOG.md
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
  pkg/alertmanager/multitenant.go
  pkg/alertmanager/multitenant_test.go
Labels: size/L

#5295 Update 1.15 compatibility test image
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#5291 Release 1.15.1
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/zone_aware_test.go
  pkg/alertmanager/api.go
  pkg/alertmanager/api_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/error_translate_queryable.go
Labels: size/L

#5296 Bump version to 1.15.1
  VERSION
Labels: size/XS

#5289 Creating label `native-histogram-sample` on the `cortex_discarded_samples_total` to keep track of discarded native histogram samples
  CHANGELOG.md
  pkg/cortexpb/compat.go
  pkg/cortexpb/cortex.pb.go
  pkg/cortexpb/cortex.proto
  pkg/cortexpb/timeseries.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/series.go
  pkg/querier/tripperware/instantquery/instantquery.pb.go
  pkg/ruler/compat.go
Labels: size/L

#5298 Disable parallel tests when thanos engine is enabled
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/error_translate_queryable_test.go
  pkg/querier/querier_test.go
Labels: size/XL

#5179 Add limit for store gateway downloaded bytes
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/storegateway/bucket_stores.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/M

#5305 Fix changelog for v1.14.0. flag ingester.chunk-encoding was removed too
  CHANGELOG.md
Labels: size/XS

#5302 Merge release 1.15.1 to master 3rd attempt
  CHANGELOG.md
  VERSION
Labels: size/XS
