Repository cortexproject/cortex, pull requests merged in 2024-03, with the labels that each got.

#5797 Fix GRPC client not honouring call options
  CHANGELOG.md
  pkg/util/grpcutil/util.go
Labels: size/XS

#5794 Add retry on Delete silence
  CHANGELOG.md
  pkg/alertmanager/distributor.go
  pkg/alertmanager/distributor_test.go
Labels: size/S

#5798 Adding `cortex_ingester_max_inflight_query_requests` metric
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
  pkg/util/math/max_tracker.go
  pkg/util/math/max_tracker_test.go
Labels: size/L

#5801 Stop using gomemcache Fork
  go.mod
  go.sum
  pkg/chunk/cache/memcached_client.go
  vendor/github.com/bradfitz/gomemcache/AUTHORS
  vendor/github.com/bradfitz/gomemcache/memcache/memcache.go
  vendor/github.com/bradfitz/gomemcache/memcache/selector.go
  vendor/modules.txt
Labels: size/S

#5799 add query storage wall time to query stats
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/querier.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
  pkg/ruler/compat.go
Labels: size/L

#5818 Remove Weaveworks and Grafana Labs from adopters
  ADOPTERS.md
  website/data/adopters.yml
  website/static/logos/weaveworks.svg
Labels: size/XS

#5817 Always turn on ingester query streaming and mark its flag as deprecated
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/chunk/chunk_test.go
  pkg/chunk/fixtures.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
  pkg/ruler/ruler_test.go
Labels: size/XL

#5816 Mark mem ballast flag as deprecated
  CHANGELOG.md
  cmd/cortex/main.go
Labels: size/S

#5823 Fix support for keep_firing_for field in alert rules
  integration/ruler_test.go
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/rulespb/compat.go
  pkg/ruler/rulespb/compat_test.go
Labels: size/L

#5826 chore: remove repetitive words
  RELEASE.md
  pkg/ha/ha_tracker_test.go
  pkg/querier/batch/stream.go
  pkg/ring/kv/client.go
  pkg/ring/kv/etcd/etcd.go
Labels: size/S

#5833 Add store gateway lazy expanded posting fuzz test to verify correctness
  go.mod
  go.sum
  integration/e2e/util.go
  integration/e2ecortex/storage.go
  integration/query_fuzz_test.go
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/promqlsmith.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: size/L

#5834 Add store gateway lazy expanded postings fuzz tests against Prometheus
  integration/e2e/db/db.go
  integration/e2e/images/images.go
  integration/e2ecortex/client.go
  integration/e2ecortex/services.go
  integration/query_fuzz_test.go
Labels: size/L

#5827 add context cancellation checks on GetSeries
  CHANGELOG.md
  pkg/querier/distributor_queryable.go
  pkg/querier/series/series_set.go
Labels: size/XS

#5838 Update cache on CAS for DDB
  CHANGELOG.md
  pkg/ring/kv/dynamodb/client.go
  pkg/ring/kv/dynamodb/client_test.go
Labels: size/M

#5839 Upgrade promqlsmith to latest main to cover more testcase
  go.mod
  go.sum
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: size/XS

#5775 change the reflect package to an unsafe package
  pkg/storage/tsdb/inmemory_index_cache.go
Labels: size/XS
