Repository cortexproject/cortex, pull requests merged in 2024-07, with the labels that each got.

#6043 support QFE instant query parse native histograms
  pkg/distributor/distributor.go
  pkg/querier/tripperware/instantquery/custom.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/instantquery.pb.go
  pkg/querier/tripperware/instantquery/instantquery.proto
  pkg/querier/tripperware/query.go
Labels: size/L

#6037 Integration test for native histograms
  integration/e2e/util.go
  integration/native_histogram_test.go
Labels: size/L

#6058 Fix Minimize Token flaky test
  pkg/ring/token_generator_test.go
Labels: size/XS

#6056 Enable native histogram for Cortex req duration metric
  CHANGELOG.md
  pkg/cortex/cortex.go
Labels: size/XS

#6057 Adding experimental flag for Metrics Labels String Interning
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/ingester/ingester.go
  pkg/ingester/lifecycle_test.go
  pkg/util/strings.go
Labels: size/L

#6054 Make sure bucket index load failure will not increase if there is context error
  pkg/storage/tsdb/bucketindex/loader.go
Labels: size/S

#6005 query rejection
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/e2ecortex/client.go
  integration/querier_test.go
  integration/query_frontend_test.go
  integration/zone_aware_test.go
  pkg/querier/tripperware/limits.go
  pkg/querier/tripperware/priority.go
  pkg/querier/tripperware/priority_test.go
  pkg/querier/tripperware/query_attribute_matcher.go
  pkg/querier/tripperware/query_attribute_matcher_test.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
  pkg/util/time.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
  tools/doc-generator/main.go
  tools/doc-generator/parser.go
Labels: size/XXL

#6061 Added the scorecard github action and its badge
  .github/workflows/scorecards.yml
  README.md
Labels: size/M

#6062 [Minimize Spread Token Generator] Calculate current ownership when generating tokens for an ingester that already have tokens
  CHANGELOG.md
  pkg/ring/token_generator.go
  pkg/ring/token_generator_test.go
Labels: size/M

#6063 Allowing renenerate ingester tokens
  CHANGELOG.md
  pkg/api/api.go
  pkg/ingester/ingester.go
  pkg/ring/lifecycler.go
  pkg/ring/lifecycler_test.go
Labels: size/M

#6059 Reuse native histogram test functions from Prometheus
  integration/e2e/util.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester_test.go
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier_test.go
  pkg/ruler/compat_test.go
  pkg/util/histogram/testutils.go
  pkg/util/test_util.go
Labels: size/L

#6069 Update build image go version to 1.22.5
  build-image/Dockerfile
Labels: size/XS

#6073 Upgrade golangci-lint to 1.59.1
  build-image/Dockerfile
Labels: size/XS

#6074 Update faillint for go 1.22
  build-image/Dockerfile
Labels: size/XS

#6071 Support exponential histogram in OTLP ingestion
  CHANGELOG.md
  integration/e2e/util.go
  integration/e2ecortex/client.go
  integration/native_histogram_test.go
  integration/otlp_test.go
Labels: size/L

#6072 Upgrade golang version to 1.22.5
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  go.mod
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/1_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/3_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/4_foobar.up.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/5_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.down.sql
  vendor/github.com/golang-migrate/migrate/v4/source/iofs/testdata/migrations/7_foobar.up.sql
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: size/S

#6040 Add filtering by health and state in list rules
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_test.go
Labels: size/M

#6046 docs: Getting Started Improvements
  docs/getting-started/.gitignore
  docs/getting-started/Makefile
  docs/getting-started/_index.md
  docs/getting-started/alertmanager-config.yaml
  docs/getting-started/alerts.yaml
  docs/getting-started/cortex-config.yaml
  docs/getting-started/dashboards/alertmanager.json
  docs/getting-started/dashboards/cortex-compactor-resources.json
  docs/getting-started/dashboards/cortex-compactor.json
  docs/getting-started/dashboards/cortex-config.json
  docs/getting-started/dashboards/cortex-object-store.json
  docs/getting-started/dashboards/cortex-queries.json
  docs/getting-started/dashboards/cortex-reads.json
  docs/getting-started/dashboards/cortex-rollout-progress.json
  docs/getting-started/dashboards/cortex-scaling.json
  docs/getting-started/dashboards/cortex-slow-queries.json
  docs/getting-started/dashboards/cortex-writes.json
  docs/getting-started/dashboards/ruler.json
  docs/getting-started/docker-compose.yaml
  docs/getting-started/grafana-dashboard.yaml
  docs/getting-started/grafana-datasource.yaml
  docs/getting-started/mixin.libsonnet
  docs/getting-started/prometheus-config.yaml
  docs/getting-started/rules.yaml
Labels: size/XXL

#6078 Using ingester id instead of address on the distributor metrics.
  CHANGELOG.md
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/distributor/query.go
  pkg/ring/model.go
  pkg/ring/ring.go
  pkg/ring/util_test.go
Labels: size/L

#6076 [Vote] Daniel Blando (danielblando) as new Cortex maintainer
  MAINTAINERS
Labels: size/XS

#6083 Add matchers filtering field to rules api
  CHANGELOG.md
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_test.go
Labels: size/L

#6080 Fixed incorrect return value for mocked function
  pkg/compactor/compactor_test.go
Labels: size/XS

#6081 Add new query inflight request on ingester
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/instance_limits.go
  pkg/ingester/instance_limits_test.go
Labels: size/L

#6097 Add unique execution ID for each compaction cycle in log for easy debugging
  CHANGELOG.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/util/log/wrappers.go
Labels: size/S

#6095 Reduce distributor memory usage when error volume is high
  CHANGELOG.md
  pkg/ring/batch.go
Labels: size/S

#6077 Fix user queue in scheduler that was not thread-safe
  CHANGELOG.md
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
Labels: size/M

#6104 Implement max bucket limit and automatic resolution reduction
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/cortexpb/histograms.go
  pkg/distributor/distributor.go
  pkg/util/validation/errors.go
  pkg/util/validation/limits.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/L

#6108 Ingester: compact ooo head during head compaction
  pkg/ingester/ingester.go
Labels: size/S

#6099 fix(build): docker compose environments
  development/tsdb-blocks-storage-s3-gossip/config/cortex.yaml
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-gossip/docker-compose.yml
  development/tsdb-blocks-storage-s3-single-binary/docker-compose.yml
  development/tsdb-blocks-storage-s3/config/cortex.yaml
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-s3/docker-compose.yml
  development/tsdb-blocks-storage-swift-single-binary/docker-compose.yml
Labels: size/S

#6096 Centralize metrics used by compactor and add user label to compactor metrics
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_metrics.go
  pkg/compactor/compactor_metrics_test.go
  pkg/compactor/compactor_test.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/compactor/syncer_metrics.go
  pkg/compactor/syncer_metrics_test.go
Labels: size/XXL

#6112 Split cleaner cycle for active and deleted tenants
  CHANGELOG.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor_test.go
Labels: size/L

#6114 Cleanup native histogram validation const
  CHANGELOG.md
  pkg/cortexpb/histograms.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/M

#6111 Differentiate retry and halt error and retry failed compaction only on retriable error
  CHANGELOG.md
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_metrics.go
  pkg/compactor/compactor_metrics_test.go
  pkg/compactor/compactor_test.go
Labels: size/L

#6016 [Store Gateway] Token bucket limiter
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
  pkg/storegateway/bucket_stores_test.go
  pkg/storegateway/limiter.go
  pkg/storegateway/limiter_test.go
  pkg/util/token_bucket.go
  pkg/util/token_bucket_test.go
Labels: size/XL

#6118 Add Alvin under Emeritus Maintainers
  README.md
Labels: size/XS

#6082 Stepping down as Cortex maintainer
  MAINTAINERS
Labels: size/XS

#6125 Update architecture.md
  docs/architecture.md
Labels: size/XS

#6011 Add support for exclude_alerts flag in ListRules API
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/ruler/api.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
Labels: size/M

#6085 Add support for Prometheus rule query offset
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/api_test.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
  pkg/ruler/rulespb/compat.go
  pkg/ruler/rulespb/compat_test.go
  pkg/ruler/rulespb/rules.pb.go
  pkg/ruler/rulespb/rules.proto
  pkg/ruler/store_mock_test.go
  pkg/util/validation/limits.go
Labels: size/L

#6130 Add missing changelogs for native histogram
  CHANGELOG.md
Labels: size/XS

#6113 Introduce cleaner visit marker
  CHANGELOG.md
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/cleaner_visit_marker.go
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/visit_marker.go
  pkg/compactor/visit_marker_test.go
Labels: size/XL
