Repository cortexproject/cortex, pull requests merged in 2024-10, with the labels that each got.

#6245 Add in-memory chunk cache
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/caching_bucket_test.go
Labels: size/L

#6250 util: Check context cancellation every 128 iterations
  pkg/util/strings.go
Labels: size/XS

#6233 [Querier] Add day range limit for LabelNames and LabelValues
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/M

#6252 [Chore] Edit metadata cache supported values description
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/caching_bucket.go
Labels: type/chore, component/documentation, size/S, lgtm

#6225 Create a experimental HealthCheck GRPC Handler
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/cortex/modules.go
  pkg/ingester/client/client.go
  pkg/querier/store_gateway_client.go
  pkg/querier/store_gateway_client_test.go
  pkg/util/grpcclient/grpcclient.go
  pkg/util/grpcclient/health_check.go
  pkg/util/grpcclient/health_check_test.go
Labels: component/querier, type/performance, size/L, component/store-gateway, lgtm

#6249 Add multi-level chunk cache
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/storage/tsdb/caching_bucket.go
  pkg/storage/tsdb/caching_bucket_test.go
  pkg/storage/tsdb/multilevel_chunk_cache.go
  pkg/storage/tsdb/multilevel_chunk_cache_test.go
Labels: size/XL, lgtm

#6257 Fix healthcheck interceptors
  CHANGELOG.md
  pkg/util/grpcclient/health_check.go
  pkg/util/grpcclient/health_check_test.go
Labels: type/bug, size/M, go

#6261 Upgrade to go 1.23 in build image
  build-image/Dockerfile
Labels: size/XS, go, lgtm

#6263 Upgrade golangci-lint to 1.61.0
  build-image/Dockerfile
Labels: size/XS, component/build, lgtm

#6265 Add index cache max async concurrency
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/index_cache.go
Labels: size/XS, storage/blocks, component/store-gateway, lgtm

#6264 Backport go upgrade to patch CVEs
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  VERSION
Labels: type/security, size/S, go, lgtm

#6275 Post release doc and code update
  RELEASE.md
  docs/getting-started/.env
  integration/backward_compatibility_test.go
Labels: component/documentation, size/XS, lgtm

#6273 Merge release-1.18 back to master
  CHANGELOG.md
  VERSION
Labels: type/chore, size/XS, lgtm

#6260 Reusing the grpc client to perform health check
  pkg/util/grpcclient/health_check.go
  pkg/util/grpcclient/health_check_test.go
Labels: type/performance, size/L, lgtm

#6276 expose flag for max store gateway consistency check attempts
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/querier.go
Labels: component/querier, size/M, lgtm

#6274 Add alertmanager config to single process documents
  docs/configuration/single-process-config-blocks-gossip-1.yaml
  docs/configuration/single-process-config-blocks-gossip-2.yaml
  docs/configuration/single-process-config-blocks-local.yaml
  docs/configuration/single-process-config-blocks-tls.yaml
  docs/configuration/single-process-config-blocks.yaml
Labels: component/documentation, size/M, component/alertmanager, lgtm

#6228 Add new query stats metrics to track prometheus querystats
  CHANGELOG.md
  pkg/api/handlers.go
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
  pkg/querier/stats_renderer.go
  pkg/querier/stats_renderer_test.go
Labels: size/L, lgtm

#6286 Add json format otlp ingestion test
  pkg/util/push/otlp_test.go
Labels: size/M, type/tests, lgtm

#6280 Add list objects version to s3 config
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
Labels: size/L, backend/s3, lgtm

#6270 Disable chunk trimming in ingester
  CHANGELOG.md
  integration/query_fuzz_test.go
  pkg/ingester/ingester.go
Labels: component/ingester, size/L, lgtm

#6255 Support application credential auth for Openstack swift
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/bucket/swift/bucket_client.go
  pkg/storage/bucket/swift/config.go
Labels: size/L, backend/swift, lgtm

#6294 Update thanos version to 62038110b1bc
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/proxy_merge.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/inprocess.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/store/storepb/rpc.proto
  vendor/github.com/thanos-io/thanos/pkg/store/tsdb.go
  vendor/github.com/thanos-io/thanos/pkg/strutil/labels.go
  vendor/github.com/thanos-io/thanos/pkg/tls/options.go
  vendor/golang.org/x/time/rate/rate.go
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/internal/descopts/options.go
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/doc.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/map_entry.go
  vendor/google.golang.org/protobuf/internal/genid/wrappers.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/codec_unsafe.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/impl/encode.go
  vendor/google.golang.org/protobuf/internal/impl/equal.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_pure.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/equal.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/methods.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_pure.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/runtime/protoiface/methods.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/emptypb/empty.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/modules.txt
Labels: dependencies, size/M, go, lgtm
