Repository cortexproject/cortex, pull requests merged in 2024-06, with the labels that each got.

#5988 Create ValidateMetrics
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/user_metrics_metadata.go
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/L

#5992 Fix Ring/Memberlist Join Test Flakiness
  pkg/ring/kv/memberlist/memberlist_client_test.go
  pkg/ring/lifecycler_test.go
Labels: size/S

#5993 Changing the per labelset config to be more generic
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/limiter.go
  pkg/ingester/limiter_test.go
  pkg/ingester/metrics.go
  pkg/ingester/user_state.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#5997 S3 bucket: Don't retry when ctx cancel
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
Labels: size/S

#5996 support querying native histograms in query frontend
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/merge_test.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/query_test.go
Labels: size/XL

#6008 logging messages returned from alert manager
  pkg/ruler/manager.go
Labels: size/S

#5986 Allow ingesting native histograms
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  pkg/cortexpb/compat.go
  pkg/cortexpb/histograms.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/custom.go
  pkg/ingester/client/custom_test.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
  pkg/querier/batch/batch_test.go
  pkg/querier/batch/chunk_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
  pkg/ruler/ruler_test.go
  pkg/storage/tsdb/config.go
  pkg/util/histogram/testutils.go
  pkg/util/test/test/poll.go
  pkg/util/test_util.go
  pkg/util/validation/validate.go
Labels: size/XXL

#6010 Add more tests for native histogram push
  pkg/ingester/ingester_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/L

#6013 Upgrade thanos
  go.mod
  go.sum
  pkg/storegateway/bucket_stores.go
  vendor/github.com/klauspost/compress/flate/matchlen_amd64.s
  vendor/github.com/klauspost/compress/s2/decode_arm64.s
  vendor/github.com/klauspost/compress/s2/index.go
  vendor/github.com/klauspost/compress/s2/s2.go
  vendor/github.com/klauspost/compress/s2/writer.go
  vendor/github.com/klauspost/compress/zlib/reader.go
  vendor/github.com/klauspost/compress/zlib/writer.go
  vendor/github.com/klauspost/compress/zstd/dict.go
  vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_arm64.s
  vendor/github.com/klauspost/compress/zstd/matchlen_amd64.s
  vendor/github.com/thanos-io/thanos/pkg/query/endpointset.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/github.com/thanos-io/thanos/pkg/store/limiter.go
  vendor/modules.txt
Labels: size/S

#6026 Build image in github actions
  .github/workflows/build-image.yml
  .github/workflows/test-build-deploy.yml
  .gitignore
  Makefile
  build-image/Makefile
  docs/contributing/how-to-update-the-build-image.md
Labels: size/L

#6027 Update upload-artifact and download-artifact to v4
  .github/workflows-doc.md
  .github/workflows/test-build-deploy.yml
Labels: size/S

#6028 Update build-image to image built with github actions
  .github/workflows/test-build-deploy.yml
  Makefile
Labels: size/S

#6029 Support ingesting native histograms in Ruler appender
  pkg/cortexpb/compat.go
  pkg/cortexpb/timeseries.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/util/http_test.go
Labels: size/L

#6019 Describe OTLP receiver in docs
  docs/api/_index.md
Labels: size/S

#6020 Update unit tests for distributor push native histograms
  pkg/distributor/distributor_test.go
Labels: size/XXL

#6032 [Vote] Charlie Le (CharlieTLe) as new Cortex maintainer
  MAINTAINERS
Labels: size/XS

#6039 Update prometheus version to latest main
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-hclog/README.md
  vendor/github.com/hashicorp/go-hclog/intlogger.go
  vendor/github.com/hashicorp/go-hclog/logger.go
  vendor/github.com/prometheus/prometheus/discovery/manager.go
  vendor/github.com/prometheus/prometheus/model/labels/labels_common.go
  vendor/github.com/prometheus/prometheus/model/labels/labels_dedupelabels.go
  vendor/github.com/prometheus/prometheus/model/labels/labels_stringlabels.go
  vendor/github.com/prometheus/prometheus/model/labels/matcher.go
  vendor/github.com/prometheus/prometheus/model/labels/regexp.go
  vendor/github.com/prometheus/prometheus/notifier/notifier.go
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/storage/remote/client.go
  vendor/github.com/prometheus/prometheus/storage/remote/codec.go
  vendor/github.com/prometheus/prometheus/storage/remote/queue_manager.go
  vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go
  vendor/github.com/prometheus/prometheus/tsdb/compact.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/github.com/prometheus/prometheus/tsdb/head.go
  vendor/github.com/prometheus/prometheus/tsdb/index/index.go
  vendor/github.com/prometheus/prometheus/tsdb/index/postings.go
  vendor/modules.txt
Labels: size/S

#6014 Upgrade alpine, go, and github.com/Azure/azure-sdk-for-go/sdk/azidentity
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
  packaging/fpm/Dockerfile
Labels: size/M

#6031 Add more unit tests for querying native histograms
  pkg/ingester/client/compat.go
  pkg/ingester/client/compat_test.go
  pkg/querier/batch/batch.go
  pkg/querier/batch/batch_test.go
  pkg/querier/block_test.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier_test.go
  pkg/util/test_util.go
Labels: size/XXL

#6015 Change max query length check to use sum of individual select time range
  pkg/querier/tripperware/instantquery/limits.go
  pkg/querier/tripperware/instantquery/limits_test.go
  pkg/querier/tripperware/queryrange/limits.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/ruler/compat.go
  pkg/util/promql/promql.go
  pkg/util/promql/promql_test.go
Labels: size/L

#6018 Enforce /api/v1/series API query length check at Querier
  CHANGELOG.md
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: size/M

#6041 Fix merge failure of querier test
  pkg/querier/querier_test.go
Labels: size/XS

#6042 Fix getting started guide
  docs/getting-started/.env
  docs/getting-started/_index.md
  docs/getting-started/cortex-config.yaml
  docs/getting-started/cortex-values.yaml
  docs/getting-started/docker-compose.yaml
  docs/getting-started/grafana-datasource.yaml
  docs/getting-started/grafana-values.yaml
  docs/getting-started/prometheus-values.yaml
  docs/getting-started/seaweedfs-config.json
  docs/getting-started/seaweedfs.yaml
Labels: component/documentation, size/L

#6044 Using Ingester Id as a tiebreaker for MinimizeSpreadTokenGenerator
  pkg/ring/token_generator.go
  pkg/ring/token_generator_test.go
Labels: size/S

#6045 docs: Fix Getting Started Title
  docs/getting-started/_index.md
Labels: size/XS
