Repository cortexproject/cortex, pull requests merged in 2024-08, with the labels that each got.

#6115 Update Kubernetes Getting Started
  docs/getting-started/_index.md
  docs/getting-started/cortex-values.yaml
  docs/getting-started/grafana-values.yaml
  docs/getting-started/prometheus-values.yaml
  docs/getting-started/seaweedfs.yaml
Labels: size/L

#6134 Fix cortex_ingester_tsdb_mmap_chunks_total metric
  CHANGELOG.md
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: size/S

#6136 OTLP handler: enable metric name normalization
  CHANGELOG.md
  pkg/util/push/otlp.go
Labels: size/XS

#6135 Fix OTLP native histogram push
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/otlp_test.go
  pkg/cortexpb/histograms.go
  pkg/util/push/otlp.go
  pkg/util/push/otlp_test.go
Labels: size/M

#6131 Fix query offset issue on individual rule groups
  pkg/ruler/api_test.go
  pkg/ruler/ruler.go
  pkg/ruler/rulespb/compat.go
Labels: size/S

#6142 Add cortex_query_samples_total metric
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
Labels: size/M

#6147 Deprecate 'querier.ingester-metadata-streaming' flag
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/querier/querier.go
Labels: size/S

#6146 Deprecating `querier.max-outstanding-requests-per-tenant` and `-query-scheduler.max-outstanding-requests-per-tenant` flags
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/frontend/v1/frontend.go
  pkg/frontend/v1/frontend_test.go
  pkg/frontend/v1/queue_test.go
  pkg/scheduler/queue/queue.go
  pkg/scheduler/queue/queue_test.go
  pkg/scheduler/queue/user_queues.go
  pkg/scheduler/queue/user_queues_test.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/scheduler_test.go
Labels: size/L

#6148 Enable 'snappy-block' compression on ingester clients by default
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  pkg/frontend/v2/frontend.go
  pkg/ingester/client/client.go
  pkg/querier/worker/worker.go
  pkg/ruler/ruler.go
  pkg/scheduler/scheduler.go
  pkg/util/grpcclient/grpcclient.go
Labels: size/L

#6150 Increase interval for ruler test
  pkg/ruler/ruler_test.go
Labels: size/S

#6145 fix for query_rejection bug
  CHANGELOG.md
  integration/query_frontend_test.go
  pkg/querier/tripperware/query_attribute_matcher.go
  pkg/querier/tripperware/query_attribute_matcher_test.go
Labels: size/L

#6128 Implement metadata API limit in Ingester
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
Labels: size/L

#6149 Setting ruler.evaluation-delay-duration to be deprecated.
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/configs.go
  integration/ruler_test.go
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/ruler_ring_test.go
  pkg/ruler/ruler_test.go
  pkg/util/validation/limits.go
  pkg/util/validation/limits_test.go
Labels: size/L

#6159 Check context cancellation every 128 iterations
  pkg/ingester/ingester.go
  pkg/querier/series/series_set.go
  pkg/storage/tsdb/inmemory_index_cache.go
  pkg/util/context.go
Labels: size/S

#6157 Remove querier.at-modifier-enabled flag
  CHANGELOG.md
  pkg/querier/querier.go
Labels: size/XS

#6158 Remove tracing oltp endpoint flag
  CHANGELOG.md
  pkg/tracing/tracing.go
Labels: size/S

#6156 cleanup docs for query_store_for_labels_enabled config
  docs/api/_index.md
  docs/configuration/v1-guarantees.md
  docs/guides/limitations.md
  pkg/ingester/ingester_test.go
  pkg/querier/querier_test.go
Labels: size/S

#6161 Always enable zone stable shuffle sharding for store gateway
  CHANGELOG.md
  pkg/storegateway/gateway_ring.go
Labels: size/XS

#6164 Start preparing for release 1.18
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#6166 Prepare 1.18.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/S

#6141 Create feature flag to switch between current shuffle sharding group planner and partition compaction group planner
  docs/blocks-storage/compactor.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/partition_compaction_grouper.go
  pkg/compactor/partition_compaction_planner.go
  pkg/util/shard.go
Labels: size/L

#5869 Add cortex_ruler_rule_groups_in_store metric
  CHANGELOG.md
  integration/ruler_test.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: size/L

#6173 Add query metrics to ruler query stats
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ruler/compat.go
  pkg/ruler/compat_test.go
  pkg/ruler/manager_metrics.go
  pkg/ruler/manager_metrics_test.go
  pkg/ruler/ruler.go
Labels: size/L

#6182 Create `cortex_reduced_resolution_histogram_samples_total` metric
  CHANGELOG.md
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: size/M
