Repository cortexproject/cortex, pull requests merged in 2024-11, with the labels that each got.

#6300 Put ingester disable chunk trimming a feature flag
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/query_fuzz_test.go
  pkg/ingester/ingester.go
Labels: component/ingester, size/M, lgtm

#6298 add fuzz test for compatibility with latest Cortex and Prometheus release
  .github/workflows/test-build-deploy.yml
  go.mod
  go.sum
  integration/e2e/db/db.go
  integration/query_fuzz_test.go
  vendor/github.com/cortexproject/promqlsmith/.go-version
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: size/XL, type/tests, lgtm

#6302 Support label_join and label_replace in query fuzz tests
  go.mod
  go.sum
  integration/query_fuzz_test.go
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: size/S, lgtm

#6304 Upgrade Prometheus to fix round function
  go.mod
  go.sum
  vendor/github.com/prometheus/prometheus/config/reload.go
  vendor/github.com/prometheus/prometheus/promql/engine.go
  vendor/github.com/prometheus/prometheus/promql/functions.go
  vendor/github.com/prometheus/prometheus/promql/info.go
  vendor/github.com/prometheus/prometheus/promql/parser/ast.go
  vendor/github.com/prometheus/prometheus/promql/parser/functions.go
  vendor/github.com/prometheus/prometheus/promql/parser/parse.go
  vendor/github.com/prometheus/prometheus/tsdb/db.go
  vendor/modules.txt
Labels: dependencies, size/XS, go, lgtm

#6305 fix typo in usage message for querier.split-queries-by-interval flag
  docs/configuration/config-file-reference.md
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
Labels: component/querier, size/XS, lgtm

#6268 Change all max async concurrency
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/tsdb/memcache_client_config.go
  pkg/storage/tsdb/redis_client_config.go
Labels: size/M, storage/blocks, lgtm

#6309 Fix BenchmarkDistributor_Push benchmark
  pkg/distributor/distributor_test.go
Labels: component/distributor, size/XS, lgtm

#6310 storegateway: Add a metric for chunk pool inuse bytes
  CHANGELOG.md
  pkg/storegateway/chunk_bytes_pool.go
  pkg/storegateway/chunk_bytes_pool_test.go
Labels: type/observability, size/M, component/store-gateway, lgtm

#6312 Fix race on chunks multilevel cache + Optimize to avoid refetching already found keys.
  pkg/storage/tsdb/multilevel_chunk_cache.go
  pkg/storage/tsdb/multilevel_chunk_cache_test.go
Labels: size/M, storage/chunks, lgtm

#6272 Change otlp attribute conversion to be consistent with prometheus
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/e2ecortex/client.go
  integration/otlp_test.go
  pkg/api/api.go
  pkg/cortex/modules.go
  pkg/distributor/distributor.go
  pkg/util/push/otlp.go
  pkg/util/push/otlp_test.go
  pkg/util/validation/limits.go
Labels: component/distributor, size/L, lgtm

#6314 Fix: PostingCache promise should fetch data only once
  pkg/storage/tsdb/expanded_postings_cache.go
  pkg/storage/tsdb/expanded_postings_cache_test.go
Labels: size/M, lgtm

#6299 Pagination support for ListRules
  CHANGELOG.md
  integration/e2ecortex/client.go
  integration/ruler_test.go
  pkg/ruler/api.go
  pkg/ruler/merger.go
  pkg/ruler/merger_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_pagination.go
  pkg/ruler/ruler_test.go
Labels: component/rules, size/XL, lgtm

#6316 Remove openstack swift experimental
  docs/architecture.md
Labels: size/XS, backend/swift, lgtm

#6318 Add reason why the key was evicted in the `cortex_ingester_expanded_postings_cache_evicts` metric
  pkg/storage/tsdb/expanded_postings_cache.go
  pkg/storage/tsdb/expanded_postings_cache_test.go
Labels: size/M, lgtm

#6319 Add kakaoenterprise to Cortex adapter
  ADOPTERS.md
  website/data/adopters.yml
  website/static/logos/kakaocloud.svg
Labels: size/XS, lgtm

#6322 Remove openstack swfit experimental in blocks storage
  docs/blocks-storage/_index.md
Labels: size/XS, storage/blocks, lgtm

#6321 Upgrade to use prometheus v2.55.1 in fuzz
  .github/workflows/test-build-deploy.yml
  integration/query_fuzz_test.go
Labels: size/XS, lgtm

#6315 update thanos objstore library to pull object duration metric fix
  go.mod
  go.sum
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/inmem.go
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/providers/azure/azure.go
  vendor/github.com/thanos-io/objstore/providers/azure/helpers.go
  vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
  vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/objstore/providers/swift/swift.go
  vendor/github.com/thanos-io/objstore/testing.go
  vendor/modules.txt
Labels: dependencies, size/XS, lgtm

#6311 Run more test cases per query fuzz test
  integration/e2ecortex/client.go
  integration/query_fuzz_test.go
Labels: size/M, type/tests, lgtm

#6288 update cortex dashboards
  docs/getting-started/alerts.yaml
  docs/getting-started/dashboards/alertmanager.json
  docs/getting-started/dashboards/cortex-compactor-resources.json
  docs/getting-started/dashboards/cortex-compactor.json
  docs/getting-started/dashboards/cortex-config.json
  docs/getting-started/dashboards/cortex-object-store.json
  docs/getting-started/dashboards/cortex-queries.json
  docs/getting-started/dashboards/cortex-reads.json
  docs/getting-started/dashboards/cortex-rollout-progress.json
  docs/getting-started/dashboards/cortex-scaling.json
  docs/getting-started/dashboards/cortex-slow-queries.json
  docs/getting-started/dashboards/cortex-writes.json
  docs/getting-started/dashboards/ruler.json
  docs/getting-started/rules.yaml
Labels: component/rules, size/XXL, lgtm

#6308 Update getting started guide, seaweedfs setup, and healthchecks in docker-compose
  docs/getting-started/Makefile
  docs/getting-started/_index.md
  docs/getting-started/docker-compose.yaml
Labels: component/documentation, size/L, lgtm

#6326 Don't propagate cancel signal to the Prometheus rules manager context
  CHANGELOG.md
  pkg/ruler/api_test.go
  pkg/ruler/compat.go
  pkg/ruler/ruler_test.go
  pkg/ruler/store_mock_test.go
Labels: component/rules, size/L, lgtm

#6328 Stop using global instant query codec
  pkg/cortex/modules.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_middlewares.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/shard_by_query_test.go
Labels: component/querier, size/M, lgtm

#6329 docs: proofread guides
  docs/guides/alert-manager-configuration.md
  docs/guides/authentication-and-authorisation.md
  docs/guides/capacity-planning.md
  docs/guides/encryption-at-rest.md
  docs/guides/encryption-at-rest.template
  docs/guides/glossary.md
  docs/guides/gossip-ring-getting-started.md
  docs/guides/ha-pair-handling.md
  docs/guides/ingesters-rolling-updates.md
  docs/guides/ingesters-scaling-up-and-down.md
  docs/guides/limitations.md
  docs/guides/overrides-exporter.md
  docs/guides/running-cortex-on-kubernetes.md
  docs/guides/sharded_ruler.md
  docs/guides/shuffle-sharding.md
  docs/guides/tls.md
  docs/guides/tracing.md
  docs/guides/zone-replication.md
Labels: component/documentation, size/L, lgtm

#6333 Add flag for limiting OTLP request size
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/api/api.go
  pkg/distributor/distributor.go
  pkg/util/http.go
  pkg/util/push/otlp.go
  pkg/util/push/otlp_test.go
Labels: component/distributor, size/L, lgtm

#6339 Bug fix on JSON Tag
  pkg/ruler/api.go
  pkg/ruler/api_test.go
Labels: type/bug, component/rules, size/M, lgtm

#6342 Relaxing float comparison on fuzz testing
  integration/query_fuzz_test.go
Labels: size/XS, type/tests

#6278 Distributor accept multiple HA Tracker pairs in the same request
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/distributor_mixed_ha_samples_test.go
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/util/validation/limits.go
Labels: component/distributor, size/L, lgtm

#6349 Add Nov 2024 KubeCon talk
  README.md
Labels: size/XS, lgtm

#6346 Upgrade thanos version to fix store gateway buf reuse issue
  go.mod
  go.sum
  pkg/chunk/cache/memcached_client.go
  pkg/compactor/compactor.go
  pkg/querier/blocks_store_balanced_set.go
  pkg/ring/bench/ring_memberlist_test.go
  pkg/ring/kv/memberlist/dnsprovider.go
  pkg/ring/kv/memberlist/memberlist_client.go
  pkg/ring/kv/memberlist/memberlist_client_test.go
  vendor/github.com/thanos-io/thanos/pkg/cache/groupcache.go
  vendor/github.com/thanos-io/thanos/pkg/cacheutil/memcached_client.go
  vendor/github.com/thanos-io/thanos/pkg/clientconfig/http.go
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/grpc.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/dns/provider.go
  vendor/github.com/thanos-io/thanos/pkg/discovery/memcache/provider.go
  vendor/github.com/thanos-io/thanos/pkg/extpromql/parser.go
  vendor/github.com/thanos-io/thanos/pkg/promclient/promclient.go
  vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go
  vendor/github.com/thanos-io/thanos/pkg/store/bucket.go
  vendor/modules.txt
Labels: size/S, component/store-gateway, lgtm

#6353 Vote to add triage role on Cortex
  GOVERNANCE.md
Labels: size/XS, Vote

#6357 Increase configs integration test timeout from 30s to 10m
  Makefile
Labels: size/XS

#6359 Adding list of Maintainers on the governance page
  GOVERNANCE.md
  MAINTAINERS
  MAINTAINERS.md
  tools/website/web-pre.sh
Labels: component/documentation, size/S

#6361 Fix typo in ha pair docs
  docs/guides/ha-pair-handling.md
Labels: component/documentation, size/XS

#6362 Install get test on the build image
  build-image/Dockerfile
Labels: size/XS, component/build

#6363 Update Build Image with `envsubst`
  .github/workflows/test-build-deploy.yml
Labels: size/S, ci/cd

#6355 Support experimental promql functions
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  go.mod
  go.sum
  integration/query_fuzz_test.go
  pkg/cortex/modules.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/merge_test.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  vendor/github.com/cortexproject/promqlsmith/opts.go
  vendor/github.com/cortexproject/promqlsmith/promqlsmith.go
  vendor/github.com/cortexproject/promqlsmith/walk.go
  vendor/modules.txt
Labels: component/querier, size/L, lgtm

#6365 Using a single seed array for expanded postings cache on ingesters
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/storage/tsdb/expanded_postings_cache.go
  pkg/storage/tsdb/expanded_postings_cache_test.go
Labels: component/ingester, size/L

#6369 Fix data race on expanded postings Cache
  pkg/ingester/ingester_test.go
  pkg/storage/tsdb/expanded_postings_cache.go
Labels: component/ingester, size/M

#6366 Improve consistency check warn log
  pkg/querier/blocks_store_queryable.go
Labels: component/querier, size/XS

#6370 Add metrics to track ingesting native histograms
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/metrics.go
  pkg/ingester/metrics_test.go
Labels: component/ingester, size/L, lgtm

#6360 [Vote] Add Sungjin Lee (@SungJin1212) as Triager on cortex
  MAINTAINERS.md
Labels: size/XS, lgtm

#6376 Add distributor inflight client request limit
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: component/distributor, size/M, lgtm

#6377 Fix flaky querier unit test
  pkg/querier/querier_test.go
Labels: component/querier, type/flaky-test, size/XS, lgtm

#6379 Fix text about cortex community calls
  README.md
Labels: component/documentation, size/XS, lgtm

#6364 Add docs for accept multiple ha pairs
  docs/guides/ha-pair-handling.md
Labels: component/documentation, size/M, lgtm

#6380 Add label size bytes native histogram
  CHANGELOG.md
  pkg/util/validation/validate.go
  pkg/util/validation/validate_test.go
Labels: type/observability, size/S, lgtm

#6385 Upgrade thanos version to v0.37.0
  go.mod
  go.sum
  pkg/ruler/rulestore/bucketclient/bucket_client.go
  pkg/storage/bucket/client_mock.go
  pkg/storage/bucket/prefixed_bucket_client.go
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/bucket_client_test.go
  pkg/storage/bucket/sse_bucket_client.go
  pkg/storage/tsdb/bucketindex/markers_bucket_client.go
  vendor/github.com/thanos-io/objstore/CHANGELOG.md
  vendor/github.com/thanos-io/objstore/README.md
  vendor/github.com/thanos-io/objstore/inmem.go
  vendor/github.com/thanos-io/objstore/objstore.go
  vendor/github.com/thanos-io/objstore/prefixed_bucket.go
  vendor/github.com/thanos-io/objstore/providers/azure/azure.go
  vendor/github.com/thanos-io/objstore/providers/filesystem/filesystem.go
  vendor/github.com/thanos-io/objstore/providers/gcs/gcs.go
  vendor/github.com/thanos-io/objstore/providers/s3/s3.go
  vendor/github.com/thanos-io/objstore/providers/swift/swift.go
  vendor/github.com/thanos-io/objstore/testing.go
  vendor/github.com/thanos-io/objstore/tracing/opentracing/opentracing.go
  vendor/github.com/thanos-io/promql-engine/engine/explain.go
  vendor/github.com/thanos-io/promql-engine/execution/aggregate/accumulator.go
  vendor/github.com/thanos-io/promql-engine/execution/aggregate/scalar_table.go
  vendor/github.com/thanos-io/promql-engine/execution/function/functions.go
  vendor/github.com/thanos-io/promql-engine/execution/function/operator.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/distribute.go
  vendor/github.com/thanos-io/promql-engine/ringbuffer/rate.go
  vendor/github.com/thanos-io/promql-engine/storage/prometheus/histograms.go
  vendor/github.com/thanos-io/promql-engine/storage/prometheus/scanners.go
  vendor/github.com/thanos-io/thanos/pkg/block/fetcher.go
  vendor/github.com/thanos-io/thanos/pkg/cache/groupcache.go
  vendor/modules.txt
Labels: dependencies, size/M, sync-vendor, go

#6374 Add tls config to consul
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/ring/kv/consul/client.go
  pkg/ring/kv/consul/client_test.go
Labels: size/L, backend/consul, lgtm

#6368 Add support for native histograms in querier protobuf codec
  integration/native_histogram_test.go
  pkg/querier/codec/protobuf_codec.go
  pkg/querier/codec/protobuf_codec_test.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
Labels: component/querier, size/XL
