Repository cortexproject/cortex, pull requests merged in 2024-04, with the labels that each got.

#5805 Improve GetRules performance
  CHANGELOG.md
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
Labels: size/L

#5832 fix instant query bypassing limit middleware due to vertical sharding
  docs/configuration/config-file-reference.md
  integration/query_frontend_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/util/validation/limits.go
Labels: size/L

#5844 Reuse prom serieset from Thanos
  pkg/querier/block.go
  pkg/querier/block_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/query.pb.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/query.proto
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/responses.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/store_matchers.go
  vendor/github.com/thanos-io/thanos/pkg/dedup/chunk_iter.go
  vendor/github.com/thanos-io/thanos/pkg/dedup/iter.go
  vendor/github.com/thanos-io/thanos/pkg/query/endpointset.go
  vendor/github.com/thanos-io/thanos/pkg/query/iter.go
  vendor/github.com/thanos-io/thanos/pkg/query/querier.go
  vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go
  vendor/modules.txt
Labels: size/XL

#5828 Configurable block listing strategy
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/querier/blocks_finder_bucket_scan.go
  pkg/querier/blocks_finder_bucket_scan_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/storage/tsdb/bucketindex/block_ids_fetcher.go
  pkg/storage/tsdb/bucketindex/block_ids_fetcher_test.go
  pkg/storage/tsdb/config.go
  pkg/storegateway/bucket_stores.go
Labels: size/L

#5854 update thanos to main to disable overlapping sources check
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/thanos-io/promql-engine/engine/engine.go
  vendor/github.com/thanos-io/promql-engine/engine/explain.go
  vendor/github.com/thanos-io/promql-engine/engine/sort.go
  vendor/github.com/thanos-io/promql-engine/execution/execution.go
  vendor/github.com/thanos-io/promql-engine/execution/model/operator.go
  vendor/github.com/thanos-io/promql-engine/execution/remote/operator.go
  vendor/github.com/thanos-io/promql-engine/execution/scan/functions.go
  vendor/github.com/thanos-io/promql-engine/execution/scan/subquery.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/distribute.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/distribute_avg.go
  vendor/github.com/thanos-io/promql-engine/storage/prometheus/matrix_selector.go
  vendor/github.com/thanos-io/promql-engine/storage/prometheus/scanners.go
  vendor/github.com/thanos-io/promql-engine/storage/prometheus/vector_selector.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/plan.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/query.pb.go
  vendor/github.com/thanos-io/thanos/pkg/api/query/querypb/query.proto
  vendor/github.com/thanos-io/thanos/pkg/compact/compact.go
  vendor/github.com/thanos-io/thanos/pkg/extkingpin/flags.go
  vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/targets/targetspb/rpc.pb.go
  vendor/github.com/thanos-io/thanos/pkg/targets/targetspb/rpc.proto
  vendor/modules.txt
Labels: size/S

#5837 add context cancellation checks on merging GetLabel slices
  CHANGELOG.md
  pkg/distributor/distributor.go
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: size/M

#5855 Implementing Spread Minimizing Token Generator
  CHANGELOG.md
  pkg/alertmanager/lifecycle.go
  pkg/alertmanager/multitenant_test.go
  pkg/cortex/cortex.go
  pkg/distributor/distributor_test.go
  pkg/ingester/ingester.go
  pkg/ring/basic_lifecycler.go
  pkg/ring/lifecycler.go
  pkg/ring/ring_test.go
  pkg/ring/token_generator.go
  pkg/ring/token_generator_test.go
  pkg/ring/util.go
  pkg/ring/util_test.go
  pkg/ruler/lifecycle.go
  pkg/ruler/lifecycle_test.go
  pkg/storegateway/gateway.go
  pkg/storegateway/gateway_test.go
Labels: size/XXL

#5852 Add retry to query frontend integration test
  integration/e2ecortex/client.go
Labels: size/S

#5850 Fix rand int63n panic in query fuzz test
  integration/query_fuzz_test.go
Labels: size/XS

#5856 chore: fix function names in comment
  integration/e2e/metrics_options.go
  pkg/ingester/ingester.go
Labels: size/XS

#5813 OTLP Ingestion
  CHANGELOG.md
  docs/api/_index.md
  docs/configuration/v1-guarantees.md
  go.mod
  integration/e2ecortex/client.go
  integration/otlp_test.go
  pkg/api/api.go
  pkg/util/push/otlp.go
  pkg/util/push/otlp_test.go
Labels: size/L

#5858 sort block ids in BlockIDsFetcherFetcher test
  pkg/storage/tsdb/bucketindex/block_ids_fetcher_test.go
Labels: size/XS

#5863 Fix function names
  pkg/storage/tsdb/bucketindex/index.go
  pkg/storage/tsdb/config.go
  pkg/util/limiter/query_limiter.go
  pkg/util/metrics_helper.go
  tools/querytee/response_comparator.go
Labels: size/S

#5865 Include Kubecon talk 2024
  README.md
Labels: size/XS

#5825 cleanup legacy Querier iterators code (take 1)
  pkg/querier/chunk_store_queryable.go
  pkg/querier/chunk_store_queryable_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/series_with_chunks.go
  pkg/querier/tripperware/queryrange/series_test.go
  pkg/querier/tripperware/queryrange/value.go
Labels: size/L

#5870 Add S3 send_content_md5 config and default to use MD5
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/storage/bucket/s3/bucket_client.go
  pkg/storage/bucket/s3/config.go
  pkg/storage/bucket/s3/config_test.go
Labels: size/M

#5872 Fix usage of math.Min since the util method was removed
  pkg/ruler/ruler_ring.go
Labels: size/XS

#5874 Update(ADOPTERS.md): add "us"
  ADOPTERS.md
Labels: size/XS

#5879 Upgrade to go 1.21.9
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
Labels: size/S

#5882 fix go version for integration tests
  .github/workflows/test-build-deploy.yml
Labels: type/bug, size/XS

#5886 Upgrade Thanos to latest main
  go.mod
  go.sum
  vendor/github.com/thanos-io/thanos/pkg/dedup/iter.go
  vendor/github.com/thanos-io/thanos/pkg/extkingpin/flags.go
  vendor/github.com/thanos-io/thanos/pkg/pool/worker_pool.go
  vendor/github.com/thanos-io/thanos/pkg/query/remote_engine.go
  vendor/github.com/thanos-io/thanos/pkg/shipper/shipper.go
  vendor/github.com/thanos-io/thanos/pkg/store/cache/inmemory.go
  vendor/github.com/thanos-io/thanos/pkg/store/lazy_postings.go
  vendor/modules.txt
Labels: size/XS

#5885 Cherrypick commits for 1.16.1
  .github/workflows/test-build-deploy.yml
  .golangci.yml
  CHANGELOG.md
  Makefile
  VERSION
  build-image/Dockerfile
  cmd/cortex/Dockerfile
  cmd/query-tee/Dockerfile
  cmd/test-exporter/Dockerfile
  cmd/thanosconvert/Dockerfile
  development/tsdb-blocks-storage-s3-gossip/dev.dockerfile
  development/tsdb-blocks-storage-s3-single-binary/dev.dockerfile
  development/tsdb-blocks-storage-s3/dev.dockerfile
  development/tsdb-blocks-storage-swift-single-binary/dev.dockerfile
  packaging/fpm/Dockerfile
  pkg/querier/testutils.go
Labels: size/M

#5888 Add Apple as an Adopter
  ADOPTERS.md
Labels: size/XS

#5887 Integration test querier max samples
  integration/querier_test.go
Labels: size/M

#5890 Add doc for the Spread minimize token generator
  docs/configuration/config-file-reference.md
  pkg/ring/lifecycler.go
Labels: size/S

#5891 Merge release 1.16 to master
  CHANGELOG.md
  VERSION
Labels: size/XS

#5889 Fixing how ring ownership is calculated on the ring status page
  CHANGELOG.md
  pkg/ring/http.go
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/M

#5894 chore: add version 1.16.1 to compatibility test
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#5895 Start preparing for release 1.17
  CHANGELOG.md
  RELEASE.md
Labels: size/XS

#5898 Prepare 1.17.0-rc.0
  CHANGELOG.md
  VERSION
Labels: size/S

#5899 Change the ring changes from ENHANCEMENT to FEATURE on the changelog
  CHANGELOG.md
Labels: size/XS

#5902 Removing Apple as adopters
  ADOPTERS.md
Labels: size/XS

#5903 fix random string used in test allocating 50MB in Cortex binary
  pkg/distributor/distributor_test.go
  pkg/util/strings_test.go
  pkg/util/test_util.go
Labels: size/S

#5901 Remove APIEnableRulesBackup config and use Ring.ReplicationFactor ins…
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_ring_test.go
  pkg/ruler/ruler_test.go
Labels: size/L

#5905 Optimize Write Signature calculation
  pkg/cortexpb/extensions.go
  pkg/cortexpb/extensions_test.go
Labels: size/M

#5892 Collect store gateway postings touched count and bytes in querier stats
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/stats/stats.go
  pkg/querier/stats/stats.pb.go
  pkg/querier/stats/stats.proto
  pkg/querier/stats/stats_test.go
Labels: size/L

#5906 Node Version Upgrade - 14x to 18x
  .github/workflows/test-build-deploy.yml
  CHANGELOG.md
  Makefile
  build-image/Dockerfile
Labels: size/S

#5907 Cherrypick commits to release-1.17 for new RC
  CHANGELOG.md
  VERSION
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/distributor/distributor_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_ring_test.go
  pkg/ruler/ruler_test.go
  pkg/util/strings_test.go
  pkg/util/test_util.go
Labels: size/L

#5912 ready for release 1.17.0
  CHANGELOG.md
  VERSION
Labels: size/XS
