Repository cortexproject/cortex, pull requests merged in 2024-09, with the labels that each got.

#6163 New ring state READONLY to be used by ingesters
  CHANGELOG.md
  docs/api/_index.md
  pkg/api/api.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ring/lifecycler.go
  pkg/ring/ring.go
  pkg/ring/ring.pb.go
  pkg/ring/ring.proto
  pkg/ring/ring_test.go
Labels: size/L

#6178 Add users stats http api to ingester
  CHANGELOG.md
  docs/api/_index.md
  pkg/api/api.go
  pkg/distributor/distributor.go
  pkg/distributor/http_server.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/http_admin.go
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: size/L

#6190 Merge release 1.18 to master
  CHANGELOG.md
  VERSION
Labels: size/S

#6191 add 1.18.0 to backward compatibility test
  .github/workflows/test-build-deploy.yml
  integration/backward_compatibility_test.go
Labels: size/XS

#6180 Unify query frontend instant and range protobufs into one
  pkg/querier/tripperware/custom.go
  pkg/querier/tripperware/instantquery/custom.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/instantquery.pb.go
  pkg/querier/tripperware/instantquery/instantquery.proto
  pkg/querier/tripperware/instantquery/limits_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/merge_test.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/queryrange/limits.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/marshaling_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/queryrange.pb.go
  pkg/querier/tripperware/queryrange/queryrange.proto
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
  pkg/querier/tripperware/queryrange/step_align_test.go
Labels: size/XXL

#6193 Use temp dir for ruler LoadPartialGroups test
  pkg/ruler/ruler_test.go
Labels: size/XS

#5862 Ruler HA - Proposal
  docs/proposals/ruler-ha-new.md
  docs/proposals/ruler-ha.md
Labels: size/M

#6129 Minimize missed rule group evaluations
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/ruler_test.go
  pkg/ruler/client_pool_test.go
  pkg/ruler/ruler.go
  pkg/ruler/ruler.pb.go
  pkg/ruler/ruler.proto
  pkg/ruler/ruler_client_config.go
  pkg/ruler/ruler_ring.go
  pkg/ruler/ruler_ring_test.go
  pkg/ruler/ruler_test.go
Labels: size/XL

#6188 Support peakSamples in query frontend response
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
Labels: size/L

#6151 Support Ruler to query Query Frontend
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/ruler_test.go
  pkg/cortex/modules.go
  pkg/ruler/compat.go
  pkg/ruler/frontend_client.go
  pkg/ruler/frontend_client_pool.go
  pkg/ruler/frontend_client_test.go
  pkg/ruler/frontend_decoder.go
  pkg/ruler/frontend_decoder_test.go
  pkg/ruler/manager.go
  pkg/ruler/manager_test.go
  pkg/ruler/ruler.go
Labels: size/XL

#6167 Update Community Call Calendar and Zoom Links
  README.md
Labels: size/S

#6196 fix regression of result cache unable to parse cached results
  pkg/querier/tripperware/custom.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/queryrange.pb.go
  pkg/querier/tripperware/queryrange/queryrange.proto
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
Labels: size/L

#6195 StoreGateway: Implement metadata API limit in queryable
  CHANGELOG.md
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
Labels: size/L

#6197 fix: querier integration flaky test
  integration/querier_test.go
Labels: size/XS

#6208 Fixed ingester ReadOnly state related bugs
  pkg/ingester/http_admin.go
  pkg/ingester/http_admin_test.go
  pkg/ingester/ingester_test.go
  pkg/ring/model.go
  pkg/ring/model_test.go
Labels: size/M

#6216 Update golang patch version in build-image
  build-image/Dockerfile
Labels: size/XS

#6212 Add timeout on lifecycler heartbeat
  pkg/ring/lifecycler.go
Labels: size/S

#6207 Add info field to query response
  CHANGELOG.md
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/queryrange.pb.go
  pkg/querier/tripperware/queryrange/queryrange.proto
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
  pkg/ruler/frontend_decoder.go
  pkg/util/api/response.go
Labels: size/L

#6218 Improve validation metrics for discarded samples and exemplars
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
Labels: size/L

#6204 Enable compactor and alertmanager in target all
  CHANGELOG.md
  integration/api_endpoints_test.go
  integration/getting_started_single_process_config_local_test.go
  integration/getting_started_single_process_config_test.go
  integration/getting_started_with_gossiped_ring_test.go
  integration/integration_memberlist_single_binary_test.go
  integration/otlp_test.go
  integration/querier_test.go
  integration/query_fuzz_test.go
  integration/ruler_test.go
  integration/runtime_config_test.go
  pkg/cortex/cortex_test.go
  pkg/cortex/modules.go
Labels: size/L

#6209 Ingester: Add matchers to LabelNames() ingester RPC
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/distributor/distributor.go
  pkg/ingester/client/compat.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
  pkg/querier/testutils.go
Labels: size/L

#5527 Add protobuf codec for query range and instant query responses
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/query_frontend_test.go
  pkg/api/api.go
  pkg/api/handlers.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/querier/codec/protobuf_codec.go
  pkg/querier/querier.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/instantquery/shard_by_query_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query.pb.go
  pkg/querier/tripperware/query.proto
  pkg/querier/tripperware/queryrange/marshaling_test.go
  pkg/querier/tripperware/queryrange/query_range.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
  pkg/querier/tripperware/queryrange/results_cache_test.go
Labels: size/XXL

#6231 Fixed bug that blocks cannot be fully deleted from TSDB
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: size/L

#6232 Add tsdb wal compression type zstd
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/blocks-storage/store-gateway.md
  docs/configuration/config-file-reference.md
  pkg/ingester/ingester.go
  pkg/storage/tsdb/config.go
  pkg/storage/tsdb/config_test.go
Labels: size/M

#6227 Make LivenessCheck Timeout Configurable
  docs/configuration/config-file-reference.md
  pkg/ruler/ruler.go
Labels: size/S

#6226 Wait until container is removed after stopping
  integration/e2e/scenario_test.go
  integration/e2e/service.go
Labels: size/M

#6224 Runtime-config: Handle absolute file paths when working directory is not /
  CHANGELOG.md
  integration/e2e/service.go
  integration/runtime_config_test.go
  pkg/cortex/modules.go
Labels: size/M

#6243 [Querier] Fix Flaky Response Compression Test
  pkg/querier/tripperware/instantquery/instant_query_test.go
  pkg/querier/tripperware/queryrange/query_range_test.go
Labels: size/M

#6244 Add otlp exemplar ingestion test
  integration/e2ecortex/client.go
  integration/otlp_test.go
Labels: size/L
