Repository cortexproject/cortex, pull requests merged in 2025-07, with the labels that each got.

#6856 remove duplicate RingMock
  pkg/compactor/partition_compaction_grouper_test.go
  pkg/compactor/shuffle_sharding_grouper_test.go
  pkg/ring/mock.go
  pkg/ring/util_test.go
Labels: size/L, component/ring

#6854 Fixed memory leak in PushStream caused by reusing context
  pkg/ingester/ingester.go
Labels: component/ingester, size/XS, lgtm

#6861 Fix YAML definition to NH docs
  docs/guides/native-histograms.md
Labels: component/documentation, size/XS

#6866 Updating parquet common to latest
  go.mod
  go.sum
  pkg/querier/parquet_queryable.go
  vendor/github.com/prometheus-community/parquet-common/convert/convert.go
  vendor/github.com/prometheus-community/parquet-common/convert/merge.go
  vendor/github.com/prometheus-community/parquet-common/convert/writer.go
  vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go
  vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go
  vendor/github.com/prometheus-community/parquet-common/storage/read_at.go
  vendor/github.com/prometheus-community/parquet-common/util/fixtures.go
  vendor/modules.txt
Labels: dependencies, size/S, go, lgtm

#6859 Add a cortex_slow_queries_total to track # of slow queries
  CHANGELOG.md
  pkg/frontend/transport/handler.go
  pkg/frontend/transport/handler_test.go
Labels: type/observability, size/M, component/query-frontend, lgtm

#6872 Fix flaky TestBasicLifecycler_HeartbeatWhileStopping
  pkg/ring/basic_lifecycler_test.go
Labels: type/flaky-test, size/XS

#6818 Add proposal for user overrides API
  docs/proposals/user-overrides-api.md
Labels: component/documentation, size/M, lgtm

#6789 Proposal for distributed query execution
  docs/proposals/distributed-query-execution.md
  website/static/images/proposals/distributed-execution-arch.png
  website/static/images/proposals/distributed-execution-assigned-fragments.png
  website/static/images/proposals/distributed-execution-logical-plan.png
  website/static/images/proposals/distributed-execution-optimized-plan.png
  website/static/images/proposals/distributed-execution-plan-fragments.png
  website/static/images/proposals/distributed-execution-scheduler-queue.png
Labels: size/L, lgtm

#6881 Do not use buffer pool when message is not releasable
  pkg/cortexpb/codec.go
  pkg/cortexpb/codec_test.go
Labels: size/L

#6891 docs: Add warning for inmemory ha-tracker to clarify its usage
  docs/configuration/arguments.md
Labels: component/documentation, size/XS, component/ha-tracker, lgtm

#6896 Update parquet common to latest main
  go.mod
  go.sum
  vendor/github.com/prometheus-community/parquet-common/convert/convert.go
  vendor/github.com/prometheus-community/parquet-common/queryable/parquet_queryable.go
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/github.com/prometheus-community/parquet-common/search/rowrange.go
  vendor/modules.txt
Labels: dependencies, size/XS, go

#6901 New metric for ingester errors
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/instance_limits.go
  pkg/ingester/metrics.go
Labels: component/ingester, size/S, lgtm

#6900 Add zone label to ring_members metric.
  CHANGELOG.md
  pkg/ring/ring.go
  pkg/ring/ring_test.go
Labels: size/L, component/ring, lgtm

#6909 Add query-frontend response compression integration test
  integration/query_response_compression_test.go
Labels: size/L, component/query-frontend

#6873 Querier: Support configuring optimizers and XFunctions
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/querier_test.go
  pkg/configs/userconfig/config.go
  pkg/configs/userconfig/config_test.go
  pkg/cortex/cortex.go
  pkg/cortex/modules.go
  pkg/engine/config.go
  pkg/engine/engine.go
  pkg/engine/engine_test.go
  pkg/parser/parser.go
  pkg/querier/querier.go
  pkg/querier/tripperware/instantquery/instant_query_middlewares_test.go
  pkg/querier/tripperware/instantquery/limits.go
  pkg/querier/tripperware/instantquery/limits_test.go
  pkg/querier/tripperware/merge.go
  pkg/querier/tripperware/query_attribute_matcher.go
  pkg/querier/tripperware/queryrange/limits.go
  pkg/querier/tripperware/queryrange/limits_test.go
  pkg/querier/tripperware/queryrange/query_range_middlewares_test.go
  pkg/querier/tripperware/queryrange/results_cache.go
  pkg/querier/tripperware/queryrange/split_by_interval.go
  pkg/querier/tripperware/queryrange/split_by_interval_test.go
  pkg/querier/tripperware/roundtrip.go
  pkg/querier/tripperware/roundtrip_test.go
  pkg/querier/tripperware/subquery.go
  pkg/querier/tripperware/test_shard_by_query_utils.go
  pkg/querysharding/util.go
  pkg/ruler/compat.go
  pkg/ruler/ruler.go
  pkg/util/promql/promql_test.go
  pkg/util/time_test.go
Labels: component/querier, size/L

#6911 docs: fix typos in configuration/arguments.md
  docs/configuration/arguments.md
Labels: component/documentation, size/M

#6913 docs: fix typos in main README.md
  README.md
Labels: component/documentation, size/S, lgtm

#6918 Delete unused proto gen script
  Makefile
Labels: size/XS

#6915 docs: Add Open-Xchange to ADOPTERS.md
  ADOPTERS.md
Labels: size/XS, lgtm

#6923 Exposing parquet configs
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  docs/guides/parquet-mode.md
  pkg/cortex/cortex.go
  pkg/parquetconverter/converter.go
  pkg/querier/querier.go
Labels: component/querier, size/L

#6848 add zstd and snappy compression for query api
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  integration/query_frontend_test.go
  pkg/api/queryapi/compression.go
  pkg/api/queryapi/compression_test.go
  pkg/api/queryapi/query_api.go
  pkg/frontend/transport/handler.go
  pkg/querier/querier.go
  pkg/querier/tripperware/instantquery/instant_query.go
  pkg/querier/tripperware/query.go
  pkg/querier/tripperware/query_test.go
  pkg/querier/tripperware/queryrange/query_range.go
Labels: component/querier, size/L, lgtm

#6927 reoder changelog
  CHANGELOG.md
Labels: size/XS

#6906 Update GOVERNANCE.md
  GOVERNANCE.md
Labels: size/XS, lgtm

#6907 Update roadmap.md
  docs/roadmap.md
Labels: component/documentation, size/S, lgtm

#6902 Emit error when the rule synchronization fails
  CHANGELOG.md
  pkg/ruler/ruler.go
  pkg/ruler/ruler_test.go
Labels: component/rules, size/M
