Repository cortexproject/cortex, pull requests merged in 2025-05, with the labels that each got.

#6730 Update shuffle-sharding.md
  docs/guides/shuffle-sharding.md
Labels: component/documentation, size/XS, lgtm

#6731 Update prometheus to c3ce1f1
  go.mod
  vendor/modules.txt
Labels: dependencies, size/XS, sync-vendor, lgtm

#6728 Create issue template for new blog posts
  .github/ISSUE_TEMPLATE/blog_post.yml
Labels: size/M

#6737 upgrade docker image
  .github/workflows/scripts/install-docker.sh
Labels: size/XS

#6729 Fix flaky TestSchedulerShutdown_FrontendLoop
  pkg/scheduler/scheduler_test.go
Labels: type/flaky-test, size/XS

#6740 Upgrade golangci linter image
  build-image/Dockerfile
Labels: size/XS, component/build, lgtm

#6735 chore: Delete dead code at ruler storage
  .golangci.yml
  pkg/ruler/storage.go
Labels: type/chore, component/rules, size/XS

#6580 Implement stream connection for remote write
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  docs/configuration/v1-guarantees.md
  integration/ingester_stream_push_test.go
  pkg/cortexpb/cortex.pb.go
  pkg/cortexpb/cortex.proto
  pkg/distributor/distributor.go
  pkg/distributor/distributor_test.go
  pkg/ingester/client/client.go
  pkg/ingester/client/client_test.go
  pkg/ingester/client/cortex_mock_test.go
  pkg/ingester/client/ingester.pb.go
  pkg/ingester/client/ingester.proto
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
Labels: component/ingester, component/distributor, size/XL

#6744 Add ingester.skip-metadata-limits flag
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  integration/backward_compatibility_test.go
  pkg/ingester/ingester.go
  pkg/ingester/user_metrics_metadata.go
  pkg/ingester/user_metrics_metadata_test.go
Labels: component/ingester, size/L

#6746 Push request should fail when label set is out of order
  CHANGELOG.md
  pkg/ingester/ingester.go
  pkg/ingester/ingester_test.go
  pkg/ingester/metrics.go
Labels: component/ingester, size/M

#6749 Update dependabot.yml
  .github/dependabot.yml
Labels: dependencies, size/XS, ci/cd

#6750 Fix data race in TestRecoverAlertsPostOutage
  pkg/ruler/manager.go
  pkg/ruler/ruler_test.go
Labels: component/rules, size/M

#6714 Add querier.ingester-query-max-attempts to retry on partial data.
  CHANGELOG.md
  docs/blocks-storage/querier.md
  docs/configuration/config-file-reference.md
  pkg/querier/distributor_queryable.go
  pkg/querier/distributor_queryable_test.go
  pkg/querier/querier.go
  pkg/querier/querier_test.go
Labels: component/querier, size/L

#6727 Validate tenantID on single resolver
  CHANGELOG.md
  pkg/tenant/resolver.go
  pkg/tenant/resolver_test.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
Labels: size/L, lgtm

#6755 Update go to 1.24.3
  build-image/Dockerfile
Labels: size/XS, go

#6751 Fix TestNativeHistogramFuzz to cover queries that contain count_values
  integration/query_fuzz_test.go
Labels: size/M, type/tests

#6756 chore: upgrade thanos-io/promql-engine
  go.mod
  go.sum
  vendor/github.com/thanos-io/promql-engine/engine/engine.go
  vendor/github.com/thanos-io/promql-engine/engine/sort.go
  vendor/github.com/thanos-io/promql-engine/execution/aggregate/khashaggregate.go
  vendor/github.com/thanos-io/promql-engine/execution/aggregate/scalar_table.go
  vendor/github.com/thanos-io/promql-engine/execution/execution.go
  vendor/github.com/thanos-io/promql-engine/execution/function/absent.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/distribute.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/propagate_selectors.go
  vendor/github.com/thanos-io/promql-engine/logicalplan/set_batch_size.go
  vendor/github.com/thanos-io/promql-engine/ringbuffer/generic.go
  vendor/github.com/thanos-io/promql-engine/ringbuffer/rate.go
  vendor/golang.org/x/crypto/cryptobyte/asn1.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/gcexportdata/gcexportdata.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/typeutil/callee.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/gcimporter/iexport.go
  vendor/golang.org/x/tools/internal/gcimporter/iimport.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/pkgbits/decoder.go
  vendor/golang.org/x/tools/internal/stdlib/deps.go
  vendor/golang.org/x/tools/internal/stdlib/manifest.go
  vendor/golang.org/x/tools/internal/stdlib/stdlib.go
  vendor/golang.org/x/tools/internal/typeparams/free.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/golang.org/x/tools/internal/typesinternal/classify_call.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: dependencies, size/S, lgtm

#6712 Add proposal for parquet storage
  docs/proposals/parquet-storage.md
Labels: component/documentation, size/L, lgtm

#6759 Add compactor percentage based sharding
  CHANGELOG.md
  docs/configuration/config-file-reference.md
  pkg/compactor/compactor.go
  pkg/compactor/compactor_test.go
  pkg/compactor/partition_compaction_grouper.go
  pkg/compactor/shuffle_sharding_grouper.go
  pkg/util/validation/limits.go
Labels: size/L, component/compactor

#6761 Add __markers__ tenantID validation
  CHANGELOG.md
  docs/guides/limitations.md
  pkg/storage/tsdb/tenant_deletion_mark.go
  pkg/storage/tsdb/users_scanner.go
  pkg/tenant/resolver_test.go
  pkg/tenant/tenant.go
  pkg/tenant/tenant_test.go
  pkg/util/allowed_tenants.go
Labels: size/M, lgtm

#6743 Implementing Parquet Queryable with fallback
  CHANGELOG.md
  go.mod
  go.sum
  integration/parquet_querier_test.go
  pkg/compactor/blocks_cleaner.go
  pkg/compactor/blocks_cleaner_test.go
  pkg/compactor/compactor.go
  pkg/cortex/modules.go
  pkg/parquetconverter/converter.go
  pkg/parquetconverter/converter_test.go
  pkg/querier/block.go
  pkg/querier/blocks_store_queryable.go
  pkg/querier/blocks_store_queryable_test.go
  pkg/querier/parquet_queryable.go
  pkg/querier/parquet_queryable_test.go
  pkg/querier/querier.go
  pkg/util/validation/limits.go
  vendor/github.com/prometheus-community/parquet-common/convert/convert.go
  vendor/github.com/prometheus-community/parquet-common/convert/merge.go
  vendor/github.com/prometheus-community/parquet-common/convert/writer.go
  vendor/github.com/prometheus-community/parquet-common/schema/encoder.go
  vendor/github.com/prometheus-community/parquet-common/schema/schema.go
  vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/github.com/prometheus-community/parquet-common/search/parquet_queriable.go
  vendor/github.com/prometheus-community/parquet-common/search/rowrange.go
  vendor/github.com/prometheus-community/parquet-common/storage/bucket_read_at.go
  vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go
  vendor/github.com/prometheus-community/parquet-common/util/bucket_read_at.go
  vendor/github.com/prometheus-community/parquet-common/util/strutil.go
  vendor/github.com/prometheus-community/parquet-common/util/util.go
  vendor/modules.txt
Labels: component/querier, size/XL, storage/blocks, sync-vendor, go

#6762 Changing flag from `query-parquet-files` to 'enable_parquet_queryable'
  integration/parquet_querier_test.go
  pkg/cortex/modules.go
  pkg/querier/querier.go
Labels: component/querier, size/XS

#6764 Fallback to the blocks queryable if vertical sharding is enabled
  go.mod
  go.sum
  pkg/parquetconverter/converter.go
  pkg/querier/parquet_queryable.go
  pkg/querier/parquet_queryable_test.go
  vendor/github.com/prometheus-community/parquet-common/convert/convert.go
  vendor/github.com/prometheus-community/parquet-common/convert/writer.go
  vendor/github.com/prometheus-community/parquet-common/schema/encoder.go
  vendor/github.com/prometheus-community/parquet-common/schema/schema_builder.go
  vendor/github.com/prometheus-community/parquet-common/search/constraint.go
  vendor/github.com/prometheus-community/parquet-common/search/materialize.go
  vendor/github.com/prometheus-community/parquet-common/search/parquet_queriable.go
  vendor/github.com/prometheus-community/parquet-common/storage/bucket_read_at.go
  vendor/github.com/prometheus-community/parquet-common/storage/parquet_shard.go
  vendor/modules.txt
Labels: component/querier, size/L, storage/blocks

#6773 Fix race condition in active user
  CHANGELOG.md
  pkg/util/active_user.go
Labels: type/bug, size/XS

#6775 Caching Parquet shards
  pkg/querier/parquet_queryable.go
  pkg/querier/querier.go
Labels: component/querier, size/L
